//
// BolusCalculationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class BolusCalculationAPI {

    /**
     Creates a new record and returns it with a `Location` header pointing to the created resource.
     
     - parameter upsertBolusCalculationRequest: (body) The data used to create the record. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BolusCalculation
     */
    open class func bolusCalculationCreate(upsertBolusCalculationRequest: UpsertBolusCalculationRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> BolusCalculation {
        return try await bolusCalculationCreateWithRequestBuilder(upsertBolusCalculationRequest: upsertBolusCalculationRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Creates a new record and returns it with a `Location` header pointing to the created resource.
     - POST /api/v4/insulin/calculations
     - `Timestamp` must be set on the mapped model; requests that resolve to a default timestamp are rejected with `400 Bad Request`.              On success, responds with `201 Created` and a `Location` header containing the URL of the newly created record.
     - parameter upsertBolusCalculationRequest: (body) The data used to create the record. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BolusCalculation> 
     */
    open class func bolusCalculationCreateWithRequestBuilder(upsertBolusCalculationRequest: UpsertBolusCalculationRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<BolusCalculation> {
        let localVariablePath = "/api/v4/insulin/calculations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: upsertBolusCalculationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BolusCalculation>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Deletes a record by ID.
     
     - parameter id: (path) The unique identifier of the record to delete. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func bolusCalculationDelete(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await bolusCalculationDeleteWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Deletes a record by ID.
     - DELETE /api/v4/insulin/calculations/{id}
     - Returns `204 No Content` on success, or `404 Not Found` if no record with the given id exists.
     - parameter id: (path) The unique identifier of the record to delete. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func bolusCalculationDeleteWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v4/insulin/calculations/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Lists records with pagination, optional date range, device, and source filtering.
     
     - parameter from: (query) Inclusive start of the date range filter. (optional)
     - parameter to: (query) Inclusive end of the date range filter. (optional)
     - parameter limit: (query) Maximum number of records to return. Defaults to &#x60;100&#x60;. (optional, default to 100)
     - parameter offset: (query) Number of records to skip for pagination. Defaults to &#x60;0&#x60;. (optional, default to 0)
     - parameter sort: (query) Sort order for results by timestamp. Defaults to &#x60;timestamp_desc&#x60;. (optional, default to "timestamp_desc")
     - parameter device: (query) Optional filter to restrict results to a specific device. (optional)
     - parameter source: (query) Optional filter to restrict results to a specific data source. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PaginatedResponseOfBolusCalculation
     */
    open class func bolusCalculationGetAll(from: Date? = nil, to: Date? = nil, limit: Int? = nil, offset: Int? = nil, sort: String? = nil, device: String? = nil, source: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> PaginatedResponseOfBolusCalculation {
        return try await bolusCalculationGetAllWithRequestBuilder(from: from, to: to, limit: limit, offset: offset, sort: sort, device: device, source: source, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Lists records with pagination, optional date range, device, and source filtering.
     - GET /api/v4/insulin/calculations
     - The `sort` parameter accepts exactly two values: - `timestamp_asc` — oldest records first - `timestamp_desc` — newest records first (default)              Use `limit` and `offset` together for paginated access to large result sets.
     - parameter from: (query) Inclusive start of the date range filter. (optional)
     - parameter to: (query) Inclusive end of the date range filter. (optional)
     - parameter limit: (query) Maximum number of records to return. Defaults to &#x60;100&#x60;. (optional, default to 100)
     - parameter offset: (query) Number of records to skip for pagination. Defaults to &#x60;0&#x60;. (optional, default to 0)
     - parameter sort: (query) Sort order for results by timestamp. Defaults to &#x60;timestamp_desc&#x60;. (optional, default to "timestamp_desc")
     - parameter device: (query) Optional filter to restrict results to a specific device. (optional)
     - parameter source: (query) Optional filter to restrict results to a specific data source. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PaginatedResponseOfBolusCalculation> 
     */
    open class func bolusCalculationGetAllWithRequestBuilder(from: Date? = nil, to: Date? = nil, limit: Int? = nil, offset: Int? = nil, sort: String? = nil, device: String? = nil, source: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<PaginatedResponseOfBolusCalculation> {
        let localVariablePath = "/api/v4/insulin/calculations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "device": (wrappedValue: device?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "source": (wrappedValue: source?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedResponseOfBolusCalculation>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Retrieves a single record by its unique identifier.
     
     - parameter id: (path) The unique identifier of the record. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BolusCalculation
     */
    open class func bolusCalculationGetById(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> BolusCalculation {
        return try await bolusCalculationGetByIdWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieves a single record by its unique identifier.
     - GET /api/v4/insulin/calculations/{id}
     - Returns `404 Not Found` if no record with the given id exists.
     - parameter id: (path) The unique identifier of the record. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BolusCalculation> 
     */
    open class func bolusCalculationGetByIdWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<BolusCalculation> {
        var localVariablePath = "/api/v4/insulin/calculations/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BolusCalculation>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Updates an existing record by ID and returns the updated record.
     
     - parameter id: (path) The unique identifier of the record to update. 
     - parameter upsertBolusCalculationRequest: (body) The data to apply to the existing record. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BolusCalculation
     */
    open class func bolusCalculationUpdate(id: String, upsertBolusCalculationRequest: UpsertBolusCalculationRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> BolusCalculation {
        return try await bolusCalculationUpdateWithRequestBuilder(id: id, upsertBolusCalculationRequest: upsertBolusCalculationRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Updates an existing record by ID and returns the updated record.
     - PUT /api/v4/insulin/calculations/{id}
     - Returns `404 Not Found` if no record with the given id exists.              `Timestamp` must be set on the mapped model; requests that resolve to a default timestamp are rejected with `400 Bad Request`.
     - parameter id: (path) The unique identifier of the record to update. 
     - parameter upsertBolusCalculationRequest: (body) The data to apply to the existing record. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BolusCalculation> 
     */
    open class func bolusCalculationUpdateWithRequestBuilder(id: String, upsertBolusCalculationRequest: UpsertBolusCalculationRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<BolusCalculation> {
        var localVariablePath = "/api/v4/insulin/calculations/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: upsertBolusCalculationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BolusCalculation>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
