//
// ConnectedAppsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ConnectedAppsAPI {

    /**
     List all connected apps (OAuth app grants) for the authenticated user on the current tenant.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ConnectedAppDto]
     */
    open class func connectedAppsList(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ConnectedAppDto] {
        return try await connectedAppsListWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all connected apps (OAuth app grants) for the authenticated user on the current tenant.
     - GET /api/v4/account/connected-apps
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ConnectedAppDto]> 
     */
    open class func connectedAppsListWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[ConnectedAppDto]> {
        let localVariablePath = "/api/v4/account/connected-apps"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ConnectedAppDto]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Revoke a connected app. Soft-deletes the grant and invalidates all associated refresh tokens; previously-issued access tokens become unusable on next request via the revocation cache.
     
     - parameter grantId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func connectedAppsRevoke(grantId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await connectedAppsRevokeWithRequestBuilder(grantId: grantId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Revoke a connected app. Soft-deletes the grant and invalidates all associated refresh tokens; previously-issued access tokens become unusable on next request via the revocation cache.
     - DELETE /api/v4/account/connected-apps/{grantId}
     - parameter grantId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func connectedAppsRevokeWithRequestBuilder(grantId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v4/account/connected-apps/{grantId}"
        let grantIdPreEscape = "\(APIHelper.mapValueToPathItem(grantId))"
        let grantIdPostEscape = grantIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{grantId}", with: grantIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
