//
// CorrelationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CorrelationAPI {

    /**
     Retrieves all records that share the given correlation ID across every V4 data type.
     
     - parameter correlationId: (path) The shared correlation ID to look up. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func correlationGetCorrelated(correlationId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await correlationGetCorrelatedWithRequestBuilder(correlationId: correlationId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retrieves all records that share the given correlation ID across every V4 data type.
     - GET /api/v4/correlated/{correlationId}
     - parameter correlationId: (path) The shared correlation ID to look up. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func correlationGetCorrelatedWithRequestBuilder(correlationId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v4/correlated/{correlationId}"
        let correlationIdPreEscape = "\(APIHelper.mapValueToPathItem(correlationId))"
        let correlationIdPostEscape = correlationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{correlationId}", with: correlationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
