//
// DevAuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DevAuthAPI {

    /**
     Export registered passkeys as a dev identity fixture. Save the output to docs/seed/dev-identities.json (committable — WebAuthn public keys are not secret) and startup re-seeds it after every DB wipe, while seed-tenant adds each fixture subject as an owner of new tenants. Synthetic dev-seed credentials are excluded. Optional ?username= filters to one identity.
     
     - parameter username: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DevIdentityFixtureFile
     */
    open class func devAuthExportPasskeyFixture(username: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DevIdentityFixtureFile {
        return try await devAuthExportPasskeyFixtureWithRequestBuilder(username: username, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Export registered passkeys as a dev identity fixture. Save the output to docs/seed/dev-identities.json (committable — WebAuthn public keys are not secret) and startup re-seeds it after every DB wipe, while seed-tenant adds each fixture subject as an owner of new tenants. Synthetic dev-seed credentials are excluded. Optional ?username= filters to one identity.
     - GET /api/v4/dev-only/auth/passkey-fixture
     - parameter username: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DevIdentityFixtureFile> 
     */
    open class func devAuthExportPasskeyFixtureWithRequestBuilder(username: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<DevIdentityFixtureFile> {
        let localVariablePath = "/api/v4/dev-only/auth/passkey-fixture"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "username": (wrappedValue: username?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DevIdentityFixtureFile>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Log in as a tenant member without a WebAuthn ceremony and set the normal session cookies. Navigating a browser to this URL on a tenant subdomain (e.g. https://sleepy.nocturne.localhost:1612/api/v4/dev-only/auth/login) leaves it authenticated and redirects into the app. The tenant resolves from the ?tenant slug, else from the request host; the member from ?username, else the first owner-role member, else the first member. Add format=json to get the token pair instead of a redirect. A state-changing GET is deliberate — browser navigation is the use case — which makes it CSRF-able while a dev stack runs; acceptable only because the controller does not exist outside Development.
     
     - parameter tenant: (query)  (optional)
     - parameter username: (query)  (optional)
     - parameter redirect: (query)  (optional)
     - parameter format: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: URL
     */
    open class func devAuthLogin(tenant: String? = nil, username: String? = nil, redirect: String? = nil, format: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> URL {
        return try await devAuthLoginWithRequestBuilder(tenant: tenant, username: username, redirect: redirect, format: format, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Log in as a tenant member without a WebAuthn ceremony and set the normal session cookies. Navigating a browser to this URL on a tenant subdomain (e.g. https://sleepy.nocturne.localhost:1612/api/v4/dev-only/auth/login) leaves it authenticated and redirects into the app. The tenant resolves from the ?tenant slug, else from the request host; the member from ?username, else the first owner-role member, else the first member. Add format=json to get the token pair instead of a redirect. A state-changing GET is deliberate — browser navigation is the use case — which makes it CSRF-able while a dev stack runs; acceptable only because the controller does not exist outside Development.
     - GET /api/v4/dev-only/auth/login
     - parameter tenant: (query)  (optional)
     - parameter username: (query)  (optional)
     - parameter redirect: (query)  (optional)
     - parameter format: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<URL> 
     */
    open class func devAuthLoginWithRequestBuilder(tenant: String? = nil, username: String? = nil, redirect: String? = nil, format: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<URL> {
        let localVariablePath = "/api/v4/dev-only/auth/login"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenant": (wrappedValue: tenant?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "username": (wrappedValue: username?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "redirect": (wrappedValue: redirect?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "format": (wrappedValue: format?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     JSON variant of Login for headless clients: returns the token pair (and also sets the session cookies on the response).
     
     - parameter devLoginRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DevLoginResponse
     */
    open class func devAuthLoginJson(devLoginRequest: DevLoginRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DevLoginResponse {
        return try await devAuthLoginJsonWithRequestBuilder(devLoginRequest: devLoginRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     JSON variant of Login for headless clients: returns the token pair (and also sets the session cookies on the response).
     - POST /api/v4/dev-only/auth/login
     - parameter devLoginRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DevLoginResponse> 
     */
    open class func devAuthLoginJsonWithRequestBuilder(devLoginRequest: DevLoginRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<DevLoginResponse> {
        let localVariablePath = "/api/v4/dev-only/auth/login"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: devLoginRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DevLoginResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
