//
// DeviceCatalogAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DeviceCatalogAPI {

    /**
     Get all known device models.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [DeviceCatalogEntry]
     */
    open class func deviceCatalogGetCatalog(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [DeviceCatalogEntry] {
        return try await deviceCatalogGetCatalogWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all known device models.
     - GET /api/v4/devices/catalog
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[DeviceCatalogEntry]> 
     */
    open class func deviceCatalogGetCatalogWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[DeviceCatalogEntry]> {
        let localVariablePath = "/api/v4/devices/catalog"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[DeviceCatalogEntry]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get device models filtered by category.
     
     - parameter category: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [DeviceCatalogEntry]
     */
    open class func deviceCatalogGetCatalogByCategory(category: DeviceCategory, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [DeviceCatalogEntry] {
        return try await deviceCatalogGetCatalogByCategoryWithRequestBuilder(category: category, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get device models filtered by category.
     - GET /api/v4/devices/catalog/{category}
     - parameter category: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[DeviceCatalogEntry]> 
     */
    open class func deviceCatalogGetCatalogByCategoryWithRequestBuilder(category: DeviceCategory, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[DeviceCatalogEntry]> {
        var localVariablePath = "/api/v4/devices/catalog/{category}"
        let categoryPreEscape = "\(APIHelper.mapValueToPathItem(category))"
        let categoryPostEscape = categoryPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{category}", with: categoryPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[DeviceCatalogEntry]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
