//
// InsulinCatalogAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class InsulinCatalogAPI {

    /**
     Get all known insulin formulations.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [InsulinFormulation]
     */
    open class func insulinCatalogGetCatalog(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [InsulinFormulation] {
        return try await insulinCatalogGetCatalogWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all known insulin formulations.
     - GET /api/v4/insulins/catalog
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[InsulinFormulation]> 
     */
    open class func insulinCatalogGetCatalogWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[InsulinFormulation]> {
        let localVariablePath = "/api/v4/insulins/catalog"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[InsulinFormulation]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get insulin formulations filtered by category.
     
     - parameter category: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [InsulinFormulation]
     */
    open class func insulinCatalogGetCatalogByCategory(category: InsulinCategory, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [InsulinFormulation] {
        return try await insulinCatalogGetCatalogByCategoryWithRequestBuilder(category: category, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get insulin formulations filtered by category.
     - GET /api/v4/insulins/catalog/{category}
     - parameter category: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[InsulinFormulation]> 
     */
    open class func insulinCatalogGetCatalogByCategoryWithRequestBuilder(category: InsulinCategory, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[InsulinFormulation]> {
        var localVariablePath = "/api/v4/insulins/catalog/{category}"
        let categoryPreEscape = "\(APIHelper.mapValueToPathItem(category))"
        let categoryPostEscape = categoryPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{category}", with: categoryPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[InsulinFormulation]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
