//
// MembershipRequestAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MembershipRequestAPI {

    /**
     Approve a membership request and add the user as a tenant member.
     
     - parameter id: (path)  
     - parameter approveMembershipRequestRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DecideMembershipRequestResult
     */
    open class func membershipRequestApproveRequest(id: String, approveMembershipRequestRequest: ApproveMembershipRequestRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DecideMembershipRequestResult {
        return try await membershipRequestApproveRequestWithRequestBuilder(id: id, approveMembershipRequestRequest: approveMembershipRequestRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Approve a membership request and add the user as a tenant member.
     - POST /api/v4/membership-requests/{id}/approve
     - parameter id: (path)  
     - parameter approveMembershipRequestRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DecideMembershipRequestResult> 
     */
    open class func membershipRequestApproveRequestWithRequestBuilder(id: String, approveMembershipRequestRequest: ApproveMembershipRequestRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<DecideMembershipRequestResult> {
        var localVariablePath = "/api/v4/membership-requests/{id}/approve"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: approveMembershipRequestRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DecideMembershipRequestResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Submit a request to join the current tenant.
     
     - parameter createMembershipRequestRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateMembershipRequestResult
     */
    open class func membershipRequestCreateRequest(createMembershipRequestRequest: CreateMembershipRequestRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateMembershipRequestResult {
        return try await membershipRequestCreateRequestWithRequestBuilder(createMembershipRequestRequest: createMembershipRequestRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Submit a request to join the current tenant.
     - POST /api/v4/membership-requests
     - parameter createMembershipRequestRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateMembershipRequestResult> 
     */
    open class func membershipRequestCreateRequestWithRequestBuilder(createMembershipRequestRequest: CreateMembershipRequestRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<CreateMembershipRequestResult> {
        let localVariablePath = "/api/v4/membership-requests"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createMembershipRequestRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateMembershipRequestResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Deny a membership request.
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DecideMembershipRequestResult
     */
    open class func membershipRequestDenyRequest(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DecideMembershipRequestResult {
        return try await membershipRequestDenyRequestWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Deny a membership request.
     - POST /api/v4/membership-requests/{id}/deny
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DecideMembershipRequestResult> 
     */
    open class func membershipRequestDenyRequestWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<DecideMembershipRequestResult> {
        var localVariablePath = "/api/v4/membership-requests/{id}/deny"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DecideMembershipRequestResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get whether this tenant currently lets people request to become a member.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MembershipRequestSettingsDto
     */
    open class func membershipRequestGetMembershipRequestSettings(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> MembershipRequestSettingsDto {
        return try await membershipRequestGetMembershipRequestSettingsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get whether this tenant currently lets people request to become a member.
     - GET /api/v4/membership-requests/settings
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MembershipRequestSettingsDto> 
     */
    open class func membershipRequestGetMembershipRequestSettingsWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<MembershipRequestSettingsDto> {
        let localVariablePath = "/api/v4/membership-requests/settings"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MembershipRequestSettingsDto>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get the current user's membership request for this tenant, if any.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MembershipRequestDto
     */
    open class func membershipRequestGetMyRequest(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> MembershipRequestDto {
        return try await membershipRequestGetMyRequestWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get the current user's membership request for this tenant, if any.
     - GET /api/v4/membership-requests/mine
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MembershipRequestDto> 
     */
    open class func membershipRequestGetMyRequestWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<MembershipRequestDto> {
        let localVariablePath = "/api/v4/membership-requests/mine"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MembershipRequestDto>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List all pending membership requests for the current tenant.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [MembershipRequestDto]
     */
    open class func membershipRequestGetPendingRequests(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [MembershipRequestDto] {
        return try await membershipRequestGetPendingRequestsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all pending membership requests for the current tenant.
     - GET /api/v4/membership-requests
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[MembershipRequestDto]> 
     */
    open class func membershipRequestGetPendingRequestsWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[MembershipRequestDto]> {
        let localVariablePath = "/api/v4/membership-requests"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[MembershipRequestDto]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Enable or disable whether people can request to become a member. Independent of public access.
     
     - parameter updateMembershipRequestSettingsRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MembershipRequestSettingsDto
     */
    open class func membershipRequestSetMembershipRequestSettings(updateMembershipRequestSettingsRequest: UpdateMembershipRequestSettingsRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> MembershipRequestSettingsDto {
        return try await membershipRequestSetMembershipRequestSettingsWithRequestBuilder(updateMembershipRequestSettingsRequest: updateMembershipRequestSettingsRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Enable or disable whether people can request to become a member. Independent of public access.
     - PUT /api/v4/membership-requests/settings
     - parameter updateMembershipRequestSettingsRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MembershipRequestSettingsDto> 
     */
    open class func membershipRequestSetMembershipRequestSettingsWithRequestBuilder(updateMembershipRequestSettingsRequest: UpdateMembershipRequestSettingsRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<MembershipRequestSettingsDto> {
        let localVariablePath = "/api/v4/membership-requests/settings"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateMembershipRequestSettingsRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MembershipRequestSettingsDto>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
