//
// MigrationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MigrationAPI {

    /**

     - parameter jobId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func migrationCancelMigration(jobId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await migrationCancelMigrationWithRequestBuilder(jobId: jobId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v4/migration/{jobId}/cancel
     - parameter jobId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func migrationCancelMigrationWithRequestBuilder(jobId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v4/migration/{jobId}/cancel"
        let jobIdPreEscape = "\(APIHelper.mapValueToPathItem(jobId))"
        let jobIdPostEscape = jobIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobId}", with: jobIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: [MigrationJobInfo]
     */
    open class func migrationGetHistory(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [MigrationJobInfo] {
        return try await migrationGetHistoryWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v4/migration/history
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[MigrationJobInfo]> 
     */
    open class func migrationGetHistoryWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[MigrationJobInfo]> {
        let localVariablePath = "/api/v4/migration/history"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[MigrationJobInfo]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: PendingMigrationConfig
     */
    open class func migrationGetPendingConfig(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> PendingMigrationConfig {
        return try await migrationGetPendingConfigWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v4/migration/pending-config
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PendingMigrationConfig> 
     */
    open class func migrationGetPendingConfigWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<PendingMigrationConfig> {
        let localVariablePath = "/api/v4/migration/pending-config"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PendingMigrationConfig>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: [MigrationSourceDto]
     */
    open class func migrationGetSources(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [MigrationSourceDto] {
        return try await migrationGetSourcesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v4/migration/sources
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[MigrationSourceDto]> 
     */
    open class func migrationGetSourcesWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[MigrationSourceDto]> {
        let localVariablePath = "/api/v4/migration/sources"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[MigrationSourceDto]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter jobId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MigrationJobStatus
     */
    open class func migrationGetStatus(jobId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> MigrationJobStatus {
        return try await migrationGetStatusWithRequestBuilder(jobId: jobId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v4/migration/{jobId}/status
     - parameter jobId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MigrationJobStatus> 
     */
    open class func migrationGetStatusWithRequestBuilder(jobId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<MigrationJobStatus> {
        var localVariablePath = "/api/v4/migration/{jobId}/status"
        let jobIdPreEscape = "\(APIHelper.mapValueToPathItem(jobId))"
        let jobIdPostEscape = jobIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobId}", with: jobIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MigrationJobStatus>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Start a migration using saved connector credentials (e.g., after Nightscout connector setup).
     
     - parameter connectorName: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MigrationJobInfo
     */
    open class func migrationStartFromConnector(connectorName: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> MigrationJobInfo {
        return try await migrationStartFromConnectorWithRequestBuilder(connectorName: connectorName, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start a migration using saved connector credentials (e.g., after Nightscout connector setup).
     - POST /api/v4/migration/start-from-connector/{connectorName}
     - parameter connectorName: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MigrationJobInfo> 
     */
    open class func migrationStartFromConnectorWithRequestBuilder(connectorName: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<MigrationJobInfo> {
        var localVariablePath = "/api/v4/migration/start-from-connector/{connectorName}"
        let connectorNamePreEscape = "\(APIHelper.mapValueToPathItem(connectorName))"
        let connectorNamePostEscape = connectorNamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{connectorName}", with: connectorNamePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MigrationJobInfo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter startMigrationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MigrationJobInfo
     */
    open class func migrationStartMigration(startMigrationRequest: StartMigrationRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> MigrationJobInfo {
        return try await migrationStartMigrationWithRequestBuilder(startMigrationRequest: startMigrationRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v4/migration/start
     - parameter startMigrationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MigrationJobInfo> 
     */
    open class func migrationStartMigrationWithRequestBuilder(startMigrationRequest: StartMigrationRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<MigrationJobInfo> {
        let localVariablePath = "/api/v4/migration/start"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: startMigrationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MigrationJobInfo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter testMigrationConnectionRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TestMigrationConnectionResult
     */
    open class func migrationTestConnection(testMigrationConnectionRequest: TestMigrationConnectionRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> TestMigrationConnectionResult {
        return try await migrationTestConnectionWithRequestBuilder(testMigrationConnectionRequest: testMigrationConnectionRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v4/migration/test
     - parameter testMigrationConnectionRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TestMigrationConnectionResult> 
     */
    open class func migrationTestConnectionWithRequestBuilder(testMigrationConnectionRequest: TestMigrationConnectionRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<TestMigrationConnectionResult> {
        let localVariablePath = "/api/v4/migration/test"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: testMigrationConnectionRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TestMigrationConnectionResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
