//
// NightscoutTransitionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class NightscoutTransitionAPI {

    /**
     Get the current Nightscout transition status including migration progress, write-back health, and disconnect readiness recommendation.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: NightscoutTransitionStatus
     */
    open class func nightscoutTransitionGetTransitionStatus(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> NightscoutTransitionStatus {
        return try await nightscoutTransitionGetTransitionStatusWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get the current Nightscout transition status including migration progress, write-back health, and disconnect readiness recommendation.
     - GET /api/v4/nightscout-transition/status
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<NightscoutTransitionStatus> 
     */
    open class func nightscoutTransitionGetTransitionStatusWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<NightscoutTransitionStatus> {
        let localVariablePath = "/api/v4/nightscout-transition/status"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NightscoutTransitionStatus>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
