//
// SessionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SessionsAPI {

    /**
     List the authenticated user's active login sessions, most recently active first.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [SessionDto]
     */
    open class func sessionsList(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [SessionDto] {
        return try await sessionsListWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List the authenticated user's active login sessions, most recently active first.
     - GET /api/v4/account/sessions
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[SessionDto]> 
     */
    open class func sessionsListWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[SessionDto]> {
        let localVariablePath = "/api/v4/account/sessions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SessionDto]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Revoke a login session, logging that device out. Revoking the current session is allowed and acts as a logout.
     
     - parameter sessionId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func sessionsRevoke(sessionId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await sessionsRevokeWithRequestBuilder(sessionId: sessionId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Revoke a login session, logging that device out. Revoking the current session is allowed and acts as a logout.
     - DELETE /api/v4/account/sessions/{sessionId}
     - parameter sessionId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func sessionsRevokeWithRequestBuilder(sessionId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v4/account/sessions/{sessionId}"
        let sessionIdPreEscape = "\(APIHelper.mapValueToPathItem(sessionId))"
        let sessionIdPostEscape = sessionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{sessionId}", with: sessionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Revoke every session except the current one (log out everywhere else).
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RevokeOthersResultDto
     */
    open class func sessionsRevokeOthers(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> RevokeOthersResultDto {
        return try await sessionsRevokeOthersWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Revoke every session except the current one (log out everywhere else).
     - POST /api/v4/account/sessions/revoke-others
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RevokeOthersResultDto> 
     */
    open class func sessionsRevokeOthersWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<RevokeOthersResultDto> {
        let localVariablePath = "/api/v4/account/sessions/revoke-others"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RevokeOthersResultDto>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
