//
// SleepAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SleepAPI {

    /**
     Create or upsert a sleep session
     
     - parameter sleepSession: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SleepSession
     */
    open class func sleepCreateSession(sleepSession: SleepSession, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SleepSession {
        return try await sleepCreateSessionWithRequestBuilder(sleepSession: sleepSession, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create or upsert a sleep session
     - POST /api/v4/sleep/sessions
     - parameter sleepSession: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SleepSession> 
     */
    open class func sleepCreateSessionWithRequestBuilder(sleepSession: SleepSession, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<SleepSession> {
        let localVariablePath = "/api/v4/sleep/sessions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sleepSession, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SleepSession>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a sleep session
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func sleepDeleteSession(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await sleepDeleteSessionWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a sleep session
     - DELETE /api/v4/sleep/sessions/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func sleepDeleteSessionWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v4/sleep/sessions/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get a sleep session by ID (includes stages and biometric samples)
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SleepSession
     */
    open class func sleepGetSession(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SleepSession {
        return try await sleepGetSessionWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a sleep session by ID (includes stages and biometric samples)
     - GET /api/v4/sleep/sessions/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SleepSession> 
     */
    open class func sleepGetSessionWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<SleepSession> {
        var localVariablePath = "/api/v4/sleep/sessions/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SleepSession>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Query sleep sessions with optional filtering (stages and biometrics excluded)
     
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter type: (query)  (optional)
     - parameter source: (query)  (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter offset: (query)  (optional, default to 0)
     - parameter sort: (query)  (optional, default to "timestamp_desc")
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PaginatedResponseOfSleepSession
     */
    open class func sleepGetSessions(from: Date? = nil, to: Date? = nil, type: SleepSessionType? = nil, source: SleepSource? = nil, limit: Int? = nil, offset: Int? = nil, sort: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> PaginatedResponseOfSleepSession {
        return try await sleepGetSessionsWithRequestBuilder(from: from, to: to, type: type, source: source, limit: limit, offset: offset, sort: sort, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Query sleep sessions with optional filtering (stages and biometrics excluded)
     - GET /api/v4/sleep/sessions
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter type: (query)  (optional)
     - parameter source: (query)  (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter offset: (query)  (optional, default to 0)
     - parameter sort: (query)  (optional, default to "timestamp_desc")
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PaginatedResponseOfSleepSession> 
     */
    open class func sleepGetSessionsWithRequestBuilder(from: Date? = nil, to: Date? = nil, type: SleepSessionType? = nil, source: SleepSource? = nil, limit: Int? = nil, offset: Int? = nil, sort: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<PaginatedResponseOfSleepSession> {
        let localVariablePath = "/api/v4/sleep/sessions"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        let _qp1: [String: (wrappedValue: (any Sendable)?, isExplode: Bool)] = [
            "from": (wrappedValue: from?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "to": (wrappedValue: to?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "type": (wrappedValue: type?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "source": (wrappedValue: source?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ]
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems(_qp1)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedResponseOfSleepSession>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing sleep session
     
     - parameter id: (path)  
     - parameter sleepSession: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SleepSession
     */
    open class func sleepUpdateSession(id: String, sleepSession: SleepSession, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SleepSession {
        return try await sleepUpdateSessionWithRequestBuilder(id: id, sleepSession: sleepSession, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing sleep session
     - PUT /api/v4/sleep/sessions/{id}
     - parameter id: (path)  
     - parameter sleepSession: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SleepSession> 
     */
    open class func sleepUpdateSessionWithRequestBuilder(id: String, sleepSession: SleepSession, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<SleepSession> {
        var localVariablePath = "/api/v4/sleep/sessions/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sleepSession, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SleepSession>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
