//
// V4ClockFacesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class V4ClockFacesAPI {

    /**
     Create a new clock face
     
     - parameter createClockFaceRequest: (body) Clock face creation request 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ClockFace
     */
    open class func clockFacesCreate(createClockFaceRequest: CreateClockFaceRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ClockFace {
        return try await clockFacesCreateWithRequestBuilder(createClockFaceRequest: createClockFaceRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a new clock face
     - POST /api/v4/clockfaces
     - parameter createClockFaceRequest: (body) Clock face creation request 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ClockFace> 
     */
    open class func clockFacesCreateWithRequestBuilder(createClockFaceRequest: CreateClockFaceRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<ClockFace> {
        let localVariablePath = "/api/v4/clockfaces"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createClockFaceRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ClockFace>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a clock face (owner only)
     
     - parameter id: (path) Clock face UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func clockFacesDelete(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await clockFacesDeleteWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a clock face (owner only)
     - DELETE /api/v4/clockfaces/{id}
     - parameter id: (path) Clock face UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func clockFacesDeleteWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v4/clockfaces/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get a clock face configuration by ID (public, no authentication required)
     
     - parameter id: (path) Clock face UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ClockFacePublicDto
     */
    open class func clockFacesGetById(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ClockFacePublicDto {
        return try await clockFacesGetByIdWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a clock face configuration by ID (public, no authentication required)
     - GET /api/v4/clockfaces/{id}
     - parameter id: (path) Clock face UUID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ClockFacePublicDto> 
     */
    open class func clockFacesGetByIdWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<ClockFacePublicDto> {
        var localVariablePath = "/api/v4/clockfaces/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ClockFacePublicDto>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     List all clock faces for the current user
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ClockFaceListItem]
     */
    open class func clockFacesList(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ClockFaceListItem] {
        return try await clockFacesListWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all clock faces for the current user
     - GET /api/v4/clockfaces
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ClockFaceListItem]> 
     */
    open class func clockFacesListWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[ClockFaceListItem]> {
        let localVariablePath = "/api/v4/clockfaces"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ClockFaceListItem]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing clock face (owner only)
     
     - parameter id: (path) Clock face UUID 
     - parameter updateClockFaceRequest: (body) Update request 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ClockFace
     */
    open class func clockFacesUpdate(id: String, updateClockFaceRequest: UpdateClockFaceRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ClockFace {
        return try await clockFacesUpdateWithRequestBuilder(id: id, updateClockFaceRequest: updateClockFaceRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing clock face (owner only)
     - PUT /api/v4/clockfaces/{id}
     - parameter id: (path) Clock face UUID 
     - parameter updateClockFaceRequest: (body) Update request 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ClockFace> 
     */
    open class func clockFacesUpdateWithRequestBuilder(id: String, updateClockFaceRequest: UpdateClockFaceRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<ClockFace> {
        var localVariablePath = "/api/v4/clockfaces/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateClockFaceRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ClockFace>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
