//
// V4ServicesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class V4ServicesAPI {

    /**
     Delete all data from a specific connector. WARNING: This is a destructive operation that cannot be undone.
     
     - parameter id: (path) Connector ID (e.g., \&quot;dexcom\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DataSourceDeleteResult
     */
    open class func servicesDeleteConnectorData(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DataSourceDeleteResult {
        return try await servicesDeleteConnectorDataWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete all data from a specific connector. WARNING: This is a destructive operation that cannot be undone.
     - DELETE /api/v4/services/connectors/{id}/data
     - parameter id: (path) Connector ID (e.g., \&quot;dexcom\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DataSourceDeleteResult> 
     */
    open class func servicesDeleteConnectorDataWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<DataSourceDeleteResult> {
        var localVariablePath = "/api/v4/services/connectors/{id}/data"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DataSourceDeleteResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delete all data from a specific data source. WARNING: This is a destructive operation that cannot be undone.
     
     - parameter id: (path) Data source ID or device ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DataSourceDeleteResult
     */
    open class func servicesDeleteDataSourceData(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DataSourceDeleteResult {
        return try await servicesDeleteDataSourceDataWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete all data from a specific data source. WARNING: This is a destructive operation that cannot be undone.
     - DELETE /api/v4/services/data-sources/{id}
     - parameter id: (path) Data source ID or device ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DataSourceDeleteResult> 
     */
    open class func servicesDeleteDataSourceDataWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<DataSourceDeleteResult> {
        var localVariablePath = "/api/v4/services/data-sources/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DataSourceDeleteResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delete all demo data. This operation is safe as demo data can be easily regenerated.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DataSourceDeleteResult
     */
    open class func servicesDeleteDemoData(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DataSourceDeleteResult {
        return try await servicesDeleteDemoDataWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete all demo data. This operation is safe as demo data can be easily regenerated.
     - DELETE /api/v4/services/data-sources/demo
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DataSourceDeleteResult> 
     */
    open class func servicesDeleteDemoDataWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<DataSourceDeleteResult> {
        let localVariablePath = "/api/v4/services/data-sources/demo"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DataSourceDeleteResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get all active data sources that have been sending data to this Nocturne instance. This includes CGM apps, AID systems, and any other uploaders.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [DataSourceInfo]
     */
    open class func servicesGetActiveDataSources(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [DataSourceInfo] {
        return try await servicesGetActiveDataSourcesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all active data sources that have been sending data to this Nocturne instance. This includes CGM apps, AID systems, and any other uploaders.
     - GET /api/v4/services/data-sources
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[DataSourceInfo]> 
     */
    open class func servicesGetActiveDataSourcesWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[DataSourceInfo]> {
        let localVariablePath = "/api/v4/services/data-sources"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[DataSourceInfo]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get API endpoint information for configuring external apps. This provides all the information needed to configure xDrip+, Loop, AAPS, etc.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApiEndpointInfo
     */
    open class func servicesGetApiInfo(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ApiEndpointInfo {
        return try await servicesGetApiInfoWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get API endpoint information for configuring external apps. This provides all the information needed to configure xDrip+, Loop, AAPS, etc.
     - GET /api/v4/services/api-info
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApiEndpointInfo> 
     */
    open class func servicesGetApiInfoWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<ApiEndpointInfo> {
        let localVariablePath = "/api/v4/services/api-info"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiEndpointInfo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get available connectors that can be configured to pull data into Nocturne.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [AvailableConnector]
     */
    open class func servicesGetAvailableConnectors(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [AvailableConnector] {
        return try await servicesGetAvailableConnectorsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get available connectors that can be configured to pull data into Nocturne.
     - GET /api/v4/services/connectors
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[AvailableConnector]> 
     */
    open class func servicesGetAvailableConnectorsWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[AvailableConnector]> {
        let localVariablePath = "/api/v4/services/connectors"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AvailableConnector]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get capabilities for a specific connector.
     
     - parameter id: (path) The connector ID (e.g., \&quot;dexcom\&quot;, \&quot;libre\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ConnectorCapabilities
     */
    open class func servicesGetConnectorCapabilities(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ConnectorCapabilities {
        return try await servicesGetConnectorCapabilitiesWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get capabilities for a specific connector.
     - GET /api/v4/services/connectors/{id}/capabilities
     - parameter id: (path) The connector ID (e.g., \&quot;dexcom\&quot;, \&quot;libre\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ConnectorCapabilities> 
     */
    open class func servicesGetConnectorCapabilitiesWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<ConnectorCapabilities> {
        var localVariablePath = "/api/v4/services/connectors/{id}/capabilities"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ConnectorCapabilities>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get a summary of data counts for a specific connector. Returns the number of entries, treatments, and device statuses synced by this connector.
     
     - parameter id: (path) Connector ID (e.g., \&quot;dexcom\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ConnectorDataSummary
     */
    open class func servicesGetConnectorDataSummary(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ConnectorDataSummary {
        return try await servicesGetConnectorDataSummaryWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a summary of data counts for a specific connector. Returns the number of entries, treatments, and device statuses synced by this connector.
     - GET /api/v4/services/connectors/{id}/data-summary
     - parameter id: (path) Connector ID (e.g., \&quot;dexcom\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ConnectorDataSummary> 
     */
    open class func servicesGetConnectorDataSummaryWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<ConnectorDataSummary> {
        var localVariablePath = "/api/v4/services/connectors/{id}/data-summary"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ConnectorDataSummary>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get sync status for a specific connector, including latest timestamps and connector state. Used by connectors on startup to determine where to resume syncing from.
     
     - parameter id: (path) The connector ID (e.g., \&quot;dexcom\&quot;, \&quot;libre\&quot;, \&quot;glooko\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ConnectorSyncStatus
     */
    open class func servicesGetConnectorSyncStatus(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ConnectorSyncStatus {
        return try await servicesGetConnectorSyncStatusWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get sync status for a specific connector, including latest timestamps and connector state. Used by connectors on startup to determine where to resume syncing from.
     - GET /api/v4/services/connectors/{id}/sync-status
     - parameter id: (path) The connector ID (e.g., \&quot;dexcom\&quot;, \&quot;libre\&quot;, \&quot;glooko\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ConnectorSyncStatus> 
     */
    open class func servicesGetConnectorSyncStatusWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<ConnectorSyncStatus> {
        var localVariablePath = "/api/v4/services/connectors/{id}/sync-status"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ConnectorSyncStatus>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get detailed information about a specific data source.
     
     - parameter id: (path) Data source ID or device ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DataSourceInfo
     */
    open class func servicesGetDataSource(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DataSourceInfo {
        return try await servicesGetDataSourceWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get detailed information about a specific data source.
     - GET /api/v4/services/data-sources/{id}
     - parameter id: (path) Data source ID or device ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DataSourceInfo> 
     */
    open class func servicesGetDataSourceWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<DataSourceInfo> {
        var localVariablePath = "/api/v4/services/data-sources/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DataSourceInfo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get a complete overview of services, data sources, and available integrations.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ServicesOverview
     */
    open class func servicesGetServicesOverview(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ServicesOverview {
        return try await servicesGetServicesOverviewWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a complete overview of services, data sources, and available integrations.
     - GET /api/v4/services
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ServicesOverview> 
     */
    open class func servicesGetServicesOverviewWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<ServicesOverview> {
        let localVariablePath = "/api/v4/services"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServicesOverview>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get uploader apps that can push data to Nocturne with setup instructions.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [UploaderApp]
     */
    open class func servicesGetUploaderApps(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [UploaderApp] {
        return try await servicesGetUploaderAppsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get uploader apps that can push data to Nocturne with setup instructions.
     - GET /api/v4/services/uploaders
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[UploaderApp]> 
     */
    open class func servicesGetUploaderAppsWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[UploaderApp]> {
        let localVariablePath = "/api/v4/services/uploaders"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[UploaderApp]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get setup instructions for a specific uploader app.
     
     - parameter appId: (path) The uploader app ID (e.g., \&quot;xdrip\&quot;, \&quot;loop\&quot;, \&quot;aaps\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: UploaderSetupResponse
     */
    open class func servicesGetUploaderSetup(appId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> UploaderSetupResponse {
        return try await servicesGetUploaderSetupWithRequestBuilder(appId: appId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get setup instructions for a specific uploader app.
     - GET /api/v4/services/uploaders/{appId}/setup
     - parameter appId: (path) The uploader app ID (e.g., \&quot;xdrip\&quot;, \&quot;loop\&quot;, \&quot;aaps\&quot;) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UploaderSetupResponse> 
     */
    open class func servicesGetUploaderSetupWithRequestBuilder(appId: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<UploaderSetupResponse> {
        var localVariablePath = "/api/v4/services/uploaders/{appId}/setup"
        let appIdPreEscape = "\(APIHelper.mapValueToPathItem(appId))"
        let appIdPostEscape = appIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{appId}", with: appIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UploaderSetupResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Trigger a manual sync for a specific connector.
     
     - parameter id: (path) Connector ID (e.g., \&quot;dexcom\&quot;, \&quot;tidepool\&quot;) 
     - parameter syncRequest: (body) Sync request parameters (date range and data types) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SyncResult
     */
    open class func servicesTriggerConnectorSync(id: String, syncRequest: SyncRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SyncResult {
        return try await servicesTriggerConnectorSyncWithRequestBuilder(id: id, syncRequest: syncRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Trigger a manual sync for a specific connector.
     - POST /api/v4/services/connectors/{id}/sync
     - parameter id: (path) Connector ID (e.g., \&quot;dexcom\&quot;, \&quot;tidepool\&quot;) 
     - parameter syncRequest: (body) Sync request parameters (date range and data types) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SyncResult> 
     */
    open class func servicesTriggerConnectorSyncWithRequestBuilder(id: String, syncRequest: SyncRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<SyncResult> {
        var localVariablePath = "/api/v4/services/connectors/{id}/sync"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: syncRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SyncResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
