//
// V4SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class V4SystemAPI {

    /**
     Accept a heartbeat from an external service (e.g. bot adapter). Returns 200 OK. Actual health tracking will be added later.
     
     - parameter heartbeatRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func systemHeartbeat(heartbeatRequest: HeartbeatRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await systemHeartbeatWithRequestBuilder(heartbeatRequest: heartbeatRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Accept a heartbeat from an external service (e.g. bot adapter). Returns 200 OK. Actual health tracking will be added later.
     - POST /api/v4/system/heartbeat
     - parameter heartbeatRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func systemHeartbeatWithRequestBuilder(heartbeatRequest: HeartbeatRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v4/system/heartbeat"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: heartbeatRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
