//
// V4TreatmentsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class V4TreatmentsAPI {

    /**
     Create a treatment with tracker integration. If the treatment's event type matches a tracker's trigger event types, the tracker instance will be automatically started/restarted.
     
     - parameter treatment: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Treatment
     */
    open class func treatmentsCreateTreatment(treatment: Treatment, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Treatment {
        return try await treatmentsCreateTreatmentWithRequestBuilder(treatment: treatment, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a treatment with tracker integration. If the treatment's event type matches a tracker's trigger event types, the tracker instance will be automatically started/restarted.
     - POST /api/v4/treatments
     - parameter treatment: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Treatment> 
     */
    open class func treatmentsCreateTreatmentWithRequestBuilder(treatment: Treatment, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Treatment> {
        let localVariablePath = "/api/v4/treatments"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: treatment, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Treatment>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Create multiple treatments with tracker integration.
     
     - parameter treatment: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [Treatment]
     */
    open class func treatmentsCreateTreatments(treatment: [Treatment], apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [Treatment] {
        return try await treatmentsCreateTreatmentsWithRequestBuilder(treatment: treatment, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create multiple treatments with tracker integration.
     - POST /api/v4/treatments/bulk
     - parameter treatment: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[Treatment]> 
     */
    open class func treatmentsCreateTreatmentsWithRequestBuilder(treatment: [Treatment], apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[Treatment]> {
        let localVariablePath = "/api/v4/treatments/bulk"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: treatment, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Treatment]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a treatment by ID
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func treatmentsDeleteTreatment(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await treatmentsDeleteTreatmentWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a treatment by ID
     - DELETE /api/v4/treatments/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func treatmentsDeleteTreatmentWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v4/treatments/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get a specific treatment by ID
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Treatment
     */
    open class func treatmentsGetTreatment(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Treatment {
        return try await treatmentsGetTreatmentWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a specific treatment by ID
     - GET /api/v4/treatments/{id}
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Treatment> 
     */
    open class func treatmentsGetTreatmentWithRequestBuilder(id: String, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Treatment> {
        var localVariablePath = "/api/v4/treatments/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Treatment>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get treatments with optional filtering and pagination. Unlike V1-V3 endpoints, this does NOT include StateSpan-derived basal data. For basal delivery, query /api/v4/state-spans?category=BasalDelivery instead.
     
     - parameter eventType: (query) Optional filter by event type (optional)
     - parameter count: (query) Maximum number of treatments to return (default: 100) (optional, default to 100)
     - parameter skip: (query) Number of treatments to skip for pagination (default: 0) (optional, default to 0)
     - parameter find: (query) Optional MongoDB-style query filter for advanced filtering (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [Treatment]
     */
    open class func treatmentsGetTreatments(eventType: String? = nil, count: Int? = nil, skip: Int? = nil, find: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [Treatment] {
        return try await treatmentsGetTreatmentsWithRequestBuilder(eventType: eventType, count: count, skip: skip, find: find, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get treatments with optional filtering and pagination. Unlike V1-V3 endpoints, this does NOT include StateSpan-derived basal data. For basal delivery, query /api/v4/state-spans?category=BasalDelivery instead.
     - GET /api/v4/treatments
     - parameter eventType: (query) Optional filter by event type (optional)
     - parameter count: (query) Maximum number of treatments to return (default: 100) (optional, default to 100)
     - parameter skip: (query) Number of treatments to skip for pagination (default: 0) (optional, default to 0)
     - parameter find: (query) Optional MongoDB-style query filter for advanced filtering (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[Treatment]> 
     */
    open class func treatmentsGetTreatmentsWithRequestBuilder(eventType: String? = nil, count: Int? = nil, skip: Int? = nil, find: String? = nil, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<[Treatment]> {
        let localVariablePath = "/api/v4/treatments"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "eventType": (wrappedValue: eventType?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "count": (wrappedValue: count?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "skip": (wrappedValue: skip?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "find": (wrappedValue: find?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Treatment]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing treatment by ID
     
     - parameter id: (path)  
     - parameter treatment: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Treatment
     */
    open class func treatmentsUpdateTreatment(id: String, treatment: Treatment, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Treatment {
        return try await treatmentsUpdateTreatmentWithRequestBuilder(id: id, treatment: treatment, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing treatment by ID
     - PUT /api/v4/treatments/{id}
     - parameter id: (path)  
     - parameter treatment: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Treatment> 
     */
    open class func treatmentsUpdateTreatmentWithRequestBuilder(id: String, treatment: Treatment, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<Treatment> {
        var localVariablePath = "/api/v4/treatments/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: treatment, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Treatment>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
