//
// WebhookSettingsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class WebhookSettingsAPI {

    /**
     Gets the webhook notification settings for the current tenant.
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WebhookNotificationSettings
     */
    open class func webhookSettingsGetWebhookSettings(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> WebhookNotificationSettings {
        return try await webhookSettingsGetWebhookSettingsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Gets the webhook notification settings for the current tenant.
     - GET /api/v4/ui-settings/notifications/webhooks
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WebhookNotificationSettings> 
     */
    open class func webhookSettingsGetWebhookSettingsWithRequestBuilder(apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<WebhookNotificationSettings> {
        let localVariablePath = "/api/v4/ui-settings/notifications/webhooks"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WebhookNotificationSettings>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Saves webhook notification settings.
     
     - parameter webhookNotificationSettings: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WebhookNotificationSettings
     */
    open class func webhookSettingsSaveWebhookSettings(webhookNotificationSettings: WebhookNotificationSettings, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> WebhookNotificationSettings {
        return try await webhookSettingsSaveWebhookSettingsWithRequestBuilder(webhookNotificationSettings: webhookNotificationSettings, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Saves webhook notification settings.
     - PUT /api/v4/ui-settings/notifications/webhooks
     - parameter webhookNotificationSettings: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WebhookNotificationSettings> 
     */
    open class func webhookSettingsSaveWebhookSettingsWithRequestBuilder(webhookNotificationSettings: WebhookNotificationSettings, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<WebhookNotificationSettings> {
        let localVariablePath = "/api/v4/ui-settings/notifications/webhooks"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: webhookNotificationSettings, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WebhookNotificationSettings>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Tests webhook settings by sending test payloads to configured URLs.
     
     - parameter webhookTestRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WebhookTestResult
     */
    open class func webhookSettingsTestWebhookSettings(webhookTestRequest: WebhookTestRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) async throws(ErrorResponse) -> WebhookTestResult {
        return try await webhookSettingsTestWebhookSettingsWithRequestBuilder(webhookTestRequest: webhookTestRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Tests webhook settings by sending test payloads to configured URLs.
     - POST /api/v4/ui-settings/notifications/webhooks/test
     - parameter webhookTestRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WebhookTestResult> 
     */
    open class func webhookSettingsTestWebhookSettingsWithRequestBuilder(webhookTestRequest: WebhookTestRequest, apiConfiguration: NocturneSDKAPIConfiguration = NocturneSDKAPIConfiguration.shared) -> RequestBuilder<WebhookTestResult> {
        let localVariablePath = "/api/v4/ui-settings/notifications/webhooks/test"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: webhookTestRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WebhookTestResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
