//
// AcceptSuggestionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AcceptSuggestionRequest: Sendable, Codable, Hashable {

    public var startMills: Int64?
    public var endMills: Int64?

    public init(startMills: Int64? = nil, endMills: Int64? = nil) {
        self.startMills = startMills
        self.endMills = endMills
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startMills
        case endMills
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startMills, forKey: .startMills)
        try container.encodeIfPresent(endMills, forKey: .endMills)
    }
}

