//
// Activity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Activity: Sendable, Codable, Hashable {

    public var id: String?
    public var createdAt: String?
    public var mills: Int64?
    public var utcOffset: Int?
    public var timestamp: Int64?
    public var type: String?
    public var description: String?
    public var duration: Double?
    public var intensity: String?
    public var notes: String?
    public var enteredBy: String?
    public var dateString: String?
    public var distance: Double?
    public var distanceUnits: String?
    public var energy: Double?
    public var energyUnits: String?
    public var name: String?

    public init(id: String? = nil, createdAt: String? = nil, mills: Int64? = nil, utcOffset: Int? = nil, timestamp: Int64? = nil, type: String? = nil, description: String? = nil, duration: Double? = nil, intensity: String? = nil, notes: String? = nil, enteredBy: String? = nil, dateString: String? = nil, distance: Double? = nil, distanceUnits: String? = nil, energy: Double? = nil, energyUnits: String? = nil, name: String? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.mills = mills
        self.utcOffset = utcOffset
        self.timestamp = timestamp
        self.type = type
        self.description = description
        self.duration = duration
        self.intensity = intensity
        self.notes = notes
        self.enteredBy = enteredBy
        self.dateString = dateString
        self.distance = distance
        self.distanceUnits = distanceUnits
        self.energy = energy
        self.energyUnits = energyUnits
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case mills
        case utcOffset
        case timestamp
        case type
        case description
        case duration
        case intensity
        case notes
        case enteredBy
        case dateString
        case distance
        case distanceUnits
        case energy
        case energyUnits
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(mills, forKey: .mills)
        try container.encodeIfPresent(utcOffset, forKey: .utcOffset)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(intensity, forKey: .intensity)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(enteredBy, forKey: .enteredBy)
        try container.encodeIfPresent(dateString, forKey: .dateString)
        try container.encodeIfPresent(distance, forKey: .distance)
        try container.encodeIfPresent(distanceUnits, forKey: .distanceUnits)
        try container.encodeIfPresent(energy, forKey: .energy)
        try container.encodeIfPresent(energyUnits, forKey: .energyUnits)
        try container.encodeIfPresent(name, forKey: .name)
    }
}


extension Activity: Identifiable {}
