//
// ActogramSleepSpan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ActogramSleepSpan: Sendable, Codable, Hashable {

    public var startMills: Int64?
    public var endMills: Int64?
    public var state: String?

    public init(startMills: Int64? = nil, endMills: Int64? = nil, state: String? = nil) {
        self.startMills = startMills
        self.endMills = endMills
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startMills
        case endMills
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startMills, forKey: .startMills)
        try container.encodeIfPresent(endMills, forKey: .endMills)
        try container.encodeIfPresent(state, forKey: .state)
    }
}

