//
// AidTimeSegment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AidTimeSegment: Sendable, Codable, Hashable {

    public var algorithm: AidAlgorithm?
    public var startDate: Date?
    public var endDate: Date?
    public var durationHours: Double?
    public var metrics: AidSegmentMetrics?

    public init(algorithm: AidAlgorithm? = nil, startDate: Date? = nil, endDate: Date? = nil, durationHours: Double? = nil, metrics: AidSegmentMetrics? = nil) {
        self.algorithm = algorithm
        self.startDate = startDate
        self.endDate = endDate
        self.durationHours = durationHours
        self.metrics = metrics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case algorithm
        case startDate
        case endDate
        case durationHours
        case metrics
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(algorithm, forKey: .algorithm)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(durationHours, forKey: .durationHours)
        try container.encodeIfPresent(metrics, forKey: .metrics)
    }
}

