//
// AlarmVibrationSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlarmVibrationSettings: Sendable, Codable, Hashable {

    public var enabled: Bool?
    public var pattern: String?
    public var customPattern: [Int]?

    public init(enabled: Bool? = nil, pattern: String? = nil, customPattern: [Int]? = nil) {
        self.enabled = enabled
        self.pattern = pattern
        self.customPattern = customPattern
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case pattern
        case customPattern
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(pattern, forKey: .pattern)
        try container.encodeIfPresent(customPattern, forKey: .customPattern)
    }
}

