//
// AlarmSnoozeSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlarmSnoozeSettings: Sendable, Codable, Hashable {

    public var defaultMinutes: Int?
    public var options: [Int]?
    public var maxMinutes: Int?
    public var maxSnoozeCount: Int?

    public init(defaultMinutes: Int? = nil, options: [Int]? = nil, maxMinutes: Int? = nil, maxSnoozeCount: Int? = nil) {
        self.defaultMinutes = defaultMinutes
        self.options = options
        self.maxMinutes = maxMinutes
        self.maxSnoozeCount = maxSnoozeCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case defaultMinutes
        case options
        case maxMinutes
        case maxSnoozeCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(defaultMinutes, forKey: .defaultMinutes)
        try container.encodeIfPresent(options, forKey: .options)
        try container.encodeIfPresent(maxMinutes, forKey: .maxMinutes)
        try container.encodeIfPresent(maxSnoozeCount, forKey: .maxSnoozeCount)
    }
}

