//
// AlarmTriggerType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum AlarmTriggerType: String, Sendable, Codable, CaseIterable {
    case high = "High"
    case low = "Low"
    case urgentHigh = "UrgentHigh"
    case urgentLow = "UrgentLow"
    case risingFast = "RisingFast"
    case fallingFast = "FallingFast"
    case staleData = "StaleData"
    case forecastLow = "ForecastLow"
    case custom = "Custom"
}
