//
// AlertRuleSeverity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum AlertRuleSeverity: String, Sendable, Codable, CaseIterable {
    case normal = "normal"
    case critical = "critical"
}
