//
// AlertRuleChannelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlertRuleChannelResponse: Sendable, Codable, Hashable {

    public var id: String?
    public var channelType: ChannelType?
    public var destination: String?
    public var destinationLabel: String?
    public var sortOrder: Int?
    /** Channel-specific config (e.g. device_action capabilities). Null when unset. */
    public var metadata: JSONValue?

    public init(id: String? = nil, channelType: ChannelType? = nil, destination: String? = nil, destinationLabel: String? = nil, sortOrder: Int? = nil, metadata: JSONValue? = nil) {
        self.id = id
        self.channelType = channelType
        self.destination = destination
        self.destinationLabel = destinationLabel
        self.sortOrder = sortOrder
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case channelType
        case destination
        case destinationLabel
        case sortOrder
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(channelType, forKey: .channelType)
        try container.encodeIfPresent(destination, forKey: .destination)
        try container.encodeIfPresent(destinationLabel, forKey: .destinationLabel)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}


extension AlertRuleChannelResponse: Identifiable {}
