//
// AlertStepChannelResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlertStepChannelResponse: Sendable, Codable, Hashable {

    public var id: String?
    public var channelType: ChannelType?
    public var destination: String?
    public var destinationLabel: String?

    public init(id: String? = nil, channelType: ChannelType? = nil, destination: String? = nil, destinationLabel: String? = nil) {
        self.id = id
        self.channelType = channelType
        self.destination = destination
        self.destinationLabel = destinationLabel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case channelType
        case destination
        case destinationLabel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(channelType, forKey: .channelType)
        try container.encodeIfPresent(destination, forKey: .destination)
        try container.encodeIfPresent(destinationLabel, forKey: .destinationLabel)
    }
}


extension AlertStepChannelResponse: Identifiable {}
