//
// AlertReplayResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlertReplayResult: Sendable, Codable, Hashable {

    public var windowStart: Date?
    public var windowEnd: Date?
    public var events: [AlertReplayEvent]?
    public var leafTransitionsByRule: [String: [LeafTransitionLog]]?
    public var factTimelines: [String: [FactSnapshotPoint]]?

    public init(windowStart: Date? = nil, windowEnd: Date? = nil, events: [AlertReplayEvent]? = nil, leafTransitionsByRule: [String: [LeafTransitionLog]]? = nil, factTimelines: [String: [FactSnapshotPoint]]? = nil) {
        self.windowStart = windowStart
        self.windowEnd = windowEnd
        self.events = events
        self.leafTransitionsByRule = leafTransitionsByRule
        self.factTimelines = factTimelines
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case windowStart
        case windowEnd
        case events
        case leafTransitionsByRule
        case factTimelines
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(windowStart, forKey: .windowStart)
        try container.encodeIfPresent(windowEnd, forKey: .windowEnd)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encodeIfPresent(leafTransitionsByRule, forKey: .leafTransitionsByRule)
        try container.encodeIfPresent(factTimelines, forKey: .factTimelines)
    }
}

