//
// AnalysisListItemDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Analysis list item DTO */
public struct AnalysisListItemDto: Sendable, Codable, Hashable {

    public var id: String?
    public var correlationId: String?
    public var analysisTimestamp: Date?
    public var requestMethod: String?
    public var requestPath: String?
    public var overallMatch: ResponseMatchType?
    public var statusCodeMatch: Bool?
    public var bodyMatch: Bool?
    public var nightscoutStatusCode: Int?
    public var nocturneStatusCode: Int?
    public var nightscoutResponseTimeMs: Int64?
    public var nocturneResponseTimeMs: Int64?
    public var totalProcessingTimeMs: Int64?
    public var summary: String?
    public var criticalDiscrepancyCount: Int?
    public var majorDiscrepancyCount: Int?
    public var minorDiscrepancyCount: Int?
    public var nightscoutMissing: Bool?
    public var nocturneMissing: Bool?

    public init(id: String? = nil, correlationId: String? = nil, analysisTimestamp: Date? = nil, requestMethod: String? = nil, requestPath: String? = nil, overallMatch: ResponseMatchType? = nil, statusCodeMatch: Bool? = nil, bodyMatch: Bool? = nil, nightscoutStatusCode: Int? = nil, nocturneStatusCode: Int? = nil, nightscoutResponseTimeMs: Int64? = nil, nocturneResponseTimeMs: Int64? = nil, totalProcessingTimeMs: Int64? = nil, summary: String? = nil, criticalDiscrepancyCount: Int? = nil, majorDiscrepancyCount: Int? = nil, minorDiscrepancyCount: Int? = nil, nightscoutMissing: Bool? = nil, nocturneMissing: Bool? = nil) {
        self.id = id
        self.correlationId = correlationId
        self.analysisTimestamp = analysisTimestamp
        self.requestMethod = requestMethod
        self.requestPath = requestPath
        self.overallMatch = overallMatch
        self.statusCodeMatch = statusCodeMatch
        self.bodyMatch = bodyMatch
        self.nightscoutStatusCode = nightscoutStatusCode
        self.nocturneStatusCode = nocturneStatusCode
        self.nightscoutResponseTimeMs = nightscoutResponseTimeMs
        self.nocturneResponseTimeMs = nocturneResponseTimeMs
        self.totalProcessingTimeMs = totalProcessingTimeMs
        self.summary = summary
        self.criticalDiscrepancyCount = criticalDiscrepancyCount
        self.majorDiscrepancyCount = majorDiscrepancyCount
        self.minorDiscrepancyCount = minorDiscrepancyCount
        self.nightscoutMissing = nightscoutMissing
        self.nocturneMissing = nocturneMissing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case correlationId
        case analysisTimestamp
        case requestMethod
        case requestPath
        case overallMatch
        case statusCodeMatch
        case bodyMatch
        case nightscoutStatusCode
        case nocturneStatusCode
        case nightscoutResponseTimeMs
        case nocturneResponseTimeMs
        case totalProcessingTimeMs
        case summary
        case criticalDiscrepancyCount
        case majorDiscrepancyCount
        case minorDiscrepancyCount
        case nightscoutMissing
        case nocturneMissing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(correlationId, forKey: .correlationId)
        try container.encodeIfPresent(analysisTimestamp, forKey: .analysisTimestamp)
        try container.encodeIfPresent(requestMethod, forKey: .requestMethod)
        try container.encodeIfPresent(requestPath, forKey: .requestPath)
        try container.encodeIfPresent(overallMatch, forKey: .overallMatch)
        try container.encodeIfPresent(statusCodeMatch, forKey: .statusCodeMatch)
        try container.encodeIfPresent(bodyMatch, forKey: .bodyMatch)
        try container.encodeIfPresent(nightscoutStatusCode, forKey: .nightscoutStatusCode)
        try container.encodeIfPresent(nocturneStatusCode, forKey: .nocturneStatusCode)
        try container.encodeIfPresent(nightscoutResponseTimeMs, forKey: .nightscoutResponseTimeMs)
        try container.encodeIfPresent(nocturneResponseTimeMs, forKey: .nocturneResponseTimeMs)
        try container.encodeIfPresent(totalProcessingTimeMs, forKey: .totalProcessingTimeMs)
        try container.encodeIfPresent(summary, forKey: .summary)
        try container.encodeIfPresent(criticalDiscrepancyCount, forKey: .criticalDiscrepancyCount)
        try container.encodeIfPresent(majorDiscrepancyCount, forKey: .majorDiscrepancyCount)
        try container.encodeIfPresent(minorDiscrepancyCount, forKey: .minorDiscrepancyCount)
        try container.encodeIfPresent(nightscoutMissing, forKey: .nightscoutMissing)
        try container.encodeIfPresent(nocturneMissing, forKey: .nocturneMissing)
    }
}


extension AnalysisListItemDto: Identifiable {}
