//
// ApiEndpointInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiEndpointInfo: Sendable, Codable, Hashable {

    public var baseUrl: String?
    public var requiresApiSecret: Bool?
    public var isAuthenticated: Bool?
    public var entriesEndpoint: String?
    public var treatmentsEndpoint: String?
    public var deviceStatusEndpoint: String?

    public init(baseUrl: String? = nil, requiresApiSecret: Bool? = nil, isAuthenticated: Bool? = nil, entriesEndpoint: String? = nil, treatmentsEndpoint: String? = nil, deviceStatusEndpoint: String? = nil) {
        self.baseUrl = baseUrl
        self.requiresApiSecret = requiresApiSecret
        self.isAuthenticated = isAuthenticated
        self.entriesEndpoint = entriesEndpoint
        self.treatmentsEndpoint = treatmentsEndpoint
        self.deviceStatusEndpoint = deviceStatusEndpoint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case baseUrl
        case requiresApiSecret
        case isAuthenticated
        case entriesEndpoint
        case treatmentsEndpoint
        case deviceStatusEndpoint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(baseUrl, forKey: .baseUrl)
        try container.encodeIfPresent(requiresApiSecret, forKey: .requiresApiSecret)
        try container.encodeIfPresent(isAuthenticated, forKey: .isAuthenticated)
        try container.encodeIfPresent(entriesEndpoint, forKey: .entriesEndpoint)
        try container.encodeIfPresent(treatmentsEndpoint, forKey: .treatmentsEndpoint)
        try container.encodeIfPresent(deviceStatusEndpoint, forKey: .deviceStatusEndpoint)
    }
}

