//
// AvatarUploadResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AvatarUploadResponse: Sendable, Codable, Hashable {

    public var avatarUrl: String?

    public init(avatarUrl: String? = nil) {
        self.avatarUrl = avatarUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avatarUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(avatarUrl, forKey: .avatarUrl)
    }
}

