//
// AveragedStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AveragedStats: Sendable, Codable, Hashable {

    public var count: Int?
    public var mean: Double?
    public var median: Double?
    public var min: Double?
    public var max: Double?
    public var standardDeviation: Double?
    public var percentiles: GlucosePercentiles?
    public var hour: Int?
    public var timeInRange: ExtendedTimeInRangePercentages?

    public init(count: Int? = nil, mean: Double? = nil, median: Double? = nil, min: Double? = nil, max: Double? = nil, standardDeviation: Double? = nil, percentiles: GlucosePercentiles? = nil, hour: Int? = nil, timeInRange: ExtendedTimeInRangePercentages? = nil) {
        self.count = count
        self.mean = mean
        self.median = median
        self.min = min
        self.max = max
        self.standardDeviation = standardDeviation
        self.percentiles = percentiles
        self.hour = hour
        self.timeInRange = timeInRange
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case mean
        case median
        case min
        case max
        case standardDeviation
        case percentiles
        case hour
        case timeInRange
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(mean, forKey: .mean)
        try container.encodeIfPresent(median, forKey: .median)
        try container.encodeIfPresent(min, forKey: .min)
        try container.encodeIfPresent(max, forKey: .max)
        try container.encodeIfPresent(standardDeviation, forKey: .standardDeviation)
        try container.encodeIfPresent(percentiles, forKey: .percentiles)
        try container.encodeIfPresent(hour, forKey: .hour)
        try container.encodeIfPresent(timeInRange, forKey: .timeInRange)
    }
}

