//
// BackfillResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Result of a V4 backfill operation */
public struct BackfillResult: Sendable, Codable, Hashable {

    /** Number of entries successfully decomposed into v4 records */
    public var entriesProcessed: Int64?
    /** Number of entries that failed decomposition */
    public var entriesFailed: Int64?
    /** Number of treatments successfully decomposed into v4 records */
    public var treatmentsProcessed: Int64?
    /** Number of treatments that failed decomposition */
    public var treatmentsFailed: Int64?
    /** Number of treatments skipped (temp basals, profile switches) */
    public var treatmentsSkipped: Int64?

    public init(entriesProcessed: Int64? = nil, entriesFailed: Int64? = nil, treatmentsProcessed: Int64? = nil, treatmentsFailed: Int64? = nil, treatmentsSkipped: Int64? = nil) {
        self.entriesProcessed = entriesProcessed
        self.entriesFailed = entriesFailed
        self.treatmentsProcessed = treatmentsProcessed
        self.treatmentsFailed = treatmentsFailed
        self.treatmentsSkipped = treatmentsSkipped
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entriesProcessed
        case entriesFailed
        case treatmentsProcessed
        case treatmentsFailed
        case treatmentsSkipped
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entriesProcessed, forKey: .entriesProcessed)
        try container.encodeIfPresent(entriesFailed, forKey: .entriesFailed)
        try container.encodeIfPresent(treatmentsProcessed, forKey: .treatmentsProcessed)
        try container.encodeIfPresent(treatmentsFailed, forKey: .treatmentsFailed)
        try container.encodeIfPresent(treatmentsSkipped, forKey: .treatmentsSkipped)
    }
}

