//
// BasalDataPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Data point for basal timeline */
public struct BasalDataPoint: Sendable, Codable, Hashable {

    public var time: Int64?
    public var hour: Int?
    public var minute: Int?
    public var timeLabel: String?
    public var rate: Double?
    public var isTemp: Bool?

    public init(time: Int64? = nil, hour: Int? = nil, minute: Int? = nil, timeLabel: String? = nil, rate: Double? = nil, isTemp: Bool? = nil) {
        self.time = time
        self.hour = hour
        self.minute = minute
        self.timeLabel = timeLabel
        self.rate = rate
        self.isTemp = isTemp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case hour
        case minute
        case timeLabel
        case rate
        case isTemp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(hour, forKey: .hour)
        try container.encodeIfPresent(minute, forKey: .minute)
        try container.encodeIfPresent(timeLabel, forKey: .timeLabel)
        try container.encodeIfPresent(rate, forKey: .rate)
        try container.encodeIfPresent(isTemp, forKey: .isTemp)
    }
}

