//
// BasalDeliveryOrigin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum BasalDeliveryOrigin: String, Sendable, Codable, CaseIterable {
    case algorithm = "Algorithm"
    case scheduled = "Scheduled"
    case manual = "Manual"
    case suspended = "Suspended"
    case inferred = "Inferred"
}
