//
// BasalInjectionMarkerDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BasalInjectionMarkerDto: Sendable, Codable, Hashable {

    public var id: String?
    public var time: Int64?
    public var units: Double?
    public var insulinName: String?

    public init(id: String? = nil, time: Int64? = nil, units: Double? = nil, insulinName: String? = nil) {
        self.id = id
        self.time = time
        self.units = units
        self.insulinName = insulinName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case time
        case units
        case insulinName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(units, forKey: .units)
        try container.encodeIfPresent(insulinName, forKey: .insulinName)
    }
}


extension BasalInjectionMarkerDto: Identifiable {}
