//
// BasalPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BasalPoint: Sendable, Codable, Hashable {

    public var timestamp: Int64?
    public var rate: Double?
    public var scheduledRate: Double?
    public var origin: BasalDeliveryOrigin?
    public var fillColor: ChartColor?
    public var strokeColor: ChartColor?

    public init(timestamp: Int64? = nil, rate: Double? = nil, scheduledRate: Double? = nil, origin: BasalDeliveryOrigin? = nil, fillColor: ChartColor? = nil, strokeColor: ChartColor? = nil) {
        self.timestamp = timestamp
        self.rate = rate
        self.scheduledRate = scheduledRate
        self.origin = origin
        self.fillColor = fillColor
        self.strokeColor = strokeColor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case rate
        case scheduledRate
        case origin
        case fillColor
        case strokeColor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(rate, forKey: .rate)
        try container.encodeIfPresent(scheduledRate, forKey: .scheduledRate)
        try container.encodeIfPresent(origin, forKey: .origin)
        try container.encodeIfPresent(fillColor, forKey: .fillColor)
        try container.encodeIfPresent(strokeColor, forKey: .strokeColor)
    }
}

