//
// BatteryStatistics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BatteryStatistics: Sendable, Codable, Hashable {

    public var device: String?
    public var displayName: String?
    public var periodStartMills: Int64?
    public var periodEndMills: Int64?
    public var readingCount: Int?
    public var currentLevel: Int?
    public var isCharging: Bool?
    public var lastReadingMills: Int64?
    public var averageLevel: Double?
    public var minLevel: Int?
    public var maxLevel: Int?
    public var chargeCycleCount: Int?
    public var averageChargeDurationMinutes: Double?
    public var averageDischargeDurationMinutes: Double?
    public var averageTimeBetweenChargesHours: Double?
    public var longestDischargeDurationMinutes: Double?
    public var shortestDischargeDurationMinutes: Double?
    public var timeAbove80Percent: Double?
    public var timeBetween30And80Percent: Double?
    public var timeBelow30Percent: Double?
    public var timeBelow20Percent: Double?
    public var warningEventCount: Int?
    public var urgentEventCount: Int?
    public var display: String?
    public var level: Int?
    public var status: String?

    public init(device: String? = nil, displayName: String? = nil, periodStartMills: Int64? = nil, periodEndMills: Int64? = nil, readingCount: Int? = nil, currentLevel: Int? = nil, isCharging: Bool? = nil, lastReadingMills: Int64? = nil, averageLevel: Double? = nil, minLevel: Int? = nil, maxLevel: Int? = nil, chargeCycleCount: Int? = nil, averageChargeDurationMinutes: Double? = nil, averageDischargeDurationMinutes: Double? = nil, averageTimeBetweenChargesHours: Double? = nil, longestDischargeDurationMinutes: Double? = nil, shortestDischargeDurationMinutes: Double? = nil, timeAbove80Percent: Double? = nil, timeBetween30And80Percent: Double? = nil, timeBelow30Percent: Double? = nil, timeBelow20Percent: Double? = nil, warningEventCount: Int? = nil, urgentEventCount: Int? = nil, display: String? = nil, level: Int? = nil, status: String? = nil) {
        self.device = device
        self.displayName = displayName
        self.periodStartMills = periodStartMills
        self.periodEndMills = periodEndMills
        self.readingCount = readingCount
        self.currentLevel = currentLevel
        self.isCharging = isCharging
        self.lastReadingMills = lastReadingMills
        self.averageLevel = averageLevel
        self.minLevel = minLevel
        self.maxLevel = maxLevel
        self.chargeCycleCount = chargeCycleCount
        self.averageChargeDurationMinutes = averageChargeDurationMinutes
        self.averageDischargeDurationMinutes = averageDischargeDurationMinutes
        self.averageTimeBetweenChargesHours = averageTimeBetweenChargesHours
        self.longestDischargeDurationMinutes = longestDischargeDurationMinutes
        self.shortestDischargeDurationMinutes = shortestDischargeDurationMinutes
        self.timeAbove80Percent = timeAbove80Percent
        self.timeBetween30And80Percent = timeBetween30And80Percent
        self.timeBelow30Percent = timeBelow30Percent
        self.timeBelow20Percent = timeBelow20Percent
        self.warningEventCount = warningEventCount
        self.urgentEventCount = urgentEventCount
        self.display = display
        self.level = level
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case device
        case displayName
        case periodStartMills
        case periodEndMills
        case readingCount
        case currentLevel
        case isCharging
        case lastReadingMills
        case averageLevel
        case minLevel
        case maxLevel
        case chargeCycleCount
        case averageChargeDurationMinutes
        case averageDischargeDurationMinutes
        case averageTimeBetweenChargesHours
        case longestDischargeDurationMinutes
        case shortestDischargeDurationMinutes
        case timeAbove80Percent
        case timeBetween30And80Percent
        case timeBelow30Percent
        case timeBelow20Percent
        case warningEventCount
        case urgentEventCount
        case display
        case level
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(periodStartMills, forKey: .periodStartMills)
        try container.encodeIfPresent(periodEndMills, forKey: .periodEndMills)
        try container.encodeIfPresent(readingCount, forKey: .readingCount)
        try container.encodeIfPresent(currentLevel, forKey: .currentLevel)
        try container.encodeIfPresent(isCharging, forKey: .isCharging)
        try container.encodeIfPresent(lastReadingMills, forKey: .lastReadingMills)
        try container.encodeIfPresent(averageLevel, forKey: .averageLevel)
        try container.encodeIfPresent(minLevel, forKey: .minLevel)
        try container.encodeIfPresent(maxLevel, forKey: .maxLevel)
        try container.encodeIfPresent(chargeCycleCount, forKey: .chargeCycleCount)
        try container.encodeIfPresent(averageChargeDurationMinutes, forKey: .averageChargeDurationMinutes)
        try container.encodeIfPresent(averageDischargeDurationMinutes, forKey: .averageDischargeDurationMinutes)
        try container.encodeIfPresent(averageTimeBetweenChargesHours, forKey: .averageTimeBetweenChargesHours)
        try container.encodeIfPresent(longestDischargeDurationMinutes, forKey: .longestDischargeDurationMinutes)
        try container.encodeIfPresent(shortestDischargeDurationMinutes, forKey: .shortestDischargeDurationMinutes)
        try container.encodeIfPresent(timeAbove80Percent, forKey: .timeAbove80Percent)
        try container.encodeIfPresent(timeBetween30And80Percent, forKey: .timeBetween30And80Percent)
        try container.encodeIfPresent(timeBelow30Percent, forKey: .timeBelow30Percent)
        try container.encodeIfPresent(timeBelow20Percent, forKey: .timeBelow20Percent)
        try container.encodeIfPresent(warningEventCount, forKey: .warningEventCount)
        try container.encodeIfPresent(urgentEventCount, forKey: .urgentEventCount)
        try container.encodeIfPresent(display, forKey: .display)
        try container.encodeIfPresent(level, forKey: .level)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

