//
// BatteryDisplaySettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BatteryDisplaySettings: Sendable, Codable, Hashable {

    public var warnThreshold: Int?
    public var urgentThreshold: Int?
    public var enableAlerts: Bool?
    public var recentMinutes: Int?
    public var showVoltage: Bool?
    public var showStatistics: Bool?

    public init(warnThreshold: Int? = nil, urgentThreshold: Int? = nil, enableAlerts: Bool? = nil, recentMinutes: Int? = nil, showVoltage: Bool? = nil, showStatistics: Bool? = nil) {
        self.warnThreshold = warnThreshold
        self.urgentThreshold = urgentThreshold
        self.enableAlerts = enableAlerts
        self.recentMinutes = recentMinutes
        self.showVoltage = showVoltage
        self.showStatistics = showStatistics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case warnThreshold
        case urgentThreshold
        case enableAlerts
        case recentMinutes
        case showVoltage
        case showStatistics
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(warnThreshold, forKey: .warnThreshold)
        try container.encodeIfPresent(urgentThreshold, forKey: .urgentThreshold)
        try container.encodeIfPresent(enableAlerts, forKey: .enableAlerts)
        try container.encodeIfPresent(recentMinutes, forKey: .recentMinutes)
        try container.encodeIfPresent(showVoltage, forKey: .showVoltage)
        try container.encodeIfPresent(showStatistics, forKey: .showStatistics)
    }
}

