//
// BolusCalculation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BolusCalculation: Sendable, Codable, Hashable {

    public var id: String?
    public var timestamp: Date?
    public var mills: Int64?
    public var utcOffset: Int?
    public var device: String?
    public var app: String?
    public var dataSource: String?
    public var correlationId: String?
    public var legacyId: String?
    public var createdAt: Date?
    public var modifiedAt: Date?
    public var bloodGlucoseInput: Double?
    public var bloodGlucoseInputSource: String?
    public var carbInput: Double?
    public var insulinOnBoard: Double?
    public var insulinRecommendation: Double?
    public var carbRatio: Double?
    public var calculationType: CalculationType?
    public var insulinRecommendationForCarbs: Double?
    public var insulinProgrammed: Double?
    public var enteredInsulin: Double?
    public var splitNow: Double?
    public var splitExt: Double?
    public var preBolus: Double?
    public var additionalProperties: [String: JSONValue]?

    public init(id: String? = nil, timestamp: Date? = nil, mills: Int64? = nil, utcOffset: Int? = nil, device: String? = nil, app: String? = nil, dataSource: String? = nil, correlationId: String? = nil, legacyId: String? = nil, createdAt: Date? = nil, modifiedAt: Date? = nil, bloodGlucoseInput: Double? = nil, bloodGlucoseInputSource: String? = nil, carbInput: Double? = nil, insulinOnBoard: Double? = nil, insulinRecommendation: Double? = nil, carbRatio: Double? = nil, calculationType: CalculationType? = nil, insulinRecommendationForCarbs: Double? = nil, insulinProgrammed: Double? = nil, enteredInsulin: Double? = nil, splitNow: Double? = nil, splitExt: Double? = nil, preBolus: Double? = nil, additionalProperties: [String: JSONValue]? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.mills = mills
        self.utcOffset = utcOffset
        self.device = device
        self.app = app
        self.dataSource = dataSource
        self.correlationId = correlationId
        self.legacyId = legacyId
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
        self.bloodGlucoseInput = bloodGlucoseInput
        self.bloodGlucoseInputSource = bloodGlucoseInputSource
        self.carbInput = carbInput
        self.insulinOnBoard = insulinOnBoard
        self.insulinRecommendation = insulinRecommendation
        self.carbRatio = carbRatio
        self.calculationType = calculationType
        self.insulinRecommendationForCarbs = insulinRecommendationForCarbs
        self.insulinProgrammed = insulinProgrammed
        self.enteredInsulin = enteredInsulin
        self.splitNow = splitNow
        self.splitExt = splitExt
        self.preBolus = preBolus
        self.additionalProperties = additionalProperties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case mills
        case utcOffset
        case device
        case app
        case dataSource
        case correlationId
        case legacyId
        case createdAt
        case modifiedAt
        case bloodGlucoseInput
        case bloodGlucoseInputSource
        case carbInput
        case insulinOnBoard
        case insulinRecommendation
        case carbRatio
        case calculationType
        case insulinRecommendationForCarbs
        case insulinProgrammed
        case enteredInsulin
        case splitNow
        case splitExt
        case preBolus
        case additionalProperties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(mills, forKey: .mills)
        try container.encodeIfPresent(utcOffset, forKey: .utcOffset)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(dataSource, forKey: .dataSource)
        try container.encodeIfPresent(correlationId, forKey: .correlationId)
        try container.encodeIfPresent(legacyId, forKey: .legacyId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(modifiedAt, forKey: .modifiedAt)
        try container.encodeIfPresent(bloodGlucoseInput, forKey: .bloodGlucoseInput)
        try container.encodeIfPresent(bloodGlucoseInputSource, forKey: .bloodGlucoseInputSource)
        try container.encodeIfPresent(carbInput, forKey: .carbInput)
        try container.encodeIfPresent(insulinOnBoard, forKey: .insulinOnBoard)
        try container.encodeIfPresent(insulinRecommendation, forKey: .insulinRecommendation)
        try container.encodeIfPresent(carbRatio, forKey: .carbRatio)
        try container.encodeIfPresent(calculationType, forKey: .calculationType)
        try container.encodeIfPresent(insulinRecommendationForCarbs, forKey: .insulinRecommendationForCarbs)
        try container.encodeIfPresent(insulinProgrammed, forKey: .insulinProgrammed)
        try container.encodeIfPresent(enteredInsulin, forKey: .enteredInsulin)
        try container.encodeIfPresent(splitNow, forKey: .splitNow)
        try container.encodeIfPresent(splitExt, forKey: .splitExt)
        try container.encodeIfPresent(preBolus, forKey: .preBolus)
        try container.encodeIfPresent(additionalProperties, forKey: .additionalProperties)
    }
}


extension BolusCalculation: Identifiable {}
