//
// BolusKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum BolusKind: String, Sendable, Codable, CaseIterable {
    case manual = "Manual"
    case algorithm = "Algorithm"
}
