//
// CareLinkDesktopTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A link code for the desktop companion app. */
public struct CareLinkDesktopTokenResponse: Sendable, Codable, Hashable {

    /** nocturne-connect://link?server=…&token=… — pasted into the desktop app (or later opened as a deep link). Carries the server base URL and a short-lived bearer token. */
    public var linkCode: String?
    /** Seconds until the embedded token expires. */
    public var expiresInSeconds: Int?

    public init(linkCode: String? = nil, expiresInSeconds: Int? = nil) {
        self.linkCode = linkCode
        self.expiresInSeconds = expiresInSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case linkCode
        case expiresInSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(linkCode, forKey: .linkCode)
        try container.encodeIfPresent(expiresInSeconds, forKey: .expiresInSeconds)
    }
}

