//
// ChartThresholdsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChartThresholdsDto: Sendable, Codable, Hashable {

    public var low: Double?
    public var high: Double?
    public var veryLow: Double?
    public var veryHigh: Double?
    public var glucoseYMax: Double?

    public init(low: Double? = nil, high: Double? = nil, veryLow: Double? = nil, veryHigh: Double? = nil, glucoseYMax: Double? = nil) {
        self.low = low
        self.high = high
        self.veryLow = veryLow
        self.veryHigh = veryHigh
        self.glucoseYMax = glucoseYMax
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case low
        case high
        case veryLow
        case veryHigh
        case glucoseYMax
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(low, forKey: .low)
        try container.encodeIfPresent(high, forKey: .high)
        try container.encodeIfPresent(veryLow, forKey: .veryLow)
        try container.encodeIfPresent(veryHigh, forKey: .veryHigh)
        try container.encodeIfPresent(glucoseYMax, forKey: .glucoseYMax)
    }
}

