//
// ClinicalAssessmentLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum ClinicalAssessmentLevel: String, Sendable, Codable, CaseIterable {
    case excellent = "Excellent"
    case good = "Good"
    case needsAttention = "NeedsAttention"
    case needsSignificantImprovement = "NeedsSignificantImprovement"
}
