//
// ClockFacePublicDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClockFacePublicDto: Sendable, Codable, Hashable {

    public var id: String?
    public var config: ClockFaceConfig?

    public init(id: String? = nil, config: ClockFaceConfig? = nil) {
        self.id = id
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(config, forKey: .config)
    }
}


extension ClockFacePublicDto: Identifiable {}
