//
// ClockGlucoseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClockGlucoseDto: Sendable, Codable, Hashable {

    public var mills: Int64?
    public var mgdl: Double?
    public var direction: String?
    public var delta: Double?
    public var dataSource: String?

    public init(mills: Int64? = nil, mgdl: Double? = nil, direction: String? = nil, delta: Double? = nil, dataSource: String? = nil) {
        self.mills = mills
        self.mgdl = mgdl
        self.direction = direction
        self.delta = delta
        self.dataSource = dataSource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mills
        case mgdl
        case direction
        case delta
        case dataSource
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mills, forKey: .mills)
        try container.encodeIfPresent(mgdl, forKey: .mgdl)
        try container.encodeIfPresent(direction, forKey: .direction)
        try container.encodeIfPresent(delta, forKey: .delta)
        try container.encodeIfPresent(dataSource, forKey: .dataSource)
    }
}

