//
// CompatibilityInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CompatibilityInfo: Sendable, Codable, Hashable {

    public var proxyEnabled: Bool?
    public var compatibilityScore: Double?
    public var totalComparisons: Int?
    public var discrepancies: Int?

    public init(proxyEnabled: Bool? = nil, compatibilityScore: Double? = nil, totalComparisons: Int? = nil, discrepancies: Int? = nil) {
        self.proxyEnabled = proxyEnabled
        self.compatibilityScore = compatibilityScore
        self.totalComparisons = totalComparisons
        self.discrepancies = discrepancies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case proxyEnabled
        case compatibilityScore
        case totalComparisons
        case discrepancies
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(proxyEnabled, forKey: .proxyEnabled)
        try container.encodeIfPresent(compatibilityScore, forKey: .compatibilityScore)
        try container.encodeIfPresent(totalComparisons, forKey: .totalComparisons)
        try container.encodeIfPresent(discrepancies, forKey: .discrepancies)
    }
}

