//
// CompressionLowSuggestion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CompressionLowSuggestion: Sendable, Codable, Hashable {

    public var id: String?
    public var startMills: Int64?
    public var endMills: Int64?
    public var confidence: Double?
    public var status: CompressionLowStatus?
    public var nightOf: Date?
    public var createdAt: Int64?
    public var reviewedAt: Int64?
    public var stateSpanId: String?
    public var lowestGlucose: Double?
    public var dropRate: Double?
    public var recoveryMinutes: Int?

    public init(id: String? = nil, startMills: Int64? = nil, endMills: Int64? = nil, confidence: Double? = nil, status: CompressionLowStatus? = nil, nightOf: Date? = nil, createdAt: Int64? = nil, reviewedAt: Int64? = nil, stateSpanId: String? = nil, lowestGlucose: Double? = nil, dropRate: Double? = nil, recoveryMinutes: Int? = nil) {
        self.id = id
        self.startMills = startMills
        self.endMills = endMills
        self.confidence = confidence
        self.status = status
        self.nightOf = nightOf
        self.createdAt = createdAt
        self.reviewedAt = reviewedAt
        self.stateSpanId = stateSpanId
        self.lowestGlucose = lowestGlucose
        self.dropRate = dropRate
        self.recoveryMinutes = recoveryMinutes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case startMills
        case endMills
        case confidence
        case status
        case nightOf
        case createdAt
        case reviewedAt
        case stateSpanId
        case lowestGlucose
        case dropRate
        case recoveryMinutes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(startMills, forKey: .startMills)
        try container.encodeIfPresent(endMills, forKey: .endMills)
        try container.encodeIfPresent(confidence, forKey: .confidence)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(nightOf, forKey: .nightOf)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(reviewedAt, forKey: .reviewedAt)
        try container.encodeIfPresent(stateSpanId, forKey: .stateSpanId)
        try container.encodeIfPresent(lowestGlucose, forKey: .lowestGlucose)
        try container.encodeIfPresent(dropRate, forKey: .dropRate)
        try container.encodeIfPresent(recoveryMinutes, forKey: .recoveryMinutes)
    }
}


extension CompressionLowSuggestion: Identifiable {}
