//
// ConnectorCapabilities.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectorCapabilities: Sendable, Codable, Hashable {

    public var supportedDataTypes: [String]?
    public var supportsHistoricalSync: Bool?
    public var maxHistoricalDays: Int?
    public var supportsManualSync: Bool?

    public init(supportedDataTypes: [String]? = nil, supportsHistoricalSync: Bool? = nil, maxHistoricalDays: Int? = nil, supportsManualSync: Bool? = nil) {
        self.supportedDataTypes = supportedDataTypes
        self.supportsHistoricalSync = supportsHistoricalSync
        self.maxHistoricalDays = maxHistoricalDays
        self.supportsManualSync = supportsManualSync
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case supportedDataTypes
        case supportsHistoricalSync
        case maxHistoricalDays
        case supportsManualSync
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(supportedDataTypes, forKey: .supportedDataTypes)
        try container.encodeIfPresent(supportsHistoricalSync, forKey: .supportsHistoricalSync)
        try container.encodeIfPresent(maxHistoricalDays, forKey: .maxHistoricalDays)
        try container.encodeIfPresent(supportsManualSync, forKey: .supportsManualSync)
    }
}

