//
// ConnectorConfigSnapshotDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Serialized representation of a connector configuration with decrypted secrets for snapshot export/import. */
public struct ConnectorConfigSnapshotDto: Sendable, Codable, Hashable {

    public var id: String?
    public var tenantId: String?
    public var connectorName: String?
    public var configurationJson: String?
    public var secretsPlaintext: [String: String]?
    public var schemaVersion: Int?
    public var lastModified: Date?
    public var modifiedBy: String?
    public var sysCreatedAt: Date?
    public var sysUpdatedAt: Date?
    public var lastSyncAttempt: Date?
    public var lastSuccessfulSync: Date?
    public var lastErrorMessage: String?
    public var lastErrorAt: Date?
    public var isHealthy: Bool?

    public init(id: String? = nil, tenantId: String? = nil, connectorName: String? = nil, configurationJson: String? = nil, secretsPlaintext: [String: String]? = nil, schemaVersion: Int? = nil, lastModified: Date? = nil, modifiedBy: String? = nil, sysCreatedAt: Date? = nil, sysUpdatedAt: Date? = nil, lastSyncAttempt: Date? = nil, lastSuccessfulSync: Date? = nil, lastErrorMessage: String? = nil, lastErrorAt: Date? = nil, isHealthy: Bool? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.connectorName = connectorName
        self.configurationJson = configurationJson
        self.secretsPlaintext = secretsPlaintext
        self.schemaVersion = schemaVersion
        self.lastModified = lastModified
        self.modifiedBy = modifiedBy
        self.sysCreatedAt = sysCreatedAt
        self.sysUpdatedAt = sysUpdatedAt
        self.lastSyncAttempt = lastSyncAttempt
        self.lastSuccessfulSync = lastSuccessfulSync
        self.lastErrorMessage = lastErrorMessage
        self.lastErrorAt = lastErrorAt
        self.isHealthy = isHealthy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId
        case connectorName
        case configurationJson
        case secretsPlaintext
        case schemaVersion
        case lastModified
        case modifiedBy
        case sysCreatedAt
        case sysUpdatedAt
        case lastSyncAttempt
        case lastSuccessfulSync
        case lastErrorMessage
        case lastErrorAt
        case isHealthy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(connectorName, forKey: .connectorName)
        try container.encodeIfPresent(configurationJson, forKey: .configurationJson)
        try container.encodeIfPresent(secretsPlaintext, forKey: .secretsPlaintext)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(lastModified, forKey: .lastModified)
        try container.encodeIfPresent(modifiedBy, forKey: .modifiedBy)
        try container.encodeIfPresent(sysCreatedAt, forKey: .sysCreatedAt)
        try container.encodeIfPresent(sysUpdatedAt, forKey: .sysUpdatedAt)
        try container.encodeIfPresent(lastSyncAttempt, forKey: .lastSyncAttempt)
        try container.encodeIfPresent(lastSuccessfulSync, forKey: .lastSuccessfulSync)
        try container.encodeIfPresent(lastErrorMessage, forKey: .lastErrorMessage)
        try container.encodeIfPresent(lastErrorAt, forKey: .lastErrorAt)
        try container.encodeIfPresent(isHealthy, forKey: .isHealthy)
    }
}


extension ConnectorConfigSnapshotDto: Identifiable {}
