//
// ConnectorConfigField.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectorConfigField: Sendable, Codable, Hashable {

    public var id: String?
    public var label: String?
    public var type: String?
    public var _required: Bool?
    public var placeholder: String?
    public var helpText: String?
    public var options: [SelectOption]?

    public init(id: String? = nil, label: String? = nil, type: String? = nil, _required: Bool? = nil, placeholder: String? = nil, helpText: String? = nil, options: [SelectOption]? = nil) {
        self.id = id
        self.label = label
        self.type = type
        self._required = _required
        self.placeholder = placeholder
        self.helpText = helpText
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case type
        case _required = "required"
        case placeholder
        case helpText
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(_required, forKey: ._required)
        try container.encodeIfPresent(placeholder, forKey: .placeholder)
        try container.encodeIfPresent(helpText, forKey: .helpText)
        try container.encodeIfPresent(options, forKey: .options)
    }
}


extension ConnectorConfigField: Identifiable {}
