//
// CreateGuestLinkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request body for creating a guest link. */
public struct CreateGuestLinkRequest: Sendable, Codable, Hashable {

    public var label: String?
    public var scopes: [String]?

    public init(label: String? = nil, scopes: [String]? = nil) {
        self.label = label
        self.scopes = scopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case scopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(scopes, forKey: .scopes)
    }
}

