//
// CreateChatIdentityLinkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateChatIdentityLinkRequest: Sendable, Codable, Hashable {

    public var nocturneUserId: String?
    public var platform: String?
    public var platformUserId: String?
    public var platformChannelId: String?

    public init(nocturneUserId: String? = nil, platform: String? = nil, platformUserId: String? = nil, platformChannelId: String? = nil) {
        self.nocturneUserId = nocturneUserId
        self.platform = platform
        self.platformUserId = platformUserId
        self.platformChannelId = platformChannelId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nocturneUserId
        case platform
        case platformUserId
        case platformChannelId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nocturneUserId, forKey: .nocturneUserId)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(platformUserId, forKey: .platformUserId)
        try container.encodeIfPresent(platformChannelId, forKey: .platformChannelId)
    }
}

