//
// CreateTempBasalRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request body for writing a temporary basal rate span via the V4 API. */
public struct CreateTempBasalRequest: Sendable, Codable, Hashable {

    /** When the temp basal started (or, for cancels, when the active temp basal ends). */
    public var timestamp: Date?
    /** UTC offset in minutes at the time of the event, for local-time display. */
    public var utcOffset: Int?
    /** Identifier of the pump that ran the temp basal. */
    public var device: String?
    /** Name of the application that submitted this record. */
    public var app: String?
    /** Upstream data source identifier; required when SyncIdentifier is supplied. */
    public var dataSource: String?
    /** Stable per-source identifier. When paired with DataSource, re-uploading the same temp basal updates the existing record in place rather than creating a duplicate. */
    public var syncIdentifier: String?
    /** Correlation identifier for grouping related events (e.g. the APS snapshot that enacted it). */
    public var correlationId: String?
    /** Temporary basal rate in units per hour. Zero is valid (zero-temp). */
    public var rate: Double?
    /** Planned duration in minutes; the span end is computed as timestamp + duration. Omit for an open-ended span (ended later by a cancel or a superseding temp basal). */
    public var durationMinutes: Double?
    /** Scheduled basal rate that this temp basal overrides, when known. */
    public var scheduledRate: Double?
    public var origin: TempBasalOrigin?
    /** Pump-specific record identifier, when the pump reports one. */
    public var pumpRecordId: String?
    /** Links this temp basal to the APS decision snapshot that enacted it. */
    public var apsSnapshotId: String?
    /** When true, truncates the temp basal active at Timestamp instead of creating a record. A cancel with no active temp basal is a no-op. */
    public var isCancel: Bool?

    public init(timestamp: Date? = nil, utcOffset: Int? = nil, device: String? = nil, app: String? = nil, dataSource: String? = nil, syncIdentifier: String? = nil, correlationId: String? = nil, rate: Double? = nil, durationMinutes: Double? = nil, scheduledRate: Double? = nil, origin: TempBasalOrigin? = nil, pumpRecordId: String? = nil, apsSnapshotId: String? = nil, isCancel: Bool? = nil) {
        self.timestamp = timestamp
        self.utcOffset = utcOffset
        self.device = device
        self.app = app
        self.dataSource = dataSource
        self.syncIdentifier = syncIdentifier
        self.correlationId = correlationId
        self.rate = rate
        self.durationMinutes = durationMinutes
        self.scheduledRate = scheduledRate
        self.origin = origin
        self.pumpRecordId = pumpRecordId
        self.apsSnapshotId = apsSnapshotId
        self.isCancel = isCancel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case utcOffset
        case device
        case app
        case dataSource
        case syncIdentifier
        case correlationId
        case rate
        case durationMinutes
        case scheduledRate
        case origin
        case pumpRecordId
        case apsSnapshotId
        case isCancel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(utcOffset, forKey: .utcOffset)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(dataSource, forKey: .dataSource)
        try container.encodeIfPresent(syncIdentifier, forKey: .syncIdentifier)
        try container.encodeIfPresent(correlationId, forKey: .correlationId)
        try container.encodeIfPresent(rate, forKey: .rate)
        try container.encodeIfPresent(durationMinutes, forKey: .durationMinutes)
        try container.encodeIfPresent(scheduledRate, forKey: .scheduledRate)
        try container.encodeIfPresent(origin, forKey: .origin)
        try container.encodeIfPresent(pumpRecordId, forKey: .pumpRecordId)
        try container.encodeIfPresent(apsSnapshotId, forKey: .apsSnapshotId)
        try container.encodeIfPresent(isCancel, forKey: .isCancel)
    }
}

