//
// CreateDirectLinkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateDirectLinkRequest: Sendable, Codable, Hashable {

    public var platform: String?
    public var platformUserId: String?

    public init(platform: String? = nil, platformUserId: String? = nil) {
        self.platform = platform
        self.platformUserId = platformUserId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case platformUserId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(platformUserId, forKey: .platformUserId)
    }
}

