//
// CreateAlertInviteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateAlertInviteRequest: Sendable, Codable, Hashable {

    public var alertRuleChannelId: String?
    public var permissionScope: String?

    public init(alertRuleChannelId: String? = nil, permissionScope: String? = nil) {
        self.alertRuleChannelId = alertRuleChannelId
        self.permissionScope = permissionScope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alertRuleChannelId
        case permissionScope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alertRuleChannelId, forKey: .alertRuleChannelId)
        try container.encodeIfPresent(permissionScope, forKey: .permissionScope)
    }
}

