//
// CreateDndWindowRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request to create a DND window. Id is client-supplied for idempotency. */
public struct CreateDndWindowRequest: Sendable, Codable, Hashable {

    /** Client-generated UUID. Re-sending the same id is a no-op that returns the stored window. */
    public var id: String?
    public var scope: DndScope?
    /** When the mute takes effect (may predate receipt for offline authoring). */
    public var startedAt: Date?
    /** Auto-expiry instant; null mutes until explicitly cleared. */
    public var endsAt: Date?
    /** Audit label for what created the window (e.g. web, prelude-device). */
    public var source: String?

    public init(id: String? = nil, scope: DndScope? = nil, startedAt: Date? = nil, endsAt: Date? = nil, source: String? = nil) {
        self.id = id
        self.scope = scope
        self.startedAt = startedAt
        self.endsAt = endsAt
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case scope
        case startedAt
        case endsAt
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(endsAt, forKey: .endsAt)
        try container.encodeIfPresent(source, forKey: .source)
    }
}


extension CreateDndWindowRequest: Identifiable {}
