//
// DailySummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DailySummaryResponse: Sendable, Codable, Hashable {

    public var year: Int?
    public var dataSources: [String]?
    public var days: [DailySummaryDay]?

    public init(year: Int? = nil, dataSources: [String]? = nil, days: [DailySummaryDay]? = nil) {
        self.year = year
        self.dataSources = dataSources
        self.days = days
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
        case dataSources
        case days
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(dataSources, forKey: .dataSources)
        try container.encodeIfPresent(days, forKey: .days)
    }
}

