//
// DashboardVisibility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum DashboardVisibility: String, Sendable, Codable, CaseIterable {
    case off = "Off"
    case always = "Always"
    case info = "Info"
    case warn = "Warn"
    case hazard = "Hazard"
    case urgent = "Urgent"
}
