//
// DataSufficiencyAssessment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DataSufficiencyAssessment: Sendable, Codable, Hashable {

    public var isSufficient: Bool?
    public var totalDays: Int?
    public var daysWithData: Int?
    public var expectedReadings: Int?
    public var actualReadings: Int?
    public var completenessPercentage: Double?
    public var minimumRequiredCompleteness: Double?
    public var averageReadingsPerDay: Double?
    public var longestGapHours: Double?
    public var status: DataSufficiencyStatus?
    public var warningMessage: String?
    public var recommendation: String?

    public init(isSufficient: Bool? = nil, totalDays: Int? = nil, daysWithData: Int? = nil, expectedReadings: Int? = nil, actualReadings: Int? = nil, completenessPercentage: Double? = nil, minimumRequiredCompleteness: Double? = nil, averageReadingsPerDay: Double? = nil, longestGapHours: Double? = nil, status: DataSufficiencyStatus? = nil, warningMessage: String? = nil, recommendation: String? = nil) {
        self.isSufficient = isSufficient
        self.totalDays = totalDays
        self.daysWithData = daysWithData
        self.expectedReadings = expectedReadings
        self.actualReadings = actualReadings
        self.completenessPercentage = completenessPercentage
        self.minimumRequiredCompleteness = minimumRequiredCompleteness
        self.averageReadingsPerDay = averageReadingsPerDay
        self.longestGapHours = longestGapHours
        self.status = status
        self.warningMessage = warningMessage
        self.recommendation = recommendation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSufficient
        case totalDays
        case daysWithData
        case expectedReadings
        case actualReadings
        case completenessPercentage
        case minimumRequiredCompleteness
        case averageReadingsPerDay
        case longestGapHours
        case status
        case warningMessage
        case recommendation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isSufficient, forKey: .isSufficient)
        try container.encodeIfPresent(totalDays, forKey: .totalDays)
        try container.encodeIfPresent(daysWithData, forKey: .daysWithData)
        try container.encodeIfPresent(expectedReadings, forKey: .expectedReadings)
        try container.encodeIfPresent(actualReadings, forKey: .actualReadings)
        try container.encodeIfPresent(completenessPercentage, forKey: .completenessPercentage)
        try container.encodeIfPresent(minimumRequiredCompleteness, forKey: .minimumRequiredCompleteness)
        try container.encodeIfPresent(averageReadingsPerDay, forKey: .averageReadingsPerDay)
        try container.encodeIfPresent(longestGapHours, forKey: .longestGapHours)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(warningMessage, forKey: .warningMessage)
        try container.encodeIfPresent(recommendation, forKey: .recommendation)
    }
}

