//
// DayData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DayData: Sendable, Codable, Hashable {

    public var date: String?
    public var treatments: [Treatment]?
    public var treatmentSummary: TreatmentSummary?
    public var timeInRanges: TimeInRangeMetrics?

    public init(date: String? = nil, treatments: [Treatment]? = nil, treatmentSummary: TreatmentSummary? = nil, timeInRanges: TimeInRangeMetrics? = nil) {
        self.date = date
        self.treatments = treatments
        self.treatmentSummary = treatmentSummary
        self.timeInRanges = timeInRanges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case treatments
        case treatmentSummary
        case timeInRanges
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(treatments, forKey: .treatments)
        try container.encodeIfPresent(treatmentSummary, forKey: .treatmentSummary)
        try container.encodeIfPresent(timeInRanges, forKey: .timeInRanges)
    }
}

