//
// DeduplicationJobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeduplicationJobStatus: Sendable, Codable, Hashable {

    public var jobId: String?
    public var state: DeduplicationJobState?
    public var startedAt: Date?
    public var completedAt: Date?
    public var progress: DeduplicationProgress?
    public var result: DeduplicationResult?

    public init(jobId: String? = nil, state: DeduplicationJobState? = nil, startedAt: Date? = nil, completedAt: Date? = nil, progress: DeduplicationProgress? = nil, result: DeduplicationResult? = nil) {
        self.jobId = jobId
        self.state = state
        self.startedAt = startedAt
        self.completedAt = completedAt
        self.progress = progress
        self.result = result
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobId
        case state
        case startedAt
        case completedAt
        case progress
        case result
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(jobId, forKey: .jobId)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encodeIfPresent(progress, forKey: .progress)
        try container.encodeIfPresent(result, forKey: .result)
    }
}

