//
// DeduplicationResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeduplicationResult: Sendable, Codable, Hashable {

    public var totalRecordsProcessed: Int?
    public var canonicalGroupsCreated: Int?
    public var recordsLinked: Int?
    public var duplicateGroupsFound: Int?
    public var duration: String?
    public var entriesProcessed: Int?
    public var treatmentsProcessed: Int?
    public var stateSpansProcessed: Int?
    public var sensorGlucoseProcessed: Int?
    public var bolusesProcessed: Int?
    public var carbIntakesProcessed: Int?
    public var bgChecksProcessed: Int?
    public var deviceEventsProcessed: Int?
    public var notesProcessed: Int?
    public var bolusCalculationsProcessed: Int?
    public var tempBasalsProcessed: Int?
    public var success: Bool?
    public var errorMessage: String?

    public init(totalRecordsProcessed: Int? = nil, canonicalGroupsCreated: Int? = nil, recordsLinked: Int? = nil, duplicateGroupsFound: Int? = nil, duration: String? = nil, entriesProcessed: Int? = nil, treatmentsProcessed: Int? = nil, stateSpansProcessed: Int? = nil, sensorGlucoseProcessed: Int? = nil, bolusesProcessed: Int? = nil, carbIntakesProcessed: Int? = nil, bgChecksProcessed: Int? = nil, deviceEventsProcessed: Int? = nil, notesProcessed: Int? = nil, bolusCalculationsProcessed: Int? = nil, tempBasalsProcessed: Int? = nil, success: Bool? = nil, errorMessage: String? = nil) {
        self.totalRecordsProcessed = totalRecordsProcessed
        self.canonicalGroupsCreated = canonicalGroupsCreated
        self.recordsLinked = recordsLinked
        self.duplicateGroupsFound = duplicateGroupsFound
        self.duration = duration
        self.entriesProcessed = entriesProcessed
        self.treatmentsProcessed = treatmentsProcessed
        self.stateSpansProcessed = stateSpansProcessed
        self.sensorGlucoseProcessed = sensorGlucoseProcessed
        self.bolusesProcessed = bolusesProcessed
        self.carbIntakesProcessed = carbIntakesProcessed
        self.bgChecksProcessed = bgChecksProcessed
        self.deviceEventsProcessed = deviceEventsProcessed
        self.notesProcessed = notesProcessed
        self.bolusCalculationsProcessed = bolusCalculationsProcessed
        self.tempBasalsProcessed = tempBasalsProcessed
        self.success = success
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalRecordsProcessed
        case canonicalGroupsCreated
        case recordsLinked
        case duplicateGroupsFound
        case duration
        case entriesProcessed
        case treatmentsProcessed
        case stateSpansProcessed
        case sensorGlucoseProcessed
        case bolusesProcessed
        case carbIntakesProcessed
        case bgChecksProcessed
        case deviceEventsProcessed
        case notesProcessed
        case bolusCalculationsProcessed
        case tempBasalsProcessed
        case success
        case errorMessage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalRecordsProcessed, forKey: .totalRecordsProcessed)
        try container.encodeIfPresent(canonicalGroupsCreated, forKey: .canonicalGroupsCreated)
        try container.encodeIfPresent(recordsLinked, forKey: .recordsLinked)
        try container.encodeIfPresent(duplicateGroupsFound, forKey: .duplicateGroupsFound)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(entriesProcessed, forKey: .entriesProcessed)
        try container.encodeIfPresent(treatmentsProcessed, forKey: .treatmentsProcessed)
        try container.encodeIfPresent(stateSpansProcessed, forKey: .stateSpansProcessed)
        try container.encodeIfPresent(sensorGlucoseProcessed, forKey: .sensorGlucoseProcessed)
        try container.encodeIfPresent(bolusesProcessed, forKey: .bolusesProcessed)
        try container.encodeIfPresent(carbIntakesProcessed, forKey: .carbIntakesProcessed)
        try container.encodeIfPresent(bgChecksProcessed, forKey: .bgChecksProcessed)
        try container.encodeIfPresent(deviceEventsProcessed, forKey: .deviceEventsProcessed)
        try container.encodeIfPresent(notesProcessed, forKey: .notesProcessed)
        try container.encodeIfPresent(bolusCalculationsProcessed, forKey: .bolusCalculationsProcessed)
        try container.encodeIfPresent(tempBasalsProcessed, forKey: .tempBasalsProcessed)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
    }
}

