//
// DevConnectorSummaryDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DevConnectorSummaryDto: Sendable, Codable, Hashable {

    public var name: String?
    public var isHealthy: Bool?
    public var lastSuccessfulSync: Date?
    public var lastError: String?

    public init(name: String? = nil, isHealthy: Bool? = nil, lastSuccessfulSync: Date? = nil, lastError: String? = nil) {
        self.name = name
        self.isHealthy = isHealthy
        self.lastSuccessfulSync = lastSuccessfulSync
        self.lastError = lastError
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case isHealthy
        case lastSuccessfulSync
        case lastError
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isHealthy, forKey: .isHealthy)
        try container.encodeIfPresent(lastSuccessfulSync, forKey: .lastSuccessfulSync)
        try container.encodeIfPresent(lastError, forKey: .lastError)
    }
}

