//
// DevIdentityFixtureFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A committed, Development-only fixture of developer identities and their real WebAuthn credentials. WebAuthn public keys are not secret and subjects are global (not tenant-scoped), so the fixture can be committed and re-inserted after a database wipe — the developer&#39;s real authenticator then signs in without re-registering. Exported by GET api/v4/dev-only/auth/passkey-fixture, consumed at API startup (Development only) and by seed-tenant, which adds every fixture subject as an owner of the seeded tenant. */
public struct DevIdentityFixtureFile: Sendable, Codable, Hashable {

    public var identities: [DevIdentityDto]?

    public init(identities: [DevIdentityDto]? = nil) {
        self.identities = identities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identities, forKey: .identities)
    }
}

