//
// DevIdentityCredentialDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A stored WebAuthn credential (public key only). SignCount is intentionally absent: credentials are always re-inserted with sign_count &#x3D; 0, which any real authenticator&#39;s next assertion counter exceeds. */
public struct DevIdentityCredentialDto: Sendable, Codable, Hashable {

    public var credentialId: String?
    public var publicKey: String?
    public var transports: [String]?
    public var label: String?
    public var aaGuid: String?

    public init(credentialId: String? = nil, publicKey: String? = nil, transports: [String]? = nil, label: String? = nil, aaGuid: String? = nil) {
        self.credentialId = credentialId
        self.publicKey = publicKey
        self.transports = transports
        self.label = label
        self.aaGuid = aaGuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credentialId
        case publicKey
        case transports
        case label
        case aaGuid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(credentialId, forKey: .credentialId)
        try container.encodeIfPresent(publicKey, forKey: .publicKey)
        try container.encodeIfPresent(transports, forKey: .transports)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(aaGuid, forKey: .aaGuid)
    }
}

