//
// DevSeedTenantResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DevSeedTenantResponse: Sendable, Codable, Hashable {

    public var tenantId: String?
    public var subjectId: String?
    public var accessToken: String?
    public var refreshToken: String?
    public var expiresInSeconds: Int?
    public var url: String?
    public var loginLink: String?
    public var entriesSeeded: Int?
    public var treatmentsSeeded: Int?
    public var sleepSessionsSeeded: Int?
    public var seeded: SampleDataSeedResult?

    public init(tenantId: String? = nil, subjectId: String? = nil, accessToken: String? = nil, refreshToken: String? = nil, expiresInSeconds: Int? = nil, url: String? = nil, loginLink: String? = nil, entriesSeeded: Int? = nil, treatmentsSeeded: Int? = nil, sleepSessionsSeeded: Int? = nil, seeded: SampleDataSeedResult? = nil) {
        self.tenantId = tenantId
        self.subjectId = subjectId
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.expiresInSeconds = expiresInSeconds
        self.url = url
        self.loginLink = loginLink
        self.entriesSeeded = entriesSeeded
        self.treatmentsSeeded = treatmentsSeeded
        self.sleepSessionsSeeded = sleepSessionsSeeded
        self.seeded = seeded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tenantId
        case subjectId
        case accessToken
        case refreshToken
        case expiresInSeconds
        case url
        case loginLink
        case entriesSeeded
        case treatmentsSeeded
        case sleepSessionsSeeded
        case seeded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(subjectId, forKey: .subjectId)
        try container.encodeIfPresent(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
        try container.encodeIfPresent(expiresInSeconds, forKey: .expiresInSeconds)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(loginLink, forKey: .loginLink)
        try container.encodeIfPresent(entriesSeeded, forKey: .entriesSeeded)
        try container.encodeIfPresent(treatmentsSeeded, forKey: .treatmentsSeeded)
        try container.encodeIfPresent(sleepSessionsSeeded, forKey: .sleepSessionsSeeded)
        try container.encodeIfPresent(seeded, forKey: .seeded)
    }
}

