//
// DevSeedTenantRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DevSeedTenantRequest: Sendable, Codable, Hashable {

    public var slug: String?
    public var displayName: String?
    public var ownerUsername: String?
    public var sampleData: Bool?
    public var sampleDataDays: Int?

    public init(slug: String? = nil, displayName: String? = nil, ownerUsername: String? = nil, sampleData: Bool? = nil, sampleDataDays: Int? = nil) {
        self.slug = slug
        self.displayName = displayName
        self.ownerUsername = ownerUsername
        self.sampleData = sampleData
        self.sampleDataDays = sampleDataDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slug
        case displayName
        case ownerUsername
        case sampleData
        case sampleDataDays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(ownerUsername, forKey: .ownerUsername)
        try container.encodeIfPresent(sampleData, forKey: .sampleData)
        try container.encodeIfPresent(sampleDataDays, forKey: .sampleDataDays)
    }
}

