//
// DiabetesType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum DiabetesType: String, Sendable, Codable, CaseIterable {
    case type1 = "Type1"
    case type2 = "Type2"
    case lada = "LADA"
    case mody = "MODY"
    case gestational = "Gestational"
    case other = "Other"
}
