//
// DndWindowResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A DND window with its resolver fields. active state is computed on read. */
public struct DndWindowResponse: Sendable, Codable, Hashable {

    public var id: String?
    public var scope: DndScope?
    public var startedAt: Date?
    public var endsAt: Date?
    public var clearedAt: Date?
    public var clearedBy: String?
    public var source: String?
    public var createdAt: Date?

    public init(id: String? = nil, scope: DndScope? = nil, startedAt: Date? = nil, endsAt: Date? = nil, clearedAt: Date? = nil, clearedBy: String? = nil, source: String? = nil, createdAt: Date? = nil) {
        self.id = id
        self.scope = scope
        self.startedAt = startedAt
        self.endsAt = endsAt
        self.clearedAt = clearedAt
        self.clearedBy = clearedBy
        self.source = source
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case scope
        case startedAt
        case endsAt
        case clearedAt
        case clearedBy
        case source
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(endsAt, forKey: .endsAt)
        try container.encodeIfPresent(clearedAt, forKey: .clearedAt)
        try container.encodeIfPresent(clearedBy, forKey: .clearedBy)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


extension DndWindowResponse: Identifiable {}
