//
// Entry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Entry: Sendable, Codable, Hashable {

    public var id: String?
    public var createdAt: String?
    public var mills: Int64?
    public var utcOffset: Int?
    public var date: Int64?
    public var dateString: String?
    public var mgdl: Double?
    public var mbg: Double?
    public var mmol: Double?
    public var sgv: Double?
    public var direction: String?
    public var trend: Int?
    public var trendRate: Double?
    public var isCalibration: Bool?
    public var type: String?
    public var device: String?
    public var notes: String?
    public var delta: Double?
    public var scaled: JSONValue?
    public var sysTime: String?
    public var noise: Int?
    public var filtered: Double?
    public var unfiltered: Double?
    public var rssi: Int?
    public var slope: Double?
    public var intercept: Double?
    public var scale: Double?
    public var modifiedAt: Date?
    public var dataSource: String?
    public var meta: [String: JSONValue]?
    public var canonicalId: String?
    public var sources: [String]?
    public var app: String?
    public var units: String?
    public var isValid: Bool?
    public var isReadOnly: Bool?
    public var identifier: String?
    public var srvModified: Int64?
    public var srvCreated: Int64?
    public var subject: String?

    public init(id: String? = nil, createdAt: String? = nil, mills: Int64? = nil, utcOffset: Int? = nil, date: Int64? = nil, dateString: String? = nil, mgdl: Double? = nil, mbg: Double? = nil, mmol: Double? = nil, sgv: Double? = nil, direction: String? = nil, trend: Int? = nil, trendRate: Double? = nil, isCalibration: Bool? = nil, type: String? = nil, device: String? = nil, notes: String? = nil, delta: Double? = nil, scaled: JSONValue? = nil, sysTime: String? = nil, noise: Int? = nil, filtered: Double? = nil, unfiltered: Double? = nil, rssi: Int? = nil, slope: Double? = nil, intercept: Double? = nil, scale: Double? = nil, modifiedAt: Date? = nil, dataSource: String? = nil, meta: [String: JSONValue]? = nil, canonicalId: String? = nil, sources: [String]? = nil, app: String? = nil, units: String? = nil, isValid: Bool? = nil, isReadOnly: Bool? = nil, identifier: String? = nil, srvModified: Int64? = nil, srvCreated: Int64? = nil, subject: String? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.mills = mills
        self.utcOffset = utcOffset
        self.date = date
        self.dateString = dateString
        self.mgdl = mgdl
        self.mbg = mbg
        self.mmol = mmol
        self.sgv = sgv
        self.direction = direction
        self.trend = trend
        self.trendRate = trendRate
        self.isCalibration = isCalibration
        self.type = type
        self.device = device
        self.notes = notes
        self.delta = delta
        self.scaled = scaled
        self.sysTime = sysTime
        self.noise = noise
        self.filtered = filtered
        self.unfiltered = unfiltered
        self.rssi = rssi
        self.slope = slope
        self.intercept = intercept
        self.scale = scale
        self.modifiedAt = modifiedAt
        self.dataSource = dataSource
        self.meta = meta
        self.canonicalId = canonicalId
        self.sources = sources
        self.app = app
        self.units = units
        self.isValid = isValid
        self.isReadOnly = isReadOnly
        self.identifier = identifier
        self.srvModified = srvModified
        self.srvCreated = srvCreated
        self.subject = subject
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case mills
        case utcOffset
        case date
        case dateString
        case mgdl
        case mbg
        case mmol
        case sgv
        case direction
        case trend
        case trendRate
        case isCalibration
        case type
        case device
        case notes
        case delta
        case scaled
        case sysTime
        case noise
        case filtered
        case unfiltered
        case rssi
        case slope
        case intercept
        case scale
        case modifiedAt = "modified_at"
        case dataSource = "data_source"
        case meta
        case canonicalId
        case sources
        case app
        case units
        case isValid
        case isReadOnly
        case identifier
        case srvModified
        case srvCreated
        case subject
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(mills, forKey: .mills)
        try container.encodeIfPresent(utcOffset, forKey: .utcOffset)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(dateString, forKey: .dateString)
        try container.encodeIfPresent(mgdl, forKey: .mgdl)
        try container.encodeIfPresent(mbg, forKey: .mbg)
        try container.encodeIfPresent(mmol, forKey: .mmol)
        try container.encodeIfPresent(sgv, forKey: .sgv)
        try container.encodeIfPresent(direction, forKey: .direction)
        try container.encodeIfPresent(trend, forKey: .trend)
        try container.encodeIfPresent(trendRate, forKey: .trendRate)
        try container.encodeIfPresent(isCalibration, forKey: .isCalibration)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(delta, forKey: .delta)
        try container.encodeIfPresent(scaled, forKey: .scaled)
        try container.encodeIfPresent(sysTime, forKey: .sysTime)
        try container.encodeIfPresent(noise, forKey: .noise)
        try container.encodeIfPresent(filtered, forKey: .filtered)
        try container.encodeIfPresent(unfiltered, forKey: .unfiltered)
        try container.encodeIfPresent(rssi, forKey: .rssi)
        try container.encodeIfPresent(slope, forKey: .slope)
        try container.encodeIfPresent(intercept, forKey: .intercept)
        try container.encodeIfPresent(scale, forKey: .scale)
        try container.encodeIfPresent(modifiedAt, forKey: .modifiedAt)
        try container.encodeIfPresent(dataSource, forKey: .dataSource)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(canonicalId, forKey: .canonicalId)
        try container.encodeIfPresent(sources, forKey: .sources)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(units, forKey: .units)
        try container.encodeIfPresent(isValid, forKey: .isValid)
        try container.encodeIfPresent(isReadOnly, forKey: .isReadOnly)
        try container.encodeIfPresent(identifier, forKey: .identifier)
        try container.encodeIfPresent(srvModified, forKey: .srvModified)
        try container.encodeIfPresent(srvCreated, forKey: .srvCreated)
        try container.encodeIfPresent(subject, forKey: .subject)
    }
}


extension Entry: Identifiable {}
