//
// ExtendedGlucoseAnalyticsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request model for extended glucose analytics with GMI, GRI, and clinical assessment */
public struct ExtendedGlucoseAnalyticsRequest: Sendable, Codable, Hashable {

    /** Collection of sensor glucose readings */
    public var entries: [SensorGlucose]?
    /** Optional collection of bolus deliveries */
    public var boluses: [Bolus]?
    /** Optional collection of carb intakes */
    public var carbIntakes: [CarbIntake]?
    /** Diabetes population type for clinical target assessment */
    public var population: DiabetesPopulation?
    /** Optional extended analysis configuration */
    public var config: ExtendedAnalysisConfig?

    public init(entries: [SensorGlucose]? = nil, boluses: [Bolus]? = nil, carbIntakes: [CarbIntake]? = nil, population: DiabetesPopulation? = nil, config: ExtendedAnalysisConfig? = nil) {
        self.entries = entries
        self.boluses = boluses
        self.carbIntakes = carbIntakes
        self.population = population
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entries
        case boluses
        case carbIntakes
        case population
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entries, forKey: .entries)
        try container.encodeIfPresent(boluses, forKey: .boluses)
        try container.encodeIfPresent(carbIntakes, forKey: .carbIntakes)
        try container.encodeIfPresent(population, forKey: .population)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

