//
// GlucoseProcessingSourceDefault.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GlucoseProcessingSourceDefault: Sendable, Codable, Hashable {

    public var match: String?
    public var field: String?
    public var processing: GlucoseProcessing?

    public init(match: String? = nil, field: String? = nil, processing: GlucoseProcessing? = nil) {
        self.match = match
        self.field = field
        self.processing = processing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case match
        case field
        case processing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(match, forKey: .match)
        try container.encodeIfPresent(field, forKey: .field)
        try container.encodeIfPresent(processing, forKey: .processing)
    }
}

