//
// GlucoseProcessing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum GlucoseProcessing: String, Sendable, Codable, CaseIterable {
    case smoothed = "Smoothed"
    case unsmoothed = "Unsmoothed"
}
