//
// GlucoseUnit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum GlucoseUnit: String, Sendable, Codable, CaseIterable {
    case mgDl = "MgDl"
    case mmol = "Mmol"
}
