//
// GlycemicVariability.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GlycemicVariability: Sendable, Codable, Hashable {

    public var coefficientOfVariation: Double?
    public var standardDeviation: Double?
    public var meanAmplitudeGlycemicExcursions: Double?
    public var continuousOverlappingNetGlycemicAction: Double?
    public var averageDailyRiskRange: Double?
    public var labilityIndex: Double?
    public var jIndex: Double?
    public var highBloodGlucoseIndex: Double?
    public var lowBloodGlucoseIndex: Double?
    public var glycemicVariabilityIndex: Double?
    public var patientGlycemicStatus: Double?
    public var estimatedA1c: Double?
    public var gmi: GlucoseManagementIndicator?
    public var meanTotalDailyChange: Double?
    public var timeInFluctuation: Double?

    public init(coefficientOfVariation: Double? = nil, standardDeviation: Double? = nil, meanAmplitudeGlycemicExcursions: Double? = nil, continuousOverlappingNetGlycemicAction: Double? = nil, averageDailyRiskRange: Double? = nil, labilityIndex: Double? = nil, jIndex: Double? = nil, highBloodGlucoseIndex: Double? = nil, lowBloodGlucoseIndex: Double? = nil, glycemicVariabilityIndex: Double? = nil, patientGlycemicStatus: Double? = nil, estimatedA1c: Double? = nil, gmi: GlucoseManagementIndicator? = nil, meanTotalDailyChange: Double? = nil, timeInFluctuation: Double? = nil) {
        self.coefficientOfVariation = coefficientOfVariation
        self.standardDeviation = standardDeviation
        self.meanAmplitudeGlycemicExcursions = meanAmplitudeGlycemicExcursions
        self.continuousOverlappingNetGlycemicAction = continuousOverlappingNetGlycemicAction
        self.averageDailyRiskRange = averageDailyRiskRange
        self.labilityIndex = labilityIndex
        self.jIndex = jIndex
        self.highBloodGlucoseIndex = highBloodGlucoseIndex
        self.lowBloodGlucoseIndex = lowBloodGlucoseIndex
        self.glycemicVariabilityIndex = glycemicVariabilityIndex
        self.patientGlycemicStatus = patientGlycemicStatus
        self.estimatedA1c = estimatedA1c
        self.gmi = gmi
        self.meanTotalDailyChange = meanTotalDailyChange
        self.timeInFluctuation = timeInFluctuation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case coefficientOfVariation
        case standardDeviation
        case meanAmplitudeGlycemicExcursions
        case continuousOverlappingNetGlycemicAction
        case averageDailyRiskRange
        case labilityIndex
        case jIndex
        case highBloodGlucoseIndex
        case lowBloodGlucoseIndex
        case glycemicVariabilityIndex
        case patientGlycemicStatus
        case estimatedA1c
        case gmi
        case meanTotalDailyChange
        case timeInFluctuation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(coefficientOfVariation, forKey: .coefficientOfVariation)
        try container.encodeIfPresent(standardDeviation, forKey: .standardDeviation)
        try container.encodeIfPresent(meanAmplitudeGlycemicExcursions, forKey: .meanAmplitudeGlycemicExcursions)
        try container.encodeIfPresent(continuousOverlappingNetGlycemicAction, forKey: .continuousOverlappingNetGlycemicAction)
        try container.encodeIfPresent(averageDailyRiskRange, forKey: .averageDailyRiskRange)
        try container.encodeIfPresent(labilityIndex, forKey: .labilityIndex)
        try container.encodeIfPresent(jIndex, forKey: .jIndex)
        try container.encodeIfPresent(highBloodGlucoseIndex, forKey: .highBloodGlucoseIndex)
        try container.encodeIfPresent(lowBloodGlucoseIndex, forKey: .lowBloodGlucoseIndex)
        try container.encodeIfPresent(glycemicVariabilityIndex, forKey: .glycemicVariabilityIndex)
        try container.encodeIfPresent(patientGlycemicStatus, forKey: .patientGlycemicStatus)
        try container.encodeIfPresent(estimatedA1c, forKey: .estimatedA1c)
        try container.encodeIfPresent(gmi, forKey: .gmi)
        try container.encodeIfPresent(meanTotalDailyChange, forKey: .meanTotalDailyChange)
        try container.encodeIfPresent(timeInFluctuation, forKey: .timeInFluctuation)
    }
}

