//
// GuestLinkCreationResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GuestLinkCreationResult: Sendable, Codable, Hashable {

    public var code: String?
    public var fullUrl: String?
    public var info: GuestLinkInfo?

    public init(code: String? = nil, fullUrl: String? = nil, info: GuestLinkInfo? = nil) {
        self.code = code
        self.fullUrl = fullUrl
        self.info = info
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case fullUrl
        case info
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(fullUrl, forKey: .fullUrl)
        try container.encodeIfPresent(info, forKey: .info)
    }
}

