//
// HaloDialPredictionCurve.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum HaloDialPredictionCurve: String, Sendable, Codable, CaseIterable {
    case main = "Main"
    case iob = "Iob"
    case uam = "Uam"
    case cob = "Cob"
    case zeroTemp = "ZeroTemp"
}
