//
// HaloDialConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HaloDialConfig: Sendable, Codable, Hashable {

    public var schemaVersion: Int?
    public var colorMode: HaloDialColorMode?
    public var historyMinutes: Int?
    public var predictionMinutes: Int?
    public var predictionCurve: HaloDialPredictionCurve?
    public var centerSub: HaloDialCenterSubElement?
    public var innerLeftArc: HaloDialArcElement?
    public var innerRightArc: HaloDialArcElement?
    public var iobMaxUnits: Double?
    public var cobMaxGrams: Double?
    public var corners: HaloDialCorners?
    public var elementConfig: [String: JSONValue]?

    public init(schemaVersion: Int? = nil, colorMode: HaloDialColorMode? = nil, historyMinutes: Int? = nil, predictionMinutes: Int? = nil, predictionCurve: HaloDialPredictionCurve? = nil, centerSub: HaloDialCenterSubElement? = nil, innerLeftArc: HaloDialArcElement? = nil, innerRightArc: HaloDialArcElement? = nil, iobMaxUnits: Double? = nil, cobMaxGrams: Double? = nil, corners: HaloDialCorners? = nil, elementConfig: [String: JSONValue]? = nil) {
        self.schemaVersion = schemaVersion
        self.colorMode = colorMode
        self.historyMinutes = historyMinutes
        self.predictionMinutes = predictionMinutes
        self.predictionCurve = predictionCurve
        self.centerSub = centerSub
        self.innerLeftArc = innerLeftArc
        self.innerRightArc = innerRightArc
        self.iobMaxUnits = iobMaxUnits
        self.cobMaxGrams = cobMaxGrams
        self.corners = corners
        self.elementConfig = elementConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion
        case colorMode
        case historyMinutes
        case predictionMinutes
        case predictionCurve
        case centerSub
        case innerLeftArc
        case innerRightArc
        case iobMaxUnits
        case cobMaxGrams
        case corners
        case elementConfig
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(colorMode, forKey: .colorMode)
        try container.encodeIfPresent(historyMinutes, forKey: .historyMinutes)
        try container.encodeIfPresent(predictionMinutes, forKey: .predictionMinutes)
        try container.encodeIfPresent(predictionCurve, forKey: .predictionCurve)
        try container.encodeIfPresent(centerSub, forKey: .centerSub)
        try container.encodeIfPresent(innerLeftArc, forKey: .innerLeftArc)
        try container.encodeIfPresent(innerRightArc, forKey: .innerRightArc)
        try container.encodeIfPresent(iobMaxUnits, forKey: .iobMaxUnits)
        try container.encodeIfPresent(cobMaxGrams, forKey: .cobMaxGrams)
        try container.encodeIfPresent(corners, forKey: .corners)
        try container.encodeIfPresent(elementConfig, forKey: .elementConfig)
    }
}

