//
// HaloDialColorMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum HaloDialColorMode: String, Sendable, Codable, CaseIterable {
    case discrete = "Discrete"
    case continuous = "Continuous"
}
