//
// HeartRate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HeartRate: Sendable, Codable, Hashable {

    public var id: String?
    public var createdAt: String?
    public var mills: Int64?
    public var utcOffset: Int?
    public var timestamp: Date?
    public var bpm: Int?
    public var accuracy: Int?
    public var device: String?
    public var enteredBy: String?
    public var dataSource: String?

    public init(id: String? = nil, createdAt: String? = nil, mills: Int64? = nil, utcOffset: Int? = nil, timestamp: Date? = nil, bpm: Int? = nil, accuracy: Int? = nil, device: String? = nil, enteredBy: String? = nil, dataSource: String? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.mills = mills
        self.utcOffset = utcOffset
        self.timestamp = timestamp
        self.bpm = bpm
        self.accuracy = accuracy
        self.device = device
        self.enteredBy = enteredBy
        self.dataSource = dataSource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case mills
        case utcOffset
        case timestamp
        case bpm
        case accuracy
        case device
        case enteredBy
        case dataSource = "data_source"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(mills, forKey: .mills)
        try container.encodeIfPresent(utcOffset, forKey: .utcOffset)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(bpm, forKey: .bpm)
        try container.encodeIfPresent(accuracy, forKey: .accuracy)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(enteredBy, forKey: .enteredBy)
        try container.encodeIfPresent(dataSource, forKey: .dataSource)
    }
}


extension HeartRate: Identifiable {}
