//
// HistoryExcursionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HistoryExcursionResponse: Sendable, Codable, Hashable {

    public var id: String?
    public var alertRuleId: String?
    public var ruleName: String?
    public var conditionType: AlertConditionType?
    public var startedAt: Date?
    public var endedAt: Date?
    public var acknowledgedAt: Date?
    public var acknowledgedBy: String?

    public init(id: String? = nil, alertRuleId: String? = nil, ruleName: String? = nil, conditionType: AlertConditionType? = nil, startedAt: Date? = nil, endedAt: Date? = nil, acknowledgedAt: Date? = nil, acknowledgedBy: String? = nil) {
        self.id = id
        self.alertRuleId = alertRuleId
        self.ruleName = ruleName
        self.conditionType = conditionType
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.acknowledgedAt = acknowledgedAt
        self.acknowledgedBy = acknowledgedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case alertRuleId
        case ruleName
        case conditionType
        case startedAt
        case endedAt
        case acknowledgedAt
        case acknowledgedBy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(alertRuleId, forKey: .alertRuleId)
        try container.encodeIfPresent(ruleName, forKey: .ruleName)
        try container.encodeIfPresent(conditionType, forKey: .conditionType)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(endedAt, forKey: .endedAt)
        try container.encodeIfPresent(acknowledgedAt, forKey: .acknowledgedAt)
        try container.encodeIfPresent(acknowledgedBy, forKey: .acknowledgedBy)
    }
}


extension HistoryExcursionResponse: Identifiable {}
