//
// InsulinDose.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InsulinDose: Sendable, Codable, Hashable {

    public var time: Date?
    public var units: Double?

    public init(time: Date? = nil, units: Double? = nil) {
        self.time = time
        self.units = units
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case units
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(units, forKey: .units)
    }
}

