//
// LoopProfileSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LoopProfileSettings: Sendable, Codable, Hashable {

    public var deviceToken: String?
    public var bundleIdentifier: String?
    public var overridePresets: [LoopOverridePreset]?
    public var dosingEnabled: Bool?
    public var minimumBGGuard: Double?
    public var preMealTargetRange: LoopTargetRange?
    public var workoutTargetRange: LoopTargetRange?
    public var maximumBolus: Double?
    public var maximumBasalRatePerHour: Double?
    public var dosingStrategy: String?
    public var scheduleOverride: LoopOverridePreset?

    public init(deviceToken: String? = nil, bundleIdentifier: String? = nil, overridePresets: [LoopOverridePreset]? = nil, dosingEnabled: Bool? = nil, minimumBGGuard: Double? = nil, preMealTargetRange: LoopTargetRange? = nil, workoutTargetRange: LoopTargetRange? = nil, maximumBolus: Double? = nil, maximumBasalRatePerHour: Double? = nil, dosingStrategy: String? = nil, scheduleOverride: LoopOverridePreset? = nil) {
        self.deviceToken = deviceToken
        self.bundleIdentifier = bundleIdentifier
        self.overridePresets = overridePresets
        self.dosingEnabled = dosingEnabled
        self.minimumBGGuard = minimumBGGuard
        self.preMealTargetRange = preMealTargetRange
        self.workoutTargetRange = workoutTargetRange
        self.maximumBolus = maximumBolus
        self.maximumBasalRatePerHour = maximumBasalRatePerHour
        self.dosingStrategy = dosingStrategy
        self.scheduleOverride = scheduleOverride
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceToken
        case bundleIdentifier
        case overridePresets
        case dosingEnabled
        case minimumBGGuard
        case preMealTargetRange
        case workoutTargetRange
        case maximumBolus
        case maximumBasalRatePerHour
        case dosingStrategy
        case scheduleOverride
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deviceToken, forKey: .deviceToken)
        try container.encodeIfPresent(bundleIdentifier, forKey: .bundleIdentifier)
        try container.encodeIfPresent(overridePresets, forKey: .overridePresets)
        try container.encodeIfPresent(dosingEnabled, forKey: .dosingEnabled)
        try container.encodeIfPresent(minimumBGGuard, forKey: .minimumBGGuard)
        try container.encodeIfPresent(preMealTargetRange, forKey: .preMealTargetRange)
        try container.encodeIfPresent(workoutTargetRange, forKey: .workoutTargetRange)
        try container.encodeIfPresent(maximumBolus, forKey: .maximumBolus)
        try container.encodeIfPresent(maximumBasalRatePerHour, forKey: .maximumBasalRatePerHour)
        try container.encodeIfPresent(dosingStrategy, forKey: .dosingStrategy)
        try container.encodeIfPresent(scheduleOverride, forKey: .scheduleOverride)
    }
}

