//
// ManualTestResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Result of manual API comparison test */
public struct ManualTestResult: Sendable, Codable, Hashable {

    /** The API path that was tested */
    public var queryPath: String?
    /** HTTP method used */
    public var method: String?
    /** When the test was performed */
    public var timestamp: Date?
    /** Raw JSON response from Nightscout */
    public var nightscoutResponse: String?
    /** Raw JSON response from Nocturne */
    public var nocturneResponse: String?
    /** HTTP status code from Nightscout */
    public var nightscoutStatusCode: Int?
    /** HTTP status code from Nocturne */
    public var nocturneStatusCode: Int?
    /** Response time from Nightscout in milliseconds */
    public var nightscoutResponseTimeMs: Int64?
    /** Response time from Nocturne in milliseconds */
    public var nocturneResponseTimeMs: Int64?
    /** Error message if Nightscout request failed */
    public var nightscoutError: String?
    /** Error message if Nocturne request failed */
    public var nocturneError: String?

    public init(queryPath: String? = nil, method: String? = nil, timestamp: Date? = nil, nightscoutResponse: String? = nil, nocturneResponse: String? = nil, nightscoutStatusCode: Int? = nil, nocturneStatusCode: Int? = nil, nightscoutResponseTimeMs: Int64? = nil, nocturneResponseTimeMs: Int64? = nil, nightscoutError: String? = nil, nocturneError: String? = nil) {
        self.queryPath = queryPath
        self.method = method
        self.timestamp = timestamp
        self.nightscoutResponse = nightscoutResponse
        self.nocturneResponse = nocturneResponse
        self.nightscoutStatusCode = nightscoutStatusCode
        self.nocturneStatusCode = nocturneStatusCode
        self.nightscoutResponseTimeMs = nightscoutResponseTimeMs
        self.nocturneResponseTimeMs = nocturneResponseTimeMs
        self.nightscoutError = nightscoutError
        self.nocturneError = nocturneError
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case queryPath
        case method
        case timestamp
        case nightscoutResponse
        case nocturneResponse
        case nightscoutStatusCode
        case nocturneStatusCode
        case nightscoutResponseTimeMs
        case nocturneResponseTimeMs
        case nightscoutError
        case nocturneError
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(queryPath, forKey: .queryPath)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(nightscoutResponse, forKey: .nightscoutResponse)
        try container.encodeIfPresent(nocturneResponse, forKey: .nocturneResponse)
        try container.encodeIfPresent(nightscoutStatusCode, forKey: .nightscoutStatusCode)
        try container.encodeIfPresent(nocturneStatusCode, forKey: .nocturneStatusCode)
        try container.encodeIfPresent(nightscoutResponseTimeMs, forKey: .nightscoutResponseTimeMs)
        try container.encodeIfPresent(nocturneResponseTimeMs, forKey: .nocturneResponseTimeMs)
        try container.encodeIfPresent(nightscoutError, forKey: .nightscoutError)
        try container.encodeIfPresent(nocturneError, forKey: .nocturneError)
    }
}

