//
// MemberInviteResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MemberInviteResult: Sendable, Codable, Hashable {

    public var id: String?
    public var token: String?
    public var inviteUrl: String?
    public var expiresAt: Date?

    public init(id: String? = nil, token: String? = nil, inviteUrl: String? = nil, expiresAt: Date? = nil) {
        self.id = id
        self.token = token
        self.inviteUrl = inviteUrl
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case token
        case inviteUrl
        case expiresAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(inviteUrl, forKey: .inviteUrl)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
    }
}


extension MemberInviteResult: Identifiable {}
