//
// NightDetectionResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NightDetectionResult: Sendable, Codable, Hashable {

    public var nightOf: String?
    public var suggestionsCreated: Int?

    public init(nightOf: String? = nil, suggestionsCreated: Int? = nil) {
        self.nightOf = nightOf
        self.suggestionsCreated = suggestionsCreated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nightOf
        case suggestionsCreated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nightOf, forKey: .nightOf)
        try container.encodeIfPresent(suggestionsCreated, forKey: .suggestionsCreated)
    }
}

