//
// NotificationCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum NotificationCategory: String, Sendable, Codable, CaseIterable {
    case informational = "Informational"
    case alert = "Alert"
    case actionRequired = "ActionRequired"
    case reminder = "Reminder"
}
