//
// OAuthError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** OAuth 2.0 error response (RFC 6749 Section 5.2) */
public struct OAuthError: Sendable, Codable, Hashable {

    /** Error code as defined in RFC 6749 Section 5.2 (e.g. \"invalid_grant\", \"invalid_client\"). */
    public var error: String?
    /** Human-readable description of the error. */
    public var errorDescription: String?
    /** URI pointing to a page with more information about the error. */
    public var errorUri: String?

    public init(error: String? = nil, errorDescription: String? = nil, errorUri: String? = nil) {
        self.error = error
        self.errorDescription = errorDescription
        self.errorUri = errorUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case errorDescription = "error_description"
        case errorUri = "error_uri"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(errorDescription, forKey: .errorDescription)
        try container.encodeIfPresent(errorUri, forKey: .errorUri)
    }
}

