//
// PaginatedResponseOfPumpSnapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedResponseOfPumpSnapshot: Sendable, Codable, Hashable {

    public var data: [PumpSnapshot]?
    public var pagination: PaginationInfo?

    public init(data: [PumpSnapshot]? = nil, pagination: PaginationInfo? = nil) {
        self.data = data
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

