//
// PatientInsulin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PatientInsulin: Sendable, Codable, Hashable {

    public var id: String?
    public var insulinCategory: InsulinCategory?
    public var name: String?
    public var startDate: Date?
    public var endDate: Date?
    public var isCurrent: Bool?
    public var notes: String?
    public var formulationId: String?
    public var dia: Double?
    public var peak: Int?
    public var curve: String?
    public var concentration: Int?
    public var role: InsulinRole?
    public var isPrimary: Bool?
    public var createdAt: Date?
    public var modifiedAt: Date?

    public init(id: String? = nil, insulinCategory: InsulinCategory? = nil, name: String? = nil, startDate: Date? = nil, endDate: Date? = nil, isCurrent: Bool? = nil, notes: String? = nil, formulationId: String? = nil, dia: Double? = nil, peak: Int? = nil, curve: String? = nil, concentration: Int? = nil, role: InsulinRole? = nil, isPrimary: Bool? = nil, createdAt: Date? = nil, modifiedAt: Date? = nil) {
        self.id = id
        self.insulinCategory = insulinCategory
        self.name = name
        self.startDate = startDate
        self.endDate = endDate
        self.isCurrent = isCurrent
        self.notes = notes
        self.formulationId = formulationId
        self.dia = dia
        self.peak = peak
        self.curve = curve
        self.concentration = concentration
        self.role = role
        self.isPrimary = isPrimary
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case insulinCategory
        case name
        case startDate
        case endDate
        case isCurrent
        case notes
        case formulationId
        case dia
        case peak
        case curve
        case concentration
        case role
        case isPrimary
        case createdAt
        case modifiedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(insulinCategory, forKey: .insulinCategory)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(isCurrent, forKey: .isCurrent)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(formulationId, forKey: .formulationId)
        try container.encodeIfPresent(dia, forKey: .dia)
        try container.encodeIfPresent(peak, forKey: .peak)
        try container.encodeIfPresent(curve, forKey: .curve)
        try container.encodeIfPresent(concentration, forKey: .concentration)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(isPrimary, forKey: .isPrimary)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(modifiedAt, forKey: .modifiedAt)
    }
}


extension PatientInsulin: Identifiable {}
