//
// PredictionSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PredictionSettings: Sendable, Codable, Hashable {

    public var enabled: Bool?
    public var minutes: Int?
    public var model: String?

    public init(enabled: Bool? = nil, minutes: Int? = nil, model: String? = nil) {
        self.enabled = enabled
        self.minutes = minutes
        self.model = model
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case minutes
        case model
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(minutes, forKey: .minutes)
        try container.encodeIfPresent(model, forKey: .model)
    }
}

