//
// ProfileSnapshotSegment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One flat segment of the resolved profile: all scalars are constant over [start, end). */
public struct ProfileSnapshotSegment: Sendable, Codable, Hashable {

    /** Segment start (Unix ms, inclusive). */
    public var startMills: Int64?
    /** Segment end (Unix ms, exclusive). */
    public var endMills: Int64?
    /** Duration of insulin action (hours). */
    public var dia: Double?
    /** Scheduled basal rate (U/hr). */
    public var basal: Double?
    /** Insulin sensitivity (mg/dL per U). */
    public var sens: Double?
    /** Carb ratio (g/U). */
    public var carbRatio: Double?
    /** Low BG target (mg/dL). */
    public var minBg: Double?
    /** High BG target (mg/dL). */
    public var maxBg: Double?
    /** Insulin activity peak (minutes). */
    public var peak: Int?
    /** Insulin activity curve model name (e.g. \"rapid-acting\"). */
    public var curve: String?

    public init(startMills: Int64? = nil, endMills: Int64? = nil, dia: Double? = nil, basal: Double? = nil, sens: Double? = nil, carbRatio: Double? = nil, minBg: Double? = nil, maxBg: Double? = nil, peak: Int? = nil, curve: String? = nil) {
        self.startMills = startMills
        self.endMills = endMills
        self.dia = dia
        self.basal = basal
        self.sens = sens
        self.carbRatio = carbRatio
        self.minBg = minBg
        self.maxBg = maxBg
        self.peak = peak
        self.curve = curve
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startMills = "start_mills"
        case endMills = "end_mills"
        case dia
        case basal
        case sens
        case carbRatio = "carb_ratio"
        case minBg = "min_bg"
        case maxBg = "max_bg"
        case peak
        case curve
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startMills, forKey: .startMills)
        try container.encodeIfPresent(endMills, forKey: .endMills)
        try container.encodeIfPresent(dia, forKey: .dia)
        try container.encodeIfPresent(basal, forKey: .basal)
        try container.encodeIfPresent(sens, forKey: .sens)
        try container.encodeIfPresent(carbRatio, forKey: .carbRatio)
        try container.encodeIfPresent(minBg, forKey: .minBg)
        try container.encodeIfPresent(maxBg, forKey: .maxBg)
        try container.encodeIfPresent(peak, forKey: .peak)
        try container.encodeIfPresent(curve, forKey: .curve)
    }
}

