//
// ProfileData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProfileData: Sendable, Codable, Hashable {

    public var dia: Double?
    public var carbsHr: Int?
    public var delay: Int?
    public var timezone: String?
    public var units: String?
    public var perGIvalues: Bool?
    public var carbsHrHigh: Int?
    public var carbsHrMedium: Int?
    public var carbsHrLow: Int?
    public var delayHigh: Int?
    public var delayMedium: Int?
    public var delayLow: Int?
    public var basal: [TimeValue]?
    public var carbratio: [TimeValue]?
    public var sens: [TimeValue]?
    public var targetLow: [TimeValue]?
    public var targetHigh: [TimeValue]?

    public init(dia: Double? = nil, carbsHr: Int? = nil, delay: Int? = nil, timezone: String? = nil, units: String? = nil, perGIvalues: Bool? = nil, carbsHrHigh: Int? = nil, carbsHrMedium: Int? = nil, carbsHrLow: Int? = nil, delayHigh: Int? = nil, delayMedium: Int? = nil, delayLow: Int? = nil, basal: [TimeValue]? = nil, carbratio: [TimeValue]? = nil, sens: [TimeValue]? = nil, targetLow: [TimeValue]? = nil, targetHigh: [TimeValue]? = nil) {
        self.dia = dia
        self.carbsHr = carbsHr
        self.delay = delay
        self.timezone = timezone
        self.units = units
        self.perGIvalues = perGIvalues
        self.carbsHrHigh = carbsHrHigh
        self.carbsHrMedium = carbsHrMedium
        self.carbsHrLow = carbsHrLow
        self.delayHigh = delayHigh
        self.delayMedium = delayMedium
        self.delayLow = delayLow
        self.basal = basal
        self.carbratio = carbratio
        self.sens = sens
        self.targetLow = targetLow
        self.targetHigh = targetHigh
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dia
        case carbsHr = "carbs_hr"
        case delay
        case timezone
        case units
        case perGIvalues
        case carbsHrHigh = "carbs_hr_high"
        case carbsHrMedium = "carbs_hr_medium"
        case carbsHrLow = "carbs_hr_low"
        case delayHigh = "delay_high"
        case delayMedium = "delay_medium"
        case delayLow = "delay_low"
        case basal
        case carbratio
        case sens
        case targetLow = "target_low"
        case targetHigh = "target_high"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dia, forKey: .dia)
        try container.encodeIfPresent(carbsHr, forKey: .carbsHr)
        try container.encodeIfPresent(delay, forKey: .delay)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(units, forKey: .units)
        try container.encodeIfPresent(perGIvalues, forKey: .perGIvalues)
        try container.encodeIfPresent(carbsHrHigh, forKey: .carbsHrHigh)
        try container.encodeIfPresent(carbsHrMedium, forKey: .carbsHrMedium)
        try container.encodeIfPresent(carbsHrLow, forKey: .carbsHrLow)
        try container.encodeIfPresent(delayHigh, forKey: .delayHigh)
        try container.encodeIfPresent(delayMedium, forKey: .delayMedium)
        try container.encodeIfPresent(delayLow, forKey: .delayLow)
        try container.encodeIfPresent(basal, forKey: .basal)
        try container.encodeIfPresent(carbratio, forKey: .carbratio)
        try container.encodeIfPresent(sens, forKey: .sens)
        try container.encodeIfPresent(targetLow, forKey: .targetLow)
        try container.encodeIfPresent(targetHigh, forKey: .targetHigh)
    }
}

