//
// PunchCardMonth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PunchCardMonth: Sendable, Codable, Hashable {

    public var year: Int?
    public var month: Int?
    public var monthName: String?
    public var days: [PunchCardDay]?
    public var maxCarbs: Double?
    public var maxInsulin: Double?
    public var maxCarbInsulinDiff: Double?
    public var totalReadings: Int?
    public var summary: PunchCardMonthSummary?

    public init(year: Int? = nil, month: Int? = nil, monthName: String? = nil, days: [PunchCardDay]? = nil, maxCarbs: Double? = nil, maxInsulin: Double? = nil, maxCarbInsulinDiff: Double? = nil, totalReadings: Int? = nil, summary: PunchCardMonthSummary? = nil) {
        self.year = year
        self.month = month
        self.monthName = monthName
        self.days = days
        self.maxCarbs = maxCarbs
        self.maxInsulin = maxInsulin
        self.maxCarbInsulinDiff = maxCarbInsulinDiff
        self.totalReadings = totalReadings
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
        case month
        case monthName
        case days
        case maxCarbs
        case maxInsulin
        case maxCarbInsulinDiff
        case totalReadings
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(month, forKey: .month)
        try container.encodeIfPresent(monthName, forKey: .monthName)
        try container.encodeIfPresent(days, forKey: .days)
        try container.encodeIfPresent(maxCarbs, forKey: .maxCarbs)
        try container.encodeIfPresent(maxInsulin, forKey: .maxInsulin)
        try container.encodeIfPresent(maxCarbInsulinDiff, forKey: .maxCarbInsulinDiff)
        try container.encodeIfPresent(totalReadings, forKey: .totalReadings)
        try container.encodeIfPresent(summary, forKey: .summary)
    }
}

