//
// ReadAccessAuditDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReadAccessAuditDto: Sendable, Codable, Hashable {

    public var id: String?
    public var createdAt: Date?
    public var endpoint: String?
    public var entityType: String?
    public var recordCount: Int?
    public var statusCode: Int?
    public var queryParameters: String?
    public var subjectId: String?
    public var subjectName: String?
    public var authType: String?
    public var ipAddress: String?
    public var apiSecretHashPrefix: String?

    public init(id: String? = nil, createdAt: Date? = nil, endpoint: String? = nil, entityType: String? = nil, recordCount: Int? = nil, statusCode: Int? = nil, queryParameters: String? = nil, subjectId: String? = nil, subjectName: String? = nil, authType: String? = nil, ipAddress: String? = nil, apiSecretHashPrefix: String? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.endpoint = endpoint
        self.entityType = entityType
        self.recordCount = recordCount
        self.statusCode = statusCode
        self.queryParameters = queryParameters
        self.subjectId = subjectId
        self.subjectName = subjectName
        self.authType = authType
        self.ipAddress = ipAddress
        self.apiSecretHashPrefix = apiSecretHashPrefix
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case endpoint
        case entityType
        case recordCount
        case statusCode
        case queryParameters
        case subjectId
        case subjectName
        case authType
        case ipAddress
        case apiSecretHashPrefix
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(endpoint, forKey: .endpoint)
        try container.encodeIfPresent(entityType, forKey: .entityType)
        try container.encodeIfPresent(recordCount, forKey: .recordCount)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(queryParameters, forKey: .queryParameters)
        try container.encodeIfPresent(subjectId, forKey: .subjectId)
        try container.encodeIfPresent(subjectName, forKey: .subjectName)
        try container.encodeIfPresent(authType, forKey: .authType)
        try container.encodeIfPresent(ipAddress, forKey: .ipAddress)
        try container.encodeIfPresent(apiSecretHashPrefix, forKey: .apiSecretHashPrefix)
    }
}


extension ReadAccessAuditDto: Identifiable {}
