//
// RecordType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum RecordType: String, Sendable, Codable, CaseIterable {
    case entry = "Entry"
    case treatment = "Treatment"
    case stateSpan = "StateSpan"
    case sensorGlucose = "SensorGlucose"
    case bolus = "Bolus"
    case carbIntake = "CarbIntake"
    case bgcheck = "BGCheck"
    case deviceEvent = "DeviceEvent"
    case note = "Note"
    case bolusCalculation = "BolusCalculation"
    case tempBasal = "TempBasal"
}
