//
// ReservoirEstimateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The current reservoir level resolved by IReservoirEstimationService. Found is false when no snapshot in the estimation window carries a reservoir value; the remaining fields are then unset. */
public struct ReservoirEstimateResponse: Sendable, Codable, Hashable {

    /** Whether an estimate could be resolved. */
    public var found: Bool?
    /** Remaining insulin in units. Null when Found is false. */
    public var units: Double?
    /** True when the value only proves the reservoir holds at least this much             (capped reading like \"50+\", or a bound overriding a lower estimate). */
    public var isLowerBound: Bool?
    /** True when the value was projected from an older reading rather than             taken directly from the newest snapshot. */
    public var isEstimated: Bool?

    public init(found: Bool? = nil, units: Double? = nil, isLowerBound: Bool? = nil, isEstimated: Bool? = nil) {
        self.found = found
        self.units = units
        self.isLowerBound = isLowerBound
        self.isEstimated = isEstimated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case found
        case units
        case isLowerBound
        case isEstimated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(found, forKey: .found)
        try container.encodeIfPresent(units, forKey: .units)
        try container.encodeIfPresent(isLowerBound, forKey: .isLowerBound)
        try container.encodeIfPresent(isEstimated, forKey: .isEstimated)
    }
}

