//
// ResolutionConditions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResolutionConditions: Sendable, Codable, Hashable {

    public var expiresAt: Date?
    public var sourceDeletedType: String?
    public var glucose: GlucoseCondition?

    public init(expiresAt: Date? = nil, sourceDeletedType: String? = nil, glucose: GlucoseCondition? = nil) {
        self.expiresAt = expiresAt
        self.sourceDeletedType = sourceDeletedType
        self.glucose = glucose
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expiresAt
        case sourceDeletedType
        case glucose
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(sourceDeletedType, forKey: .sourceDeletedType)
        try container.encodeIfPresent(glucose, forKey: .glucose)
    }
}

