//
// RetrospectiveTimelineResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response for retrospective timeline */
public struct RetrospectiveTimelineResponse: Sendable, Codable, Hashable {

    public var date: String?
    public var startTime: Int64?
    public var endTime: Int64?
    public var intervalMinutes: Int?
    public var totalPoints: Int?
    public var data: [RetrospectiveDataPoint]?

    public init(date: String? = nil, startTime: Int64? = nil, endTime: Int64? = nil, intervalMinutes: Int? = nil, totalPoints: Int? = nil, data: [RetrospectiveDataPoint]? = nil) {
        self.date = date
        self.startTime = startTime
        self.endTime = endTime
        self.intervalMinutes = intervalMinutes
        self.totalPoints = totalPoints
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case startTime
        case endTime
        case intervalMinutes
        case totalPoints
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(endTime, forKey: .endTime)
        try container.encodeIfPresent(intervalMinutes, forKey: .intervalMinutes)
        try container.encodeIfPresent(totalPoints, forKey: .totalPoints)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

