//
// RevokeOthersResultDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Result of POST /api/v4/account/sessions/revoke-others. */
public struct RevokeOthersResultDto: Sendable, Codable, Hashable {

    public var revokedTokenCount: Int?

    public init(revokedTokenCount: Int? = nil) {
        self.revokedTokenCount = revokedTokenCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case revokedTokenCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(revokedTokenCount, forKey: .revokedTokenCount)
    }
}

