//
// ScheduleChangeInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScheduleChangeInfo: Sendable, Codable, Hashable {

    public var changedDuringPeriod: Bool?
    public var lastChangedAt: Date?
    public var changeCount: Int?

    public init(changedDuringPeriod: Bool? = nil, lastChangedAt: Date? = nil, changeCount: Int? = nil) {
        self.changedDuringPeriod = changedDuringPeriod
        self.lastChangedAt = lastChangedAt
        self.changeCount = changeCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case changedDuringPeriod
        case lastChangedAt
        case changeCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(changedDuringPeriod, forKey: .changedDuringPeriod)
        try container.encodeIfPresent(lastChangedAt, forKey: .lastChangedAt)
        try container.encodeIfPresent(changeCount, forKey: .changeCount)
    }
}

