//
// SetActiveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetActiveRequest: Sendable, Codable, Hashable {

    public var isActive: Bool?

    public init(isActive: Bool? = nil) {
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isActive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isActive, forKey: .isActive)
    }
}

