//
// SetGlucoseProcessingPreferenceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetGlucoseProcessingPreferenceRequest: Sendable, Codable, Hashable {

    public var preferredGlucoseProcessing: String?

    public init(preferredGlucoseProcessing: String? = nil) {
        self.preferredGlucoseProcessing = preferredGlucoseProcessing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case preferredGlucoseProcessing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(preferredGlucoseProcessing, forKey: .preferredGlucoseProcessing)
    }
}

