//
// SetupOwnerOidcResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetupOwnerOidcResponse: Sendable, Codable, Hashable {

    public var authorizationUrl: String?

    public init(authorizationUrl: String? = nil) {
        self.authorizationUrl = authorizationUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case authorizationUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(authorizationUrl, forKey: .authorizationUrl)
    }
}

