//
// ShareLinkDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Current state of a tenant&#39;s single public share link. */
public struct ShareLinkDto: Sendable, Codable, Hashable {

    /** Whether a public share link is currently active. */
    public var enabled: Bool?
    /** The full share URL when enabled; null otherwise. The raw token is never returned separately. */
    public var url: String?
    /** When true the public view shows full history; when false, only the last 24 hours. */
    public var fullHistory: Bool?
    /** The data categories anonymous viewers can see, as read-permission atoms (e.g. glucose.read). A subset of PublicShareScopes. Empty means the link is live but nothing is shared yet. */
    public var scopes: [String]?
    /** When the share link was last accessed, or null if never (or not yet recorded). */
    public var lastAccessedAt: Date?

    public init(enabled: Bool? = nil, url: String? = nil, fullHistory: Bool? = nil, scopes: [String]? = nil, lastAccessedAt: Date? = nil) {
        self.enabled = enabled
        self.url = url
        self.fullHistory = fullHistory
        self.scopes = scopes
        self.lastAccessedAt = lastAccessedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case url
        case fullHistory
        case scopes
        case lastAccessedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(fullHistory, forKey: .fullHistory)
        try container.encodeIfPresent(scopes, forKey: .scopes)
        try container.encodeIfPresent(lastAccessedAt, forKey: .lastAccessedAt)
    }
}

