//
// SiteChangeImpactRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request model for site change impact analysis */
public struct SiteChangeImpactRequest: Sendable, Codable, Hashable {

    /** Collection of sensor glucose readings */
    public var entries: [SensorGlucose]?
    /** Collection of device events (must include site changes) */
    public var deviceEvents: [DeviceEvent]?
    /** Hours before site change to analyze (default: 12) */
    public var hoursBeforeChange: Int?
    /** Hours after site change to analyze (default: 24) */
    public var hoursAfterChange: Int?
    /** Time bucket size for averaging in minutes (default: 30) */
    public var bucketSizeMinutes: Int?

    public init(entries: [SensorGlucose]? = nil, deviceEvents: [DeviceEvent]? = nil, hoursBeforeChange: Int? = nil, hoursAfterChange: Int? = nil, bucketSizeMinutes: Int? = nil) {
        self.entries = entries
        self.deviceEvents = deviceEvents
        self.hoursBeforeChange = hoursBeforeChange
        self.hoursAfterChange = hoursAfterChange
        self.bucketSizeMinutes = bucketSizeMinutes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entries
        case deviceEvents
        case hoursBeforeChange
        case hoursAfterChange
        case bucketSizeMinutes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entries, forKey: .entries)
        try container.encodeIfPresent(deviceEvents, forKey: .deviceEvents)
        try container.encodeIfPresent(hoursBeforeChange, forKey: .hoursBeforeChange)
        try container.encodeIfPresent(hoursAfterChange, forKey: .hoursAfterChange)
        try container.encodeIfPresent(bucketSizeMinutes, forKey: .bucketSizeMinutes)
    }
}

