//
// SleepStageInterval.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SleepStageInterval: Sendable, Codable, Hashable {

    public var startTime: Date?
    public var endTime: Date?
    public var stage: SleepStageType?
    public var ordinal: Int?

    public init(startTime: Date? = nil, endTime: Date? = nil, stage: SleepStageType? = nil, ordinal: Int? = nil) {
        self.startTime = startTime
        self.endTime = endTime
        self.stage = stage
        self.ordinal = ordinal
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startTime
        case endTime
        case stage
        case ordinal
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(endTime, forKey: .endTime)
        try container.encodeIfPresent(stage, forKey: .stage)
        try container.encodeIfPresent(ordinal, forKey: .ordinal)
    }
}

