//
// SleepDetectionMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum SleepDetectionMethod: String, Sendable, Codable, CaseIterable {
    case auto = "Auto"
    case manual = "Manual"
    case autoTentative = "AutoTentative"
    case autoFinal = "AutoFinal"
    case enhanced = "Enhanced"
    case enhancedFinal = "EnhancedFinal"
    case device = "Device"
    case unknown = "Unknown"
}
