//
// SleepTrendsReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SleepTrendsReport: Sendable, Codable, Hashable {

    public var nights: [SleepNightSummary]?
    public var weeks: [SleepWeekSummary]?
    public var summary: SleepTrendsSummary?

    public init(nights: [SleepNightSummary]? = nil, weeks: [SleepWeekSummary]? = nil, summary: SleepTrendsSummary? = nil) {
        self.nights = nights
        self.weeks = weeks
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nights
        case weeks
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nights, forKey: .nights)
        try container.encodeIfPresent(weeks, forKey: .weeks)
        try container.encodeIfPresent(summary, forKey: .summary)
    }
}

