//
// SleepSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum SleepSource: String, Sendable, Codable, CaseIterable {
    case apple = "Apple"
    case google = "Google"
    case fitbit = "Fitbit"
    case oura = "Oura"
    case garmin = "Garmin"
    case samsung = "Samsung"
    case manual = "Manual"
}
