//
// StartMigrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Parameters for starting a new data migration from Nightscout or MongoDB. */
public struct StartMigrationRequest: Sendable, Codable, Hashable {

    public var mode: MigrationMode?
    /** Nightscout URL (for API mode) */
    public var nightscoutUrl: String?
    /** Nightscout API secret (for API mode) */
    public var nightscoutApiSecret: String?
    /** MongoDB connection string (for MongoDB mode) */
    public var mongoConnectionString: String?
    /** MongoDB database name (for MongoDB mode) */
    public var mongoDatabaseName: String?
    /** Collections to migrate. Empty means all. */
    public var collections: [String]?
    /** Start date for migration (optional) */
    public var startDate: Date?
    /** End date for migration (optional) */
    public var endDate: Date?

    public init(mode: MigrationMode? = nil, nightscoutUrl: String? = nil, nightscoutApiSecret: String? = nil, mongoConnectionString: String? = nil, mongoDatabaseName: String? = nil, collections: [String]? = nil, startDate: Date? = nil, endDate: Date? = nil) {
        self.mode = mode
        self.nightscoutUrl = nightscoutUrl
        self.nightscoutApiSecret = nightscoutApiSecret
        self.mongoConnectionString = mongoConnectionString
        self.mongoDatabaseName = mongoDatabaseName
        self.collections = collections
        self.startDate = startDate
        self.endDate = endDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mode
        case nightscoutUrl
        case nightscoutApiSecret
        case mongoConnectionString
        case mongoDatabaseName
        case collections
        case startDate
        case endDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mode, forKey: .mode)
        try container.encodeIfPresent(nightscoutUrl, forKey: .nightscoutUrl)
        try container.encodeIfPresent(nightscoutApiSecret, forKey: .nightscoutApiSecret)
        try container.encodeIfPresent(mongoConnectionString, forKey: .mongoConnectionString)
        try container.encodeIfPresent(mongoDatabaseName, forKey: .mongoDatabaseName)
        try container.encodeIfPresent(collections, forKey: .collections)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
    }
}

