//
// StatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StatusResponse: Sendable, Codable, Hashable {

    public var status: String?
    public var name: String?
    public var version: String?
    public var apiVersion: String?
    public var serverTime: Date?
    public var serverTimeEpoch: Int64?
    public var enabled: [String]?
    public var apiEnabled: Bool?
    public var roles: [String]?
    public var settings: [String: JSONValue]?
    public var extendedSettings: [String: JSONValue]?
    public var careportalEnabled: Bool?
    public var boluscalcEnabled: Bool?
    public var authorized: JSONValue?
    public var runtimeState: String?
    public var head: String?
    public var build: String?
    public var isDemo: Bool?
    public var nextResetAt: Date?
    public var anonymousReadAccess: Bool?

    public init(status: String? = nil, name: String? = nil, version: String? = nil, apiVersion: String? = nil, serverTime: Date? = nil, serverTimeEpoch: Int64? = nil, enabled: [String]? = nil, apiEnabled: Bool? = nil, roles: [String]? = nil, settings: [String: JSONValue]? = nil, extendedSettings: [String: JSONValue]? = nil, careportalEnabled: Bool? = nil, boluscalcEnabled: Bool? = nil, authorized: JSONValue? = nil, runtimeState: String? = nil, head: String? = nil, build: String? = nil, isDemo: Bool? = nil, nextResetAt: Date? = nil, anonymousReadAccess: Bool? = nil) {
        self.status = status
        self.name = name
        self.version = version
        self.apiVersion = apiVersion
        self.serverTime = serverTime
        self.serverTimeEpoch = serverTimeEpoch
        self.enabled = enabled
        self.apiEnabled = apiEnabled
        self.roles = roles
        self.settings = settings
        self.extendedSettings = extendedSettings
        self.careportalEnabled = careportalEnabled
        self.boluscalcEnabled = boluscalcEnabled
        self.authorized = authorized
        self.runtimeState = runtimeState
        self.head = head
        self.build = build
        self.isDemo = isDemo
        self.nextResetAt = nextResetAt
        self.anonymousReadAccess = anonymousReadAccess
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case name
        case version
        case apiVersion
        case serverTime
        case serverTimeEpoch
        case enabled
        case apiEnabled
        case roles
        case settings
        case extendedSettings
        case careportalEnabled
        case boluscalcEnabled
        case authorized
        case runtimeState
        case head
        case build
        case isDemo
        case nextResetAt
        case anonymousReadAccess
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(apiVersion, forKey: .apiVersion)
        try container.encodeIfPresent(serverTime, forKey: .serverTime)
        try container.encodeIfPresent(serverTimeEpoch, forKey: .serverTimeEpoch)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(apiEnabled, forKey: .apiEnabled)
        try container.encodeIfPresent(roles, forKey: .roles)
        try container.encodeIfPresent(settings, forKey: .settings)
        try container.encodeIfPresent(extendedSettings, forKey: .extendedSettings)
        try container.encodeIfPresent(careportalEnabled, forKey: .careportalEnabled)
        try container.encodeIfPresent(boluscalcEnabled, forKey: .boluscalcEnabled)
        try container.encodeIfPresent(authorized, forKey: .authorized)
        try container.encodeIfPresent(runtimeState, forKey: .runtimeState)
        try container.encodeIfPresent(head, forKey: .head)
        try container.encodeIfPresent(build, forKey: .build)
        try container.encodeIfPresent(isDemo, forKey: .isDemo)
        try container.encodeIfPresent(nextResetAt, forKey: .nextResetAt)
        try container.encodeIfPresent(anonymousReadAccess, forKey: .anonymousReadAccess)
    }
}

