//
// SubjectCredentialsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SubjectCredentialsDto: Sendable, Codable, Hashable {

    public var passkeys: [PasskeyCredentialDto]?
    public var oidcIdentities: [OidcIdentityDto]?

    public init(passkeys: [PasskeyCredentialDto]? = nil, oidcIdentities: [OidcIdentityDto]? = nil) {
        self.passkeys = passkeys
        self.oidcIdentities = oidcIdentities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passkeys
        case oidcIdentities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(passkeys, forKey: .passkeys)
        try container.encodeIfPresent(oidcIdentities, forKey: .oidcIdentities)
    }
}

