//
// SuggestedMealMatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A suggested meal match between a food entry and treatment */
public struct SuggestedMealMatch: Sendable, Codable, Hashable {

    public var foodEntryId: String?
    public var foodName: String?
    public var mealName: String?
    public var carbs: Double?
    public var consumedAt: Date?
    public var treatmentId: String?
    public var treatmentCarbs: Double?
    public var treatmentMills: Int64?
    public var matchScore: Double?

    public init(foodEntryId: String? = nil, foodName: String? = nil, mealName: String? = nil, carbs: Double? = nil, consumedAt: Date? = nil, treatmentId: String? = nil, treatmentCarbs: Double? = nil, treatmentMills: Int64? = nil, matchScore: Double? = nil) {
        self.foodEntryId = foodEntryId
        self.foodName = foodName
        self.mealName = mealName
        self.carbs = carbs
        self.consumedAt = consumedAt
        self.treatmentId = treatmentId
        self.treatmentCarbs = treatmentCarbs
        self.treatmentMills = treatmentMills
        self.matchScore = matchScore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case foodEntryId
        case foodName
        case mealName
        case carbs
        case consumedAt
        case treatmentId
        case treatmentCarbs
        case treatmentMills
        case matchScore
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(foodEntryId, forKey: .foodEntryId)
        try container.encodeIfPresent(foodName, forKey: .foodName)
        try container.encodeIfPresent(mealName, forKey: .mealName)
        try container.encodeIfPresent(carbs, forKey: .carbs)
        try container.encodeIfPresent(consumedAt, forKey: .consumedAt)
        try container.encodeIfPresent(treatmentId, forKey: .treatmentId)
        try container.encodeIfPresent(treatmentCarbs, forKey: .treatmentCarbs)
        try container.encodeIfPresent(treatmentMills, forKey: .treatmentMills)
        try container.encodeIfPresent(matchScore, forKey: .matchScore)
    }
}

