//
// SupportChannelConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SupportChannelConfig: Sendable, Codable, Hashable {

    public var mode: String?
    public var url: String?
    public var label: String?

    public init(mode: String? = nil, url: String? = nil, label: String? = nil) {
        self.mode = mode
        self.url = url
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mode
        case url
        case label
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mode, forKey: .mode)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(label, forKey: .label)
    }
}

