//
// SystemEventsGetSystemEventsCategoryParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SystemEventsGetSystemEventsCategoryParameter: Sendable, Codable, Hashable {
    case typeSystemEventCategory(SystemEventCategory)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeSystemEventCategory(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(SystemEventCategory.self) {
            self = .typeSystemEventCategory(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of SystemEventsGetSystemEventsCategoryParameter"))
        }
    }
}

