//
// SystemEventsGetSystemEventsTypeParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SystemEventsGetSystemEventsTypeParameter: Sendable, Codable, Hashable {
    case typeSystemEventType(SystemEventType)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeSystemEventType(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(SystemEventType.self) {
            self = .typeSystemEventType(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of SystemEventsGetSystemEventsTypeParameter"))
        }
    }
}

