//
// TargetAssessment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TargetAssessment: Sendable, Codable, Hashable {

    public var metricName: String?
    public var currentValue: Double?
    public var targetValue: Double?
    public var isMaximumTarget: Bool?
    public var status: TargetStatus?
    public var differenceFromTarget: Double?
    public var progressPercentage: Double?

    public init(metricName: String? = nil, currentValue: Double? = nil, targetValue: Double? = nil, isMaximumTarget: Bool? = nil, status: TargetStatus? = nil, differenceFromTarget: Double? = nil, progressPercentage: Double? = nil) {
        self.metricName = metricName
        self.currentValue = currentValue
        self.targetValue = targetValue
        self.isMaximumTarget = isMaximumTarget
        self.status = status
        self.differenceFromTarget = differenceFromTarget
        self.progressPercentage = progressPercentage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metricName
        case currentValue
        case targetValue
        case isMaximumTarget
        case status
        case differenceFromTarget
        case progressPercentage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metricName, forKey: .metricName)
        try container.encodeIfPresent(currentValue, forKey: .currentValue)
        try container.encodeIfPresent(targetValue, forKey: .targetValue)
        try container.encodeIfPresent(isMaximumTarget, forKey: .isMaximumTarget)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(differenceFromTarget, forKey: .differenceFromTarget)
        try container.encodeIfPresent(progressPercentage, forKey: .progressPercentage)
    }
}

