//
// TenantRoleDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TenantRoleDto: Sendable, Codable, Hashable {

    public var id: String?
    public var name: String?
    public var slug: String?
    public var description: String?
    public var permissions: [String]?
    public var isSystem: Bool?
    public var memberCount: Int?
    public var sysCreatedAt: Date?

    public init(id: String? = nil, name: String? = nil, slug: String? = nil, description: String? = nil, permissions: [String]? = nil, isSystem: Bool? = nil, memberCount: Int? = nil, sysCreatedAt: Date? = nil) {
        self.id = id
        self.name = name
        self.slug = slug
        self.description = description
        self.permissions = permissions
        self.isSystem = isSystem
        self.memberCount = memberCount
        self.sysCreatedAt = sysCreatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case slug
        case description
        case permissions
        case isSystem
        case memberCount
        case sysCreatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(permissions, forKey: .permissions)
        try container.encodeIfPresent(isSystem, forKey: .isSystem)
        try container.encodeIfPresent(memberCount, forKey: .memberCount)
        try container.encodeIfPresent(sysCreatedAt, forKey: .sysCreatedAt)
    }
}


extension TenantRoleDto: Identifiable {}
