//
// TenantMemberEntityDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Serialized representation of a tenant membership (subject-to-tenant link) for snapshot export/import. */
public struct TenantMemberEntityDto: Sendable, Codable, Hashable {

    public var id: String?
    public var tenantId: String?
    public var subjectId: String?
    public var sysCreatedAt: Date?
    public var sysUpdatedAt: Date?
    public var directPermissions: [String]?
    public var label: String?
    public var limitTo24Hours: Bool?
    public var createdFromInviteId: String?
    public var lastUsedAt: Date?
    public var lastUsedIp: String?
    public var lastUsedUserAgent: String?
    public var revokedAt: Date?

    public init(id: String? = nil, tenantId: String? = nil, subjectId: String? = nil, sysCreatedAt: Date? = nil, sysUpdatedAt: Date? = nil, directPermissions: [String]? = nil, label: String? = nil, limitTo24Hours: Bool? = nil, createdFromInviteId: String? = nil, lastUsedAt: Date? = nil, lastUsedIp: String? = nil, lastUsedUserAgent: String? = nil, revokedAt: Date? = nil) {
        self.id = id
        self.tenantId = tenantId
        self.subjectId = subjectId
        self.sysCreatedAt = sysCreatedAt
        self.sysUpdatedAt = sysUpdatedAt
        self.directPermissions = directPermissions
        self.label = label
        self.limitTo24Hours = limitTo24Hours
        self.createdFromInviteId = createdFromInviteId
        self.lastUsedAt = lastUsedAt
        self.lastUsedIp = lastUsedIp
        self.lastUsedUserAgent = lastUsedUserAgent
        self.revokedAt = revokedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tenantId
        case subjectId
        case sysCreatedAt
        case sysUpdatedAt
        case directPermissions
        case label
        case limitTo24Hours
        case createdFromInviteId
        case lastUsedAt
        case lastUsedIp
        case lastUsedUserAgent
        case revokedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(subjectId, forKey: .subjectId)
        try container.encodeIfPresent(sysCreatedAt, forKey: .sysCreatedAt)
        try container.encodeIfPresent(sysUpdatedAt, forKey: .sysUpdatedAt)
        try container.encodeIfPresent(directPermissions, forKey: .directPermissions)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(limitTo24Hours, forKey: .limitTo24Hours)
        try container.encodeIfPresent(createdFromInviteId, forKey: .createdFromInviteId)
        try container.encodeIfPresent(lastUsedAt, forKey: .lastUsedAt)
        try container.encodeIfPresent(lastUsedIp, forKey: .lastUsedIp)
        try container.encodeIfPresent(lastUsedUserAgent, forKey: .lastUsedUserAgent)
        try container.encodeIfPresent(revokedAt, forKey: .revokedAt)
    }
}


extension TenantMemberEntityDto: Identifiable {}
