//
// TestFireDryRunRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request body for the dry-run test fire endpoint. Mirrors the editor&#39;s in-memory rule shape — only the fields needed to render a notification. */
public struct TestFireDryRunRequest: Sendable, Codable, Hashable {

    public var name: String?
    public var severity: AlertRuleSeverity?
    public var channels: [CreateAlertRuleChannelRequest]?

    public init(name: String? = nil, severity: AlertRuleSeverity? = nil, channels: [CreateAlertRuleChannelRequest]? = nil) {
        self.name = name
        self.severity = severity
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case severity
        case channels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(severity, forKey: .severity)
        try container.encodeIfPresent(channels, forKey: .channels)
    }
}

