//
// TherapySettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TherapySettings: Sendable, Codable, Hashable {

    public var id: String?
    public var timestamp: Date?
    public var mills: Int64?
    public var utcOffset: Int?
    public var device: String?
    public var app: String?
    public var dataSource: String?
    public var correlationId: String?
    public var legacyId: String?
    public var createdAt: Date?
    public var modifiedAt: Date?
    public var profileName: String?
    public var timezone: String?
    public var units: String?
    public var dia: Double?
    public var carbsHr: Int?
    public var delay: Int?
    public var perGIValues: Bool?
    public var carbsHrHigh: Int?
    public var carbsHrMedium: Int?
    public var carbsHrLow: Int?
    public var delayHigh: Int?
    public var delayMedium: Int?
    public var delayLow: Int?
    public var loopSettings: LoopProfileSettings?
    public var isDefault: Bool?
    public var enteredBy: String?
    public var isExternallyManaged: Bool?
    public var startDate: String?
    public var additionalProperties: [String: JSONValue]?

    public init(id: String? = nil, timestamp: Date? = nil, mills: Int64? = nil, utcOffset: Int? = nil, device: String? = nil, app: String? = nil, dataSource: String? = nil, correlationId: String? = nil, legacyId: String? = nil, createdAt: Date? = nil, modifiedAt: Date? = nil, profileName: String? = nil, timezone: String? = nil, units: String? = nil, dia: Double? = nil, carbsHr: Int? = nil, delay: Int? = nil, perGIValues: Bool? = nil, carbsHrHigh: Int? = nil, carbsHrMedium: Int? = nil, carbsHrLow: Int? = nil, delayHigh: Int? = nil, delayMedium: Int? = nil, delayLow: Int? = nil, loopSettings: LoopProfileSettings? = nil, isDefault: Bool? = nil, enteredBy: String? = nil, isExternallyManaged: Bool? = nil, startDate: String? = nil, additionalProperties: [String: JSONValue]? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.mills = mills
        self.utcOffset = utcOffset
        self.device = device
        self.app = app
        self.dataSource = dataSource
        self.correlationId = correlationId
        self.legacyId = legacyId
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
        self.profileName = profileName
        self.timezone = timezone
        self.units = units
        self.dia = dia
        self.carbsHr = carbsHr
        self.delay = delay
        self.perGIValues = perGIValues
        self.carbsHrHigh = carbsHrHigh
        self.carbsHrMedium = carbsHrMedium
        self.carbsHrLow = carbsHrLow
        self.delayHigh = delayHigh
        self.delayMedium = delayMedium
        self.delayLow = delayLow
        self.loopSettings = loopSettings
        self.isDefault = isDefault
        self.enteredBy = enteredBy
        self.isExternallyManaged = isExternallyManaged
        self.startDate = startDate
        self.additionalProperties = additionalProperties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case mills
        case utcOffset
        case device
        case app
        case dataSource
        case correlationId
        case legacyId
        case createdAt
        case modifiedAt
        case profileName
        case timezone
        case units
        case dia
        case carbsHr
        case delay
        case perGIValues
        case carbsHrHigh
        case carbsHrMedium
        case carbsHrLow
        case delayHigh
        case delayMedium
        case delayLow
        case loopSettings
        case isDefault
        case enteredBy
        case isExternallyManaged
        case startDate
        case additionalProperties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(mills, forKey: .mills)
        try container.encodeIfPresent(utcOffset, forKey: .utcOffset)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(dataSource, forKey: .dataSource)
        try container.encodeIfPresent(correlationId, forKey: .correlationId)
        try container.encodeIfPresent(legacyId, forKey: .legacyId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(modifiedAt, forKey: .modifiedAt)
        try container.encodeIfPresent(profileName, forKey: .profileName)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(units, forKey: .units)
        try container.encodeIfPresent(dia, forKey: .dia)
        try container.encodeIfPresent(carbsHr, forKey: .carbsHr)
        try container.encodeIfPresent(delay, forKey: .delay)
        try container.encodeIfPresent(perGIValues, forKey: .perGIValues)
        try container.encodeIfPresent(carbsHrHigh, forKey: .carbsHrHigh)
        try container.encodeIfPresent(carbsHrMedium, forKey: .carbsHrMedium)
        try container.encodeIfPresent(carbsHrLow, forKey: .carbsHrLow)
        try container.encodeIfPresent(delayHigh, forKey: .delayHigh)
        try container.encodeIfPresent(delayMedium, forKey: .delayMedium)
        try container.encodeIfPresent(delayLow, forKey: .delayLow)
        try container.encodeIfPresent(loopSettings, forKey: .loopSettings)
        try container.encodeIfPresent(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(enteredBy, forKey: .enteredBy)
        try container.encodeIfPresent(isExternallyManaged, forKey: .isExternallyManaged)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(additionalProperties, forKey: .additionalProperties)
    }
}


extension TherapySettings: Identifiable {}
