//
// TimeInRangeMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeInRangeMetrics: Sendable, Codable, Hashable {

    public var percentages: TimeInRangePercentages?
    public var durations: TimeInRangeDurations?
    public var episodes: TimeInRangeEpisodes?
    public var rangeStats: TimeInRangeDetailedStats?

    public init(percentages: TimeInRangePercentages? = nil, durations: TimeInRangeDurations? = nil, episodes: TimeInRangeEpisodes? = nil, rangeStats: TimeInRangeDetailedStats? = nil) {
        self.percentages = percentages
        self.durations = durations
        self.episodes = episodes
        self.rangeStats = rangeStats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percentages
        case durations
        case episodes
        case rangeStats
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(percentages, forKey: .percentages)
        try container.encodeIfPresent(durations, forKey: .durations)
        try container.encodeIfPresent(episodes, forKey: .episodes)
        try container.encodeIfPresent(rangeStats, forKey: .rangeStats)
    }
}

