//
// TimeRange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeRange: Sendable, Codable, Hashable {

    public var startTime: String?
    public var endTime: String?

    public init(startTime: String? = nil, endTime: String? = nil) {
        self.startTime = startTime
        self.endTime = endTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startTime
        case endTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startTime, forKey: .startTime)
        try container.encodeIfPresent(endTime, forKey: .endTime)
    }
}

