//
// TimeSeriesPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeSeriesPoint: Sendable, Codable, Hashable {

    public var timestamp: Int64?
    public var value: Double?

    public init(timestamp: Int64? = nil, value: Double? = nil) {
        self.timestamp = timestamp
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

