//
// TimeValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeValue: Sendable, Codable, Hashable {

    public var time: String?
    public var value: Double?
    public var timeAsSeconds: Int?

    public init(time: String? = nil, value: Double? = nil, timeAsSeconds: Int? = nil) {
        self.time = time
        self.value = value
        self.timeAsSeconds = timeAsSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case value
        case timeAsSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(timeAsSeconds, forKey: .timeAsSeconds)
    }
}

