//
// TimeOfDayAnalysis.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimeOfDayAnalysis: Sendable, Codable, Hashable {

    public var overnight: PeriodMetrics?
    public var morning: PeriodMetrics?
    public var afternoon: PeriodMetrics?
    public var evening: PeriodMetrics?
    public var dawnPhenomenonDetected: Bool?
    public var dawnPhenomenonMagnitude: Double?
    public var highestVariabilityPeriod: String?
    public var lowestTIRPeriod: String?
    public var mostHypoglycemiaPeriod: String?

    public init(overnight: PeriodMetrics? = nil, morning: PeriodMetrics? = nil, afternoon: PeriodMetrics? = nil, evening: PeriodMetrics? = nil, dawnPhenomenonDetected: Bool? = nil, dawnPhenomenonMagnitude: Double? = nil, highestVariabilityPeriod: String? = nil, lowestTIRPeriod: String? = nil, mostHypoglycemiaPeriod: String? = nil) {
        self.overnight = overnight
        self.morning = morning
        self.afternoon = afternoon
        self.evening = evening
        self.dawnPhenomenonDetected = dawnPhenomenonDetected
        self.dawnPhenomenonMagnitude = dawnPhenomenonMagnitude
        self.highestVariabilityPeriod = highestVariabilityPeriod
        self.lowestTIRPeriod = lowestTIRPeriod
        self.mostHypoglycemiaPeriod = mostHypoglycemiaPeriod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case overnight
        case morning
        case afternoon
        case evening
        case dawnPhenomenonDetected
        case dawnPhenomenonMagnitude
        case highestVariabilityPeriod
        case lowestTIRPeriod
        case mostHypoglycemiaPeriod
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(overnight, forKey: .overnight)
        try container.encodeIfPresent(morning, forKey: .morning)
        try container.encodeIfPresent(afternoon, forKey: .afternoon)
        try container.encodeIfPresent(evening, forKey: .evening)
        try container.encodeIfPresent(dawnPhenomenonDetected, forKey: .dawnPhenomenonDetected)
        try container.encodeIfPresent(dawnPhenomenonMagnitude, forKey: .dawnPhenomenonMagnitude)
        try container.encodeIfPresent(highestVariabilityPeriod, forKey: .highestVariabilityPeriod)
        try container.encodeIfPresent(lowestTIRPeriod, forKey: .lowestTIRPeriod)
        try container.encodeIfPresent(mostHypoglycemiaPeriod, forKey: .mostHypoglycemiaPeriod)
    }
}

