//
// TrackerMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum TrackerMode: String, Sendable, Codable, CaseIterable {
    case duration = "Duration"
    case event = "Event"
}
