//
// TrackerMarkerDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrackerMarkerDto: Sendable, Codable, Hashable {

    public var id: String?
    public var definitionId: String?
    public var name: String?
    public var category: TrackerCategory?
    public var time: Int64?
    public var icon: String?
    public var color: ChartColor?

    public init(id: String? = nil, definitionId: String? = nil, name: String? = nil, category: TrackerCategory? = nil, time: Int64? = nil, icon: String? = nil, color: ChartColor? = nil) {
        self.id = id
        self.definitionId = definitionId
        self.name = name
        self.category = category
        self.time = time
        self.icon = icon
        self.color = color
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case definitionId
        case name
        case category
        case time
        case icon
        case color
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(definitionId, forKey: .definitionId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(color, forKey: .color)
    }
}


extension TrackerMarkerDto: Identifiable {}
