//
// TrackerPresetDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrackerPresetDto: Sendable, Codable, Hashable {

    public var id: String?
    public var name: String?
    public var definitionId: String?
    public var definitionName: String?
    public var defaultStartNotes: String?
    public var createdAt: Date?

    public init(id: String? = nil, name: String? = nil, definitionId: String? = nil, definitionName: String? = nil, defaultStartNotes: String? = nil, createdAt: Date? = nil) {
        self.id = id
        self.name = name
        self.definitionId = definitionId
        self.definitionName = definitionName
        self.defaultStartNotes = defaultStartNotes
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case definitionId
        case definitionName
        case defaultStartNotes
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(definitionId, forKey: .definitionId)
        try container.encodeIfPresent(definitionName, forKey: .definitionName)
        try container.encodeIfPresent(defaultStartNotes, forKey: .defaultStartNotes)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


extension TrackerPresetDto: Identifiable {}
