//
// TrackerCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum TrackerCategory: String, Sendable, Codable, CaseIterable {
    case consumable = "Consumable"
    case reservoir = "Reservoir"
    case appointment = "Appointment"
    case reminder = "Reminder"
    case custom = "Custom"
    case sensor = "Sensor"
    case cannula = "Cannula"
    case battery = "Battery"
}
