//
// TrackersGetDefinitionsCategoryParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TrackersGetDefinitionsCategoryParameter: Sendable, Codable, Hashable {
    case typeTrackerCategory(TrackerCategory)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTrackerCategory(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TrackerCategory.self) {
            self = .typeTrackerCategory(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of TrackersGetDefinitionsCategoryParameter"))
        }
    }
}

