//
// TrackerPillsSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrackerPillsSettings: Sendable, Codable, Hashable {

    public var enabled: Bool?
    public var visibility: String?

    public init(enabled: Bool? = nil, visibility: String? = nil) {
        self.enabled = enabled
        self.visibility = visibility
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case visibility
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(visibility, forKey: .visibility)
    }
}

