//
// TrackerDefinitionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrackerDefinitionDto: Sendable, Codable, Hashable {

    public var id: String?
    public var name: String?
    public var description: String?
    public var category: TrackerCategory?
    public var icon: String?
    public var triggerEventTypes: [String]?
    public var triggerNotesContains: String?
    public var lifespanHours: Int?
    public var notificationThresholds: [NotificationThresholdDto]?
    public var isFavorite: Bool?
    /** Dashboard visibility: Off, Always, Info, Warn, Hazard, Urgent */
    public var dashboardVisibility: DashboardVisibility?
    /** Visibility level for this tracker (Public, Private, RoleRestricted) */
    public var visibility: TrackerVisibility?
    /** Event type to create when tracker is started (for Nightscout compatibility) */
    public var startEventType: String?
    /** Event type to create when tracker is completed (for Nightscout compatibility) */
    public var completionEventType: String?
    /** Tracker mode: Duration or Event */
    public var mode: TrackerMode?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: String? = nil, name: String? = nil, description: String? = nil, category: TrackerCategory? = nil, icon: String? = nil, triggerEventTypes: [String]? = nil, triggerNotesContains: String? = nil, lifespanHours: Int? = nil, notificationThresholds: [NotificationThresholdDto]? = nil, isFavorite: Bool? = nil, dashboardVisibility: DashboardVisibility? = nil, visibility: TrackerVisibility? = nil, startEventType: String? = nil, completionEventType: String? = nil, mode: TrackerMode? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.category = category
        self.icon = icon
        self.triggerEventTypes = triggerEventTypes
        self.triggerNotesContains = triggerNotesContains
        self.lifespanHours = lifespanHours
        self.notificationThresholds = notificationThresholds
        self.isFavorite = isFavorite
        self.dashboardVisibility = dashboardVisibility
        self.visibility = visibility
        self.startEventType = startEventType
        self.completionEventType = completionEventType
        self.mode = mode
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case category
        case icon
        case triggerEventTypes
        case triggerNotesContains
        case lifespanHours
        case notificationThresholds
        case isFavorite
        case dashboardVisibility
        case visibility
        case startEventType
        case completionEventType
        case mode
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(triggerEventTypes, forKey: .triggerEventTypes)
        try container.encodeIfPresent(triggerNotesContains, forKey: .triggerNotesContains)
        try container.encodeIfPresent(lifespanHours, forKey: .lifespanHours)
        try container.encodeIfPresent(notificationThresholds, forKey: .notificationThresholds)
        try container.encodeIfPresent(isFavorite, forKey: .isFavorite)
        try container.encodeIfPresent(dashboardVisibility, forKey: .dashboardVisibility)
        try container.encodeIfPresent(visibility, forKey: .visibility)
        try container.encodeIfPresent(startEventType, forKey: .startEventType)
        try container.encodeIfPresent(completionEventType, forKey: .completionEventType)
        try container.encodeIfPresent(mode, forKey: .mode)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


extension TrackerDefinitionDto: Identifiable {}
