//
// TreatmentSummaryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request model for treatment summary calculation */
public struct TreatmentSummaryRequest: Sendable, Codable, Hashable {

    /** Optional collection of bolus deliveries */
    public var boluses: [Bolus]?
    /** Optional collection of carb intakes */
    public var carbIntakes: [CarbIntake]?

    public init(boluses: [Bolus]? = nil, carbIntakes: [CarbIntake]? = nil) {
        self.boluses = boluses
        self.carbIntakes = carbIntakes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case boluses
        case carbIntakes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(boluses, forKey: .boluses)
        try container.encodeIfPresent(carbIntakes, forKey: .carbIntakes)
    }
}

