//
// UpdateClockFaceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateClockFaceRequest: Sendable, Codable, Hashable {

    public var name: String?
    public var config: ClockFaceConfig?

    public init(name: String? = nil, config: ClockFaceConfig? = nil) {
        self.name = name
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

