//
// UpdateChatIdentityLinkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateChatIdentityLinkRequest: Sendable, Codable, Hashable {

    public var label: String?
    public var displayName: String?

    public init(label: String? = nil, displayName: String? = nil) {
        self.label = label
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case displayName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(displayName, forKey: .displayName)
    }
}

