//
// UpdateUserPreferencesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request to update user preferences */
public struct UpdateUserPreferencesRequest: Sendable, Codable, Hashable {

    /** User's preferred language code (e.g., \"en\", \"fr\", \"de\") */
    public var preferredLanguage: String?

    public init(preferredLanguage: String? = nil) {
        self.preferredLanguage = preferredLanguage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case preferredLanguage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(preferredLanguage, forKey: .preferredLanguage)
    }
}

