//
// UpdateGrantRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request to update an existing grant&#39;s label and/or scopes */
public struct UpdateGrantRequest: Sendable, Codable, Hashable {

    /** New user-facing label for the grant; null leaves the existing label unchanged. */
    public var label: String?
    /** Updated set of authorized scopes; null leaves the existing scopes unchanged. */
    public var scopes: [String]?

    public init(label: String? = nil, scopes: [String]? = nil) {
        self.label = label
        self.scopes = scopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case scopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(scopes, forKey: .scopes)
    }
}

