//
// UploaderPlatform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public enum UploaderPlatform: String, Sendable, Codable, CaseIterable {
    case android = "android"
    case ios = "ios"
    case desktop = "desktop"
    case web = "web"
}
