//
// UploaderSetupResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response model for uploader setup instructions */
public struct UploaderSetupResponse: Sendable, Codable, Hashable {

    public var app: UploaderApp?
    /** Base URL for this Nocturne instance */
    public var baseUrl: String?
    /** Deep-link URL for apps that support OAuth device authorization via QR code (e.g. xdrip://connect/nocturne?url=https://your-instance.com). When present, the frontend shows a QR code and inline device-code input. */
    public var connectUrl: String?

    public init(app: UploaderApp? = nil, baseUrl: String? = nil, connectUrl: String? = nil) {
        self.app = app
        self.baseUrl = baseUrl
        self.connectUrl = connectUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case app
        case baseUrl
        case connectUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(baseUrl, forKey: .baseUrl)
        try container.encodeIfPresent(connectUrl, forKey: .connectUrl)
    }
}

