//
// UpsertHeartRateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request body for upserting a heart rate measurement via the V4 API. */
public struct UpsertHeartRateRequest: Sendable, Codable, Hashable {

    /** When the heart rate measurement was taken. */
    public var timestamp: Date?
    /** UTC offset in minutes at the time of the event, for local-time display. */
    public var utcOffset: Int?
    /** Heart rate in beats per minute. */
    public var bpm: Int?
    /** Sensor accuracy indicator (device-specific scale). */
    public var accuracy: Int?
    /** Identifier of the wearable or sensor device. */
    public var device: String?
    /** Name of the application that submitted this record. */
    public var app: String?
    /** Upstream data source identifier. */
    public var dataSource: String?

    public init(timestamp: Date? = nil, utcOffset: Int? = nil, bpm: Int? = nil, accuracy: Int? = nil, device: String? = nil, app: String? = nil, dataSource: String? = nil) {
        self.timestamp = timestamp
        self.utcOffset = utcOffset
        self.bpm = bpm
        self.accuracy = accuracy
        self.device = device
        self.app = app
        self.dataSource = dataSource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case utcOffset
        case bpm
        case accuracy
        case device
        case app
        case dataSource
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(utcOffset, forKey: .utcOffset)
        try container.encodeIfPresent(bpm, forKey: .bpm)
        try container.encodeIfPresent(accuracy, forKey: .accuracy)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(dataSource, forKey: .dataSource)
    }
}

