//
// UpsertBGCheckRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request body for upserting a blood glucose (BG) check record via the V4 API. */
public struct UpsertBGCheckRequest: Sendable, Codable, Hashable {

    /** When the BG check was performed. */
    public var timestamp: Date?
    /** UTC offset in minutes at the time of the event, for local-time display. */
    public var utcOffset: Int?
    /** Identifier of the device that performed the check. */
    public var device: String?
    /** Name of the application that submitted this record. */
    public var app: String?
    /** Upstream data source identifier. */
    public var dataSource: String?
    /** Blood glucose reading value (validated 0-10,000). */
    public var glucose: Double?
    public var units: GlucoseUnit?
    public var glucoseType: GlucoseType?
    /** Upstream sync identifier for deduplication. */
    public var syncIdentifier: String?

    public init(timestamp: Date? = nil, utcOffset: Int? = nil, device: String? = nil, app: String? = nil, dataSource: String? = nil, glucose: Double? = nil, units: GlucoseUnit? = nil, glucoseType: GlucoseType? = nil, syncIdentifier: String? = nil) {
        self.timestamp = timestamp
        self.utcOffset = utcOffset
        self.device = device
        self.app = app
        self.dataSource = dataSource
        self.glucose = glucose
        self.units = units
        self.glucoseType = glucoseType
        self.syncIdentifier = syncIdentifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case utcOffset
        case device
        case app
        case dataSource
        case glucose
        case units
        case glucoseType
        case syncIdentifier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(utcOffset, forKey: .utcOffset)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(dataSource, forKey: .dataSource)
        try container.encodeIfPresent(glucose, forKey: .glucose)
        try container.encodeIfPresent(units, forKey: .units)
        try container.encodeIfPresent(glucoseType, forKey: .glucoseType)
        try container.encodeIfPresent(syncIdentifier, forKey: .syncIdentifier)
    }
}

