//
// UserAlarmConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserAlarmConfiguration: Sendable, Codable, Hashable {

    public var version: Int?
    public var enabled: Bool?
    public var soundEnabled: Bool?
    public var vibrationEnabled: Bool?
    public var globalVolume: Int?
    public var profiles: [AlarmProfileConfiguration]?
    public var customSounds: [CustomSoundReference]?
    public var emergencyContacts: [EmergencyContactConfig]?
    public var channels: NotificationChannelsConfig?

    public init(version: Int? = nil, enabled: Bool? = nil, soundEnabled: Bool? = nil, vibrationEnabled: Bool? = nil, globalVolume: Int? = nil, profiles: [AlarmProfileConfiguration]? = nil, customSounds: [CustomSoundReference]? = nil, emergencyContacts: [EmergencyContactConfig]? = nil, channels: NotificationChannelsConfig? = nil) {
        self.version = version
        self.enabled = enabled
        self.soundEnabled = soundEnabled
        self.vibrationEnabled = vibrationEnabled
        self.globalVolume = globalVolume
        self.profiles = profiles
        self.customSounds = customSounds
        self.emergencyContacts = emergencyContacts
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case enabled
        case soundEnabled
        case vibrationEnabled
        case globalVolume
        case profiles
        case customSounds
        case emergencyContacts
        case channels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(soundEnabled, forKey: .soundEnabled)
        try container.encodeIfPresent(vibrationEnabled, forKey: .vibrationEnabled)
        try container.encodeIfPresent(globalVolume, forKey: .globalVolume)
        try container.encodeIfPresent(profiles, forKey: .profiles)
        try container.encodeIfPresent(customSounds, forKey: .customSounds)
        try container.encodeIfPresent(emergencyContacts, forKey: .emergencyContacts)
        try container.encodeIfPresent(channels, forKey: .channels)
    }
}

