//
// V4AlarmState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct V4AlarmState: Sendable, Codable, Hashable {

    public var level: Int?
    public var type: String?
    public var message: String?
    public var triggeredMills: Int64?
    public var isSilenced: Bool?
    public var silenceExpiresMills: Int64?

    public init(level: Int? = nil, type: String? = nil, message: String? = nil, triggeredMills: Int64? = nil, isSilenced: Bool? = nil, silenceExpiresMills: Int64? = nil) {
        self.level = level
        self.type = type
        self.message = message
        self.triggeredMills = triggeredMills
        self.isSilenced = isSilenced
        self.silenceExpiresMills = silenceExpiresMills
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case level
        case type
        case message
        case triggeredMills
        case isSilenced
        case silenceExpiresMills
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(level, forKey: .level)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(triggeredMills, forKey: .triggeredMills)
        try container.encodeIfPresent(isSilenced, forKey: .isSilenced)
        try container.encodeIfPresent(silenceExpiresMills, forKey: .silenceExpiresMills)
    }
}

