//
// WidgetConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WidgetConfig: Sendable, Codable, Hashable {

    public var id: WidgetId?
    public var enabled: Bool?
    public var placement: WidgetPlacement?
    public var size: WidgetSize?
    public var settings: [String: JSONValue]?

    public init(id: WidgetId? = nil, enabled: Bool? = nil, placement: WidgetPlacement? = nil, size: WidgetSize? = nil, settings: [String: JSONValue]? = nil) {
        self.id = id
        self.enabled = enabled
        self.placement = placement
        self.size = size
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case enabled
        case placement
        case size
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(placement, forKey: .placement)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(settings, forKey: .settings)
    }
}

